### ISSUE TITLE
Tool to get/locate/correct invalid chunk

### ISSUE THREAD

**Issue by oszafraniec** [moosefs/moosefs#106]
Let's say something went wrong (HW problems) and we have file (small one < 64MB) with "INVALID COPIES". What we can do is...
```
mfsfileinfo /path/to/file_with_invalid_copies
/path/to/file_with_invalid_copies:
        chunk 0: 00000000189C9EB1_00000001 / (id:412917425 ver:1)
                copy 1: 192.168.10.111:9422 (status:INVALID)
                copy 2: 192.168.10.117:9422 (status:INVALID)
                no valid copies !!!
```
Scary, but not so much. First thing that you want to do is to use `mfsfilerepair` but... **DON'T**! It will (don't know why) delete invalid chunks and make the file `empty`. 

Next thing comes to mind is... mayby the copies are invalid, but they still are present on chunk servers. Mayby only CRC/header/someting little is wrong. So let's take a look at them... So let's find them.
```
find /moose/*/ -name chunk_00000000189C9EB1_00000001.mfs -print
```
...and you go for a walk if you have big chunkserver with a lots of chunks :)

After a walk you will have a path to a chunk with data. So you can copy it, get rid of first 8k of MFS headers, look at it and so on... Mayby the data is OK.
You can also use `mfschunktool` to check what's wrong and find out that only header/crc is not OK. Then you can make `mfschunktool -r /path/to/chunk_file.mfs` to correct this and end up with VALID chunk. 

That's a lot of time, mainly for finding a chunk file. So I have a feature request :)

`mfsgetchunkdata` tool to download raw data of given chunk id from a given chunkserver, valid or not from Moose point of view, without headers etc. Having such data we can play with it, mayby correct it, overwrite invalid file with corrected data... many things can be done to get data back instead of just looking at "missing" status and "invalid copies" only because of wrong crc
or 
`mfslocatechunk` tool to get /path/to/chunk on a chunkserver so we don't have to find it and walk too much which can be very time consuming (30min per chunk_id if you have CHSRV with 68 4TB drives and 100mln chunks on it ;) )

or mayby even extend `mfsfilerepair` with some new options to let the human decide what to do in case of INVALID COPIES... because now I have no idea what `mfsfilerepair` does (@oxide94 : more info needed) and again, **DON'T USE IT!** if you don't have chunk copies on a side, which gets you back to the beginning of this story.

All above is based on real case from today with small files = 1 chunk per file. **And the end files/data have been restored in 100%!** 😁

**Comment by borkd** [comment]
+1 on this request, especially on always considering input from human operator. But also a concern: if such functionality is exposed raw chunk data should be closely guarded and restricted by default. When access for chunk ID is sought it should be LOUD and possibly even rate limited by default, regardless whether granted or not. Keeping a lid on fishing expeditions for potentially sensitive data is hard enough without extra backdoors in one's filesystem.

@oszafraniec - please do tell what kind of HW problem resulted in simultaneous invalid copies? Both 111 and 117 in the same failure domain, or something else? Details are always useful. Thanks!

**Comment by oszafraniec** [comment]
_Sorry for TLNR ;)_ 

**HW problems...**
117 - this chunkserver had problems with motherboard, we do not know why but under heavy load it was suddenly restarting or freezing, usually every 24h we had such unexpected reset; after some time we saw chunk errors on Disks tab in last_error column on every drive in this chunkserver; we had replaced the motherboard, the reset problem went away and we let Moose to correct invalid chunk copies during rebalancing etc.; in this time we had no other idea how to "verify" chunks on this chunkserver and to force Moose to correct it. (now we know how to deal with verfication of chunks with mfschunktool, but this is another story).

After some time we had a drive failure in other chunk server 104. Because some files had goal 2 only, 7 chunks had copies on failed drive (so no copy) and on 117 chunkserver (which happend to be invalid because of the HW problems). In this situation Moose had only invalid copy on 117 and (as I assume) made another invalid copy on 111 chunkserver because of goal 2. Then MFS reported missing chunk due to invalid copies. And here starts the story I described above. 

**Chunkserver verfication...**
Because letting MFS to correct invalid chunks during some rebalancing is a long time aproach and drive failure with goal 2 file like we had can lead to problems, we started to look for invalid chunks by our selfs. We use ``mfschunktool`` on a chunkserver for it with the script below started like this:

` sudo find /moose/ -name *.mfs -exec sudo /home/moose/verMFS.sh {} \;`

```
#!/usr/bin/env bash

if [[ $EUID -ne 0 ]]
then
    echo "It needs to be started with root/sudo access”
    exit
fi

checkTest=`sudo mfschunktool -f $1 2>&1`

if [ -n "$checkTest" ]
then
    echo "$1 INVALID"
    echo "$1" >> chunkTest.log
else
    echo "$1 ok"
fi
```

You can do this on a working chunkserver as it does not change anything. After it will finish we will have a list of invalid chunks in chunkTest.log. Then we plan to stop chunkserver, move invalid chunks to safe location and start chunkserver. It will rescan drives, report it to master and because there will be undergoal chunks, master will make valid copies of them from other copies. You can also use `mfschunktool -r` to correct them, but we think it will be better to rely on second valid copy from other chunkserver. Always we have invalid copies on a side to correct them if needed.

This leads to another feature request to have some tool to verfify chunks on a chunkserver on the fly. I know there are some loops on master to check the filesystem, but they don't check chunk copies if they are valid because of performance. It would be good to start verify process on suspicious chunkserver by hand.  Meanwhile we made up the above idea to verify chunks by our selves.

_I hope the above story will help someone in a future ;)_

**Comment by borkd** [comment]
So you want a "scrub" command that is independent of the normal check loop? Same as scheduling a ```zfs scrub``` to munch through data stored in the pool, instead of waiting for a check done at read time, which on a PB-scale filesystem with hundreds of millions of files could be "some time from now"?

@acid-maker - A simple command taking a directory entry as a parameter, and verifying all data stored underneath is still safe and sound could help adoption among new users with lots of valuable data, and will certainly delight existing users. Having to bend over backwards to achieve same goal, not so much. 
Even though MooseFS hasn't lost any of my data over the years I had to resort to writing helper scripts just like @oszafraniec. For a large deployment most folks would call that bending over backwards, and go look elsewhere.

One site-specific implementation detail to account for: whatever mechanism is used to split the read spree on the chunkservers it needs to be done at such a rate so wheels don't fall off because of timeouts.

+100 for making scrub the top of the feature priority list.

**Comment by guestisp** [comment]
+1000 for this.
Is something that will be added?

**Comment by 4Dolio** [comment]
I am also interested in this feature/process

**Comment by guestisp** [comment]
> I am also interested in this feature/process
It's funny to read this. When I've asked the same thing for the same reason on LizardFS, you were against my proposal, because the `find` method is enough and there is no need to add something else in the code.

**Comment by 4Dolio** [comment]
I am pretty sure I have voiced my concern about reverse resolution of chunks needing to be easier to do with a native tool.  My method is to dump metadata to human form and slowly reverse resolve which in only slightly better than the brute force method of recursing the whole filesystem.

**Comment by borkd** [comment]
bump

**Comment by oszafraniec** [comment]
Again we encountered situation (a little different from above) when master thinks there are no chunk copies, but we know there are ones but can't tell where right away to hand it to him. We have some strange drive failure that stops chunkserver to scan the drive. Scanning stops around 51% and hangs there cousing even chunkserver disconnections after some time etc. We think it is some error in XFS filesystem, not Moose problem... But... We still can read from this drive. We have 94 files missing after unplugging this drive from moose. Now we need to mfsfileinfo every file that is missing, get the chunk ID with no copies, make "find /broken_drive -name chunkID -print", wait a lot of time 94 times to get those chunks back.

It's a pain... It's not a first time we need a native tool to do locate/get/correct chunk data. Please, make it happen :) 

**Or just write how we can decode chunk path/folder from it's ID. It will save a lot of find loops.**

**Comment by jwest75674** [comment]
I just wanted to add here that I too would appreciate a reverse resolution capability. 

I am trying to manually download chunk files directly and reconsitute them manually for more granular control over which chunk server I am pulling from. (Learning excersice mainly)

Reading though the source files I haven't been able it identify the correct function definition, but what I was working towards seems like an incorrect path.

If I hold the chunk ID and server can I manually request the chunks from the server somehow?

**Comment by onlyjob** [comment]
To trace chunkfile back to the file it belongs, I recommend to incorporate inode number into chunkfile file name.

**Comment by chogata** [comment]
@jwest75674 - there is no "human friendly" way to ask a chunkserver for a chunk - you have to form proper mfs protocol packets and send them to the chunkserver, then you can get your chunk. If you want to delve into the source code for the purpose of learning, I recommend [mfschunkserver/replicator.c](https://github.com/moosefs/moosefs/blob/master/mfschunkserver/replicator.c) - this is the replicator and as part of its work it just requests whole chunks, without any caching or read-ahead mechanisms that complicate the code used in the client.

@onlyjob - this is not feasible, because of snapshots. A chunk can belong to inode A, then be snanpshotted and start to belong to inodes A and B and then A or B are changed and the chunk needs to be splitted into two versions and at this point we can no longer say if it's A or B. Not to mention that we don't know B at all, because we cannot "add" it during snapshotting - this would turn a quick operation on metadata into an operation that takes literal ages. The only thing we could keep is the "original" inode, but after several snapshots and changes in the system this information could get so far from the actual truth, at the end of the day it couldn't be trusted at all and would only be confusing.

**Comment by oszafraniec** [comment]
Just as +1 and a reminder... we had again same situation... INVALID COPIES reported... found 1 remaining copy of a chunk/file shown as INVALID by mfsfileinfo... skipped first 8k and got file data in perfect shape.

**Comment by jkiebzak** [comment]
+1 . It is **very** painful to do a `find` against all harddrives a chunkserver is managing, especially when you are using dense drives/dense servers. Multiple the run time of `find` if you have multiple chunks to find. There should be a way to query the chunkserver for the *path* of the chunk on the local chunkserver - even having the raw API, someone could then put together a script to do the work.

**Comment by oszafraniec** [comment]
> There should be a way to query the chunkserver for the _path_ of the chunk on the local chunkserver - even having the raw API, someone could then put together a script to do the work.

I think not a path... raw chunk data from selected chunk by id is all we need. You know which file is invalid. mfsfileinfo can show you avaible (invalid) chunks. New command f.ex. mfsgetchunkdata with filename and chunkid provided should give you what we are looking with find... with 8kB chechsum stripped etc.... Just a raw file data. And we are home.

**Comment by chogata** [comment]
This is on our feature list, but it requires changes in chunk server communication protocols, so it's not just a case of writing a small tool. It will be added along other changes in MooseFS administration tools.

**Comment by chogata** [comment]
MooseFS 4 now has an option in its `mfsfileinfo` tool to show paths to chunks of a file. Also, the `mfschunktool` has new options when it comes to chunk fixing. Please, upgrade and test. If comments are needed, please open a new issue or discussion (whichever is appropriate for the info you want to post).
