### ISSUE TITLE
trashtime TIMEDURATION is multiple of 3600

### ISSUE THREAD

**Issue by honza801** [moosefs/moosefs#110]
hi,

i was very confused with settrashtime for about 8 hours. setting the trash time, nothing was changed and i dont know why. 
```
/mnt/mfs# mfsgettrashtime .
.: 3600
/mnt/mfs# mfssettrashtime -r 10 .
.:
 inodes with trashtime changed:              0
 inodes with trashtime not changed:         11
 inodes with permission denied:              0
```
following went ok:
```
/mnt/mfs# mfssettrashtime -r 0 .
.:
 inodes with trashtime changed:             11
 inodes with trashtime not changed:          0
 inodes with permission denied:              0
/mnt/mfs# mfsgettrashtime .
.: 0
```

next test is very annoying. i want to set 60 seconds, but something else appears.
```
/mnt/mfs# mfssettrashtime -r 60 .
.:
 inodes with trashtime changed:             11
 inodes with trashtime not changed:          0
 inodes with permission denied:              0
/mnt/mfs# mfsgettrashtime .
.: 3600
```

and finally, this is how it really works. ceil of multiples of 3600.
```
/mnt/mfs# mfssettrashtime -r 3601 .
.:
 inodes with trashtime changed:             11
 inodes with trashtime not changed:          0
 inodes with permission denied:              0
/mnt/mfs# mfsgettrashtime .
.: 7200
```

please document this "feature". short mention in mfsexports.cfg and pdf documentation will be enough. this must drive people crazy.

thanks
jan

**Comment by oxide94** [comment]
Hi @honza801,

Since MooseFS 3.0.74 trashtime is set in hours, this is why it behaves like you described.
See more here: in this part of `NEWS` file: https://github.com/moosefs/moosefs/blob/master/NEWS#L207 and this commit: https://github.com/moosefs/moosefs/commit/cf8285c1e17267adab651eb570c1466b3ed60f37.

Thank you,
Best regards,
Peter / MooseFS Team

**Comment by honza801** [comment]
hi @oxide94 ,

good to have this in NEWS and commit message. but there is nothing about it in the documentation nor example config files/man pages. please add the information there. i hope these are the places users are looking for the informations.

thanks
jan

**Comment by oxide94** [comment]
Hi @honza801,
sure, thanks for pointing this out.

Cheers,
Peter / MooseFS Team

**Comment by leezout** [comment]
So let's say you want to setup a trashtime of 24hours on a particular folder.
 mfssettrashtime -r 24 *

When I run mfsgettrashtime it gives me 3600

**Comment by honza801** [comment]
mfssettrashtime parameter is in seconds ceiled to hours. you should run
mfssettrashtime -r $((24*60*60)) *

confusing, right? :) thats why i recommend to amend the documentation and config files comments.
