### ISSUE TITLE
Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by Sveeeeeen** [moosefs/moosefs#111]
Hello,

Ubuntu 18 is out. When do you plan to support it?

Sven

**Comment by oxide94** [comment]
Hi @Sveeeeeen,

we are working on it and most probably MooseFS 3.0.101 release will include Ubuntu 18.04 LTS support.

Thanks,

Best regards,
Peter / MooseFS Team

**Comment by oxide94** [comment]
Released: https://github.com/moosefs/moosefs/releases/tag/v3.0.101 :)

Best regards,
Peter / MooseFS Team

**Comment by guestisp** [comment]
In release note is wrote 3.0.100

**Comment by oxide94** [comment]
@guestisp: Fixed, thanks!

Best regards,
Peter / MooseFS Team
