### ISSUE TITLE
Full scrub

### ISSUE THREAD

**Issue by guestisp** [moosefs/moosefs#117]
I've asked this in LizardFS, tried to make a patch (I'm not a C++) that was rejected (correctly, it was a mess) but at the end, there was almost no interest in adding such feature.

Let's see if MooseFS is more open.

All SDS and RAID systems has scrub features. I know that MooseFS periodically checks all chunks, but it does at very very low speed. On *huge* clusters, many millions of chunks, the whole scrub will take months or years.

Let's assume a storage used as backup archive. 
You don't need goal > 2 (or maybe > 1).
You store files that won't be read for many months/years, thus the automatic checksumming on each read won't be useful.

Now, a disk fails. MooseFS start healing from the other replica. The other replica wasn't read for many months (it's a backup server, you write once and hopefully you won't read it anymore) and during the healing, checksum fails on file. You have lost some data. That file is not readable anymore.

is the same as URE during a raid rebuild. If you don't periodically scrub the whole array, you'll risk to hit an URE during a rebuild and you are gone. (That's why some RAID controller periodically scrube the whole array **and** force a full-surface scan reallocating any bad sectors, in addition to SMART tests)

LizardFS is able to prefer local server (during reads) , so one workaround is to locally mount the cluster on a chunkserver, run a `find` and read every file redirecting to `>/dev/null`. As Lizard is preferring the local chunkserver, this operation will scrub the single server. I don't like this workaround.

Would be possible to implement what every other SDS/RAID (software or hardware) does ?
A manually triggered scrub that will verify checksum for all files from all chunkservers at a faster speed than normal HDD TEST and automatically stop when all chunks were scrubbed. Maybe with a configurable speed limit (or based on the current I/O on the cluster itself, like mdadm does. Higher the load, lower the scrubbing speed should be)

**Comment by oszafraniec** [comment]
Similar idea was discussed in this issue: #106

**Comment by guestisp** [comment]
Exactly and exactly for the same reasons
I'm closing this issue, as duplicate
