### ISSUE TITLE
Use fadvise(POSIX_FADV_DONTNEED) in chunk test loop?

### ISSUE THREAD

**Issue by zcalusic** [moosefs/moosefs#118]
Rarely have I suggested using fadvise() flags, more often I fought against improper use of those :smile: but maybe, just maybe, fadvise(POSIX_FADV_DONTNEED) could really be useful in chunk test loop.

Here's an example, one of my chunkservers has 16GB of RAM, let's say that around 10GB of those is available for the page cache. With default test period `HDD_TEST_FREQ = 10` and with mostly large files (i.e. chunks are most often exactly 64 MB), it takes about 10240/64*10 =~ less than half an hour before chunk test loop basically flushes (fills) the page cache with data from mostly unneeded chunks. Of course, in reality chunk test loop will compete with other users of the available memory. This is where I feel like fadvise(POSIX_FADV_DONTNEED) could be beneficial, to explicitely advise the kernel that cached data of recently checked chunk won't be needed again soon (typically days pass before it's checked again). That way memory can be immediately released by the kernel and (re)used for caching more useful pages instead.

It might also be a good idea to add this feature as a mfschunkserver.cfg tunable, for starters, so everybody can compare the effect of turning it on on their workload, easily.

I don't expect any stellar improvements, Linux MM is able to cope with current situation pretty well, yet in some corner cases it might be beneficial to manage RAM more efficiently by means of fadvise().

Thanks for considering!

**Comment by guestisp** [comment]
The same was asked in LizardFS, I think this is a good feature to add.

**Comment by acid-maker** [comment]
I like that. I'm not a huge fan of fadvise, but here it might help a bit. Why do you think that it should be switchable in config? Is there any possibility that it would slow down CS? Maybe it won't change anything (this is what I expect), but it shouldn't work worse with fadvise that without it. Using fadvise here seems to be very logical.

**Comment by acid-maker** [comment]
Added to code - without option. I don't want to add too many options to mfschunkserver.cfg, but if you convince me that it might be a good idea then I will add it and then commit this change.

**Comment by guestisp** [comment]
On small cluster may be useful to warm up the cache with all chunks by using the chunk test loop?

Just thinking because in my case i'll use fadvice always

**Comment by zcalusic** [comment]
@acid-maker possibly only to make it easier to test the effects with it turned on/off. No, I don't expect that it will slow down CS, but until it's properly tested in the wild, we can't be sure. Though, I also agree it's better not to have too many tunables in the long run.

Maybe I'm influenced by the Kubernetes model. First there's an alpha feature that is by default off, and you can turn it on if you wish to test it. Then after some time, when the new feature is well tested by the community, it is turned on by default. IMHO, a pretty neat model, and you always stay in control.

**Comment by guestisp** [comment]
@zcalusic Pretty neat and the proper way to do changes to a software, imo

**Comment by zcalusic** [comment]
Just one more thing, fadvise() flag should only be used for chunk test loop reads (when CS initiates background jobs). Whenever chunk is read by client, that one SHOULD be left cached in RAM, 'cause that really improves performance, especially if there's enough RAM in CS.

**Comment by guestisp** [comment]
:+1:

**Comment by guestisp** [comment]
Simple question as a noob: why opening a chunk for testing with `fadvise(POSIX_FADV_DONTNEED) ` will flush caches? If chunks is already in cache (because read by a client), reopening it with `fadvise(POSIX_FADV_DONTNEED)` will flush it ?

**Comment by acid-maker** [comment]
@zcalusic 
Exactly. After adding options I'll commit this code (probably today) but without closing this 'issue', so we will be able to write about our observations.

BTW. I do atime/mtime only initially - then track lastiotime by myself, so even with noatime option (which is good in case of CS) it should work quite well. Also consider using 'relatime' instead of 'noatime'. Relatime updates atime only once a day (or when it becomes higher than mtime), so it is almost as efficient as 'noatime', but much more 'sane' :)

**Comment by acid-maker** [comment]
@guestisp posix_fadvise(fd,0,0,POSIX_FADV_DONTNEED) flushes cache, so adding it before reading doesn't make sense. This can be only added before close. Check Linux kernel code: https://github.com/torvalds/linux/blob/786b71f5b754273ccef6d9462e52062b3e1f9877/mm/fadvise.c#L119

**Comment by guestisp** [comment]
Ok, so if file is already in cache, opening it again for chunk test and closing with `posix_fadvise(fd,0,0,POSIX_FADV_DONTNEED)` will drain that affected memory pages (thus, removing the file)

**Comment by zcalusic** [comment]
@acid-maker if you do keep track of chunk atime/mtime internally, then I must admit your initial proposal sounds perfect. Test chunk only if some configurable time has passed since the last read/write, that's actually a brilliant idea. :+1:

BTW, I turned atime off on MFS mounts mostly because I noticed that atime accounting makes roundtrips to master, and in some of my use cases, a lot of changelog was generated purely due to atime changes. Also with my master being quite far away from clients (WAN MFS deployment), it was my deliberate decision to turn it off explicitely, for all MFS mounts.

But generally, I don't hate it, and never turn it off on locally mounted partitions, not even on CS. And `relatime` is default these days.
```
/dev/sdb1 on /data type ext4 (rw,relatime,data=ordered)
```

**Comment by guestisp** [comment]
> if you do keep track of chunk atime/mtime internally, then I must admit your initial proposal sounds perfect. Test chunk only if some configurable time has passed since the last read/write, that's actually a brilliant idea. +1

That's wondeful. if you have a huge cluster with millions of chunks, there is no need to check what was already read a couple of day ago (thus passing the crc check on reads) when you have chunks with last access 5 years ago.

> BTW, I turned atime off on MFS mounts mostly because I noticed that atime accounting makes roundtrips to master, and in some of my use cases, a lot of changelog was generated purely due to atime changes. Also with my master being quite far away from clients (WAN MFS deployment), it was my deliberate decision to turn it off explicitely, for all MFS mounts.

Is mounting with "atime" necessary, to use the atime/mtime based chunk test? 
Because, for the same reason, I'll mount with "noatime". 
Master is sending chunks location to clients upon request, thus is already able to know when a chunk is requested for a read/write operation. 
Isn't possible to use that for chunk test loop without relying to FS atime ?

**Comment by guestisp** [comment]
@acid-maker Again, thank you for your detailes responses.

As MooseFS will generate a metadata transaction on every atime change, keeping metadata operations as low as possible should increase performances and, why not, reduce the already low risk of followers out-of-sync in case of master failure. Syncing 1 change per second is different than syncing 100 changes per seconds, obviously.

So, if I set `ATIME_MODE` to `2` in `mfsmaster.cfg` and `relatime` as mount option and `relatime` inside the VM image, should keep metadata changes very low.
