### ISSUE TITLE
More files than chunks

### ISSUE THREAD

**Issue by guestisp** [moosefs/moosefs#119]
I have more files (6685768) than chunks (6674410)

How this is possible? A file should be 1 chunk at minimum

**Comment by oszafraniec** [comment]
If the file is empty, there are no chunks for it. Mayby this is your case.

```
# touch empty-test

# ls -alh empty-test 
-rw-r--r-- 1 root root 0 Jun  4 11:00 empty-test

# mfsfileinfo empty-test 
empty-test:
        no chunks - empty file

# echo test >> empty-test 

# ls -alh empty-test 
-rw-r--r-- 1 root root 5 Jun  4 11:00 empty-test

# mfsfileinfo empty-test 
empty-test:
        chunk 0: 000000003CD50315_00000001 / (id:1020592917 ver:1)
                copy 1: 192.168.10.114:9422 (status:VALID)
                copy 2: 192.168.10.119:9422 (status:VALID)
```

**Comment by oxide94** [comment]
Also, if you use snapshots or hardlinks, some (or all) chunks are shared between original file and snapshot / hardlink.

Peter / MooseFS Team

**Comment by guestisp** [comment]
I don't have snapshots or hardlink. It's a test cluster, i've moved a couple of mailservers to this cluster, thus all files are mail files. In addition, i've created a 100GB VPS, maybe some chunks are still empty as the VM is much smaller than 100GB ?
