### ISSUE TITLE
all file times altered at read/access to file

### ISSUE THREAD

**Issue by oszafraniec** [moosefs/moosefs#12]
This is what I have observed while testing Moose mounted at FreeBSD...

```
[root@s4 ~]# stat /moose/1427833 
3976265515 272905 -rw-r--r-- 1 www www 0 686828 "May 11 16:33:40 2016" "Feb 22 11:41:37 2013" "May 11 16:32:05 2016" "Jan  1 00:59:59 1970" 4096 1342 0 /moose/1427833
[root@s4 ~]# cat /moose/1427833 > test
[root@s4 ~]# stat /moose/1427833 
3976265515 272905 -rw-r--r-- 1 www www 0 686828 "Jun 19 23:40:27 2016" "Jun 19 23:40:27 2016" "Jun 19 23:40:27 2016" "Jan  1 00:59:59 1970" 4096 1342 0 /moose/1427833
```

Moose version: 3.0.78 @ Ubuntu (recently upgraded from 2.x.x)
Mount @ Freebsd with moose client 2.0.88

It doesn't look good as all file times are changed on file read/access.

I don't know if this is freebsd or moose related. I don't have linux box by the hand to test it there.

**Comment by oxide94** [comment]
@oszafraniec 
Hi Oskar,

thanks for your report, we're checking it on our test environment. Could you please provide us with more details about your FreeBSD (FreeBSD version, `fusefs-libs` version)?

We haven't confirmed this on our test environment so far (`moosefs-client 2.0.88`, `FreeBSD pkonopelko-freebsd10 10.3-RELEASE FreeBSD 10.3-RELEASE #0 r297264: Fri Mar 25 02:10:02 UTC 2016`, `fusefs-libs-2.9.5` Master and Chunkservers are 3.0.78).

```
[root@pkonopelko-freebsd10 ~]# echo "asdasdasd" > /mnt/mfs/asd
[root@pkonopelko-freebsd10 ~]# stat /mnt/mfs/asd
3976265474 124 -rw-r--r-- 1 root wheel 0 10 "Jun 20 13:27:16 2016" "Jun 20 13:27:16 2016" "Jun 20 13:27:16 2016" "Jan  1 00:59:59 1970" 4096 1 0 /mnt/mfs/asd
[root@pkonopelko-freebsd10 ~]# cat /mnt/mfs/asd > asd
[root@pkonopelko-freebsd10 ~]# stat /mnt/mfs/asd
3976265474 124 -rw-r--r-- 1 root wheel 0 10 "Jun 20 13:27:44 2016" "Jun 20 13:27:16 2016" "Jun 20 13:27:16 2016" "Jan  1 00:59:59 1970" 4096 1 0 /mnt/mfs/asd
[root@pkonopelko-freebsd10 ~]#
```

Best regards,
Peter

**Comment by oszafraniec** [comment]
After remounting everything looks OK now (we will still observe it for some time). Strange thing, I hope it will no show up later on production env.

**Comment by acid-maker** [comment]
This is FreeBSD related. FreeBSD just before close performs 'truncate' command with current file size. Such 'truncate' doesn't change file size because file size is the same, but it changes ctime+mtime (which is correct according to posix). FreeBSD does it only first time you read file - this is why you probably notice it only from time to time.

We can think of some kind of 'workaround' for FreeBSD. Something like: "if os is FreeBSD and size doesn't change then do not change mtime+ctime during truncate".
