### ISSUE TITLE
directory is empty

### ISSUE THREAD

**Issue by com4343568** [moosefs/moosefs#120]
Hi ,

two servers are mounted on MFS, when I  exec 'll' in the directory '/mnt/chiyanfeng/mypwatcher', one is empty as shown below:

###########################################  
[root@sgemaster /mnt/chiyanfeng/mypwatcher]# ll
total 2987
drwxr-xr-x   2 root root    1900 Jun  5 11:29 exits
drwxr-xr-x   2 root root       0 Jun  5 11:10 heartbeats
drwxr-xr-x 431 root root 2039585 Jun  5 11:29 jobs
drwxr-xr-x   2 root root 1016004 Jun  5 11:29 wrappers

###########################################  
[root@sgeworker427 /mnt/chiyanfeng/mypwatcher]# ll
total 0

version :  moosefs-3.0.100 (chunkserver, mfsmaster,mfsmount)

ps: clients are mounted on /mnt

could you please help me ?
thanks a million!

**Comment by wudigailun** [comment]
You can try the mfscgi web monitoring page to see
Is mfsmount successful?

**Comment by com4343568** [comment]
@wudigailun yes, all the clients are mounted.
