### ISSUE TITLE
I have a problem with mfsmount

### ISSUE THREAD

**Issue by wudigailun** [moosefs/moosefs#121]
Hi,everybody.
I have a problem .
The mfsmaster server was shut down for some reason.
then，web server(client),mfsmount------mfsmaster，The server load is so high that it can't even ssh  connect。
mfsmount use command.
/usr/bin/mfsmount /web_data -H mfsmaster.com -o mfspassword='moosefs'

How can you avoid this problem?

Thanks。

**Comment by xandrus** [comment]
Can you tell us something more about your configuration?
I mean OS, network, MooseFS version and so on.


By the way, you can try to set timeout on MooseFS client

`/usr/bin/mfsmount /web_data -H mfsmaster.com -o mfspassword='moosefs' -o mfstimeout=30`

-o mfstimeout define maximum timeout in seconds before I/O error is returned (default: 0 - which means no timeout)
