### ISSUE TITLE
Problem with Automount after reboot

### ISSUE THREAD

**Issue by machiasiaweb** [moosefs/moosefs#123]
Hello,

I got a problem when trying automount after system restart.   However it got following result 

**
welcome to emergency mode！after logging in, type “journalctl -xb” to view system logs，“systemctl reboot” to reboot，“systemctl default” to try again to boot into default mode.
give root password for maintenance 
(or type Control-D to continue):
**

Three mount parameters in below under /etc/fstab which I have already tried but still fail.

mfsmount       /mnt/mfs        fuse    mfsmaster=mfsmaster.mydomain.com,mfsport=9421          0 0
mfsmount       /mnt/mfs        fuse    defaults                0 0
mfsmaster.mydomain.com:               /mnt/mfs        moosefs         defaults                0 0

However, if I remark those above.  System can be boot up normally and I can mount moosefs partition again but either one of the above.

I am using CentOS 7 with moosefs version 3.0.100 installed.  fuse and fuse-libs is already installed as well.

Please advise how can I solve this problem.

Thanks!

**Comment by oxide94** [comment]
Hi @machiasiaweb,

Please add the following parameter: `mfsdelayedinit`, so whole entry would look like:

```
mfsmaster.mydomain.com: /mnt/mfs moosefs defaults,mfsdelayedinit 0 0
```

Please find a description of this parameter below (from `man mfsmount`):

```
-o mfsdelayedinit
connection with master is done in background - with this option mount can be ran
without network (good for being run from fstab / init scripts etc.)
```

Please let me know did it help.

Thanks,
Peter / MooseFS Team

**Comment by machiasiaweb** [comment]
Hello,

The problem now is resolved by your suggestion.  Thanks for your information.  

Thanks!

**Comment by xandrus** [comment]
Hi,
I would like add that there is more "systemd" way to mount resources:

Solution is simple. Let assume that we have:
- MooseFS master host: mfsmaster.local
- We will user moosefs root folder: /
- We will mount moosefs in location: /mnt/mfs

Now we have to create mnt-mfs.mount unit file in /lib/systemd/system location.
_We have to remember that unit name should consists of mount point folders :)_

And /lib/systemd/system/mnt-mfs.mount file should look like this:
```
[Unit]
Description=MooseFS FUSE mount
ConditionPathExists=/mnt/mfs
After=network-online.target

[Mount]
What=mfsmaster.local:/
Where=/mnt/mfs
Type=moosefs

[Install]
WantedBy=multi-user.target
```
Now you can start mount in systemd way:
```
systemctl start mnt-mfs.mount
```
Enable unit, to be executed during boot process:
```
systemctl enable mnt-mfs.mount
```
Also you will be able to read logs with journalctl:
```
journalctl -u mnt-mfs.mount
```

Best regards

**Comment by machiasiaweb** [comment]
This also is another good choice.  Thanks!
