### ISSUE TITLE
how to interpret this error: OVERLOADED in resources tab1

### ISSUE THREAD

**Issue by scotthuang1989** [moosefs/moosefs#128]
here is the error from cgi interface:

![image](https://user-images.githubusercontent.com/5325686/42309144-5e1be850-806a-11e8-8f7e-c47b26069d5e.png)

**Comment by machiasiaweb** [comment]
I also have such issue when running fio write simulation.

![storage_classes_overloaded](https://user-images.githubusercontent.com/17189318/42370408-41edb5ac-813f-11e8-88b6-453d163648f7.jpg)

**Comment by scotthuang1989** [comment]
any document  is appreciated. 

I am not sure if it is correlated, my moosefs is having all kinds of problem recently: can't save  file, can't create directory, flush is not successfully, etc....

**Comment by borkd** [comment]
https://github.com/moosefs/moosefs/search?q=overloaded&unscoped_q=overloaded
