### ISSUE TITLE
FIO error - fio: native_fallocate call failed: Operation not supported

### ISSUE THREAD

**Issue by machiasiaweb** [moosefs/moosefs#129]
Hello,

I found there is error when running fio test which following error.  It only happening when first time file creation. However, it did not happen when test file created at local disk.

%%%
> fio fiops_seqreadtest.conf
iotesttest: (g=0): rw=read, bs=(R) 1024KiB-1024KiB, (W) 1024KiB-1024KiB, (T) 1024KiB-1024KiB, ioengine=libaio, iodepth=32
...
fio-3.1
Starting 4 processes
iotesttest: Laying out IO file (1 file / 65536MiB)
fio: native_fallocate call failed: Operation not supported
iotesttest: Laying out IO file (1 file / 65536MiB)
fio: native_fallocate call failed: Operation not supported
iotesttest: Laying out IO file (1 file / 65536MiB)
fio: native_fallocate call failed: Operation not supported
iotesttest: Laying out IO file (1 file / 65536MiB)
fio: native_fallocate call failed: Operation not supported
%%%

enclosed is running config for reference.
[fio_seqread_config.txt](https://github.com/moosefs/moosefs/files/2169785/fio_seqread_config.txt)

Please advise why it happen.

Thanks!

**Comment by oxide94** [comment]
Hi,
Such issue does not occur with the latest FIO 3.12.

Most probably older FIO version wants to reserve space on the file system with `fallocate` and `fallocate` is not supported on MooseFS (the question is how it should be supported on distributed file systems like MooseFS? Just return "ok"?).

As long as you have space (and usually you do have enough space available) it is not an issue.

Thanks,
Piotr

**Comment by onlyjob** [comment]
Yes, it should fake allocation and just return "ok".

I've seen very long response times when files are copied to MooseFS/LizardFS when "Preallocate space" option is enabled in Midnight Commander. Preallocation on `ext4` is almost instant.

**Comment by asomers** [comment]
No, it should not fake allocation and return "ok".  posix_fallocate should only return "ok" if it can guarantee that subsequent writes will return ENOSPC.  If it can't make that guarantee, then it should return `EINVAL`.  (Honestly, `EOPNOTSUPP` would make more sense, but that's not what the Open Group specified).

**Comment by onlyjob** [comment]
On MooseFS (or on any distributed storage system) fallocate can guarantee very little, even if actual preallocation succeeds (e.g. consider sudden loss of disk or downtime of a chunkserver, not to mention chunkservers backed by compressed file systems).
Most of the time, preallocation on MooseFS just needlessly waste time. 

Besides, preallocation probably could be handled better, as there is no reason for MooseFS to be slow about making empty chunks.
