### ISSUE TITLE
Network partitioning results in an inconsistent state of the file system for the client

### ISSUE THREAD

**Issue by Network-shooter** [moosefs/moosefs#131]
Version number: v3.0
I deployed a cluster of 3 chunk servers (S1, S2, and S3) , one Master server and one Client node. In a case of network partition that splits (S1 and S2) from (S3 and Client) while all nodes can reach the Master server, the Client will be able to list all files in the system including files stored on S1, S2, but when he tries to access files stored on S1 and S2, he will receive an error. Note that the client may receive this  error even though there is a copy of the same file stored on S3.

This behavior is confusing as the files are exists but I cannot access them.

**Comment by Network-shooter** [comment]
Just a correction. The network partition splits (S1 and S2) from (S3 and Client) while all nodes can reach the Master sever.

**Comment by chogata** [comment]
MooseFS 4 is now available. Please, upgrade and test. If comments are needed, please open a new issue or discussion (whichever is appropriate for the info you want to post).
