### ISSUE TITLE
Network partition causes the client to hang forever

### ISSUE THREAD

**Issue by Network-shooter** [moosefs/moosefs#132]
Version number: v3.0
I deployed a cluster of 3 chunk servers (S1, S2, and S3) , one Master server and one Client node. The "goal" parameter was set to 2. 
Assume a network partition that splits (S1) from (S2, S3 and Client) while all nodes can reach the Master server. Sometimes when the Client tries to write a file, it hangs forever.

**Comment by xandrus** [comment]
Hi,
You can always set some timeout in MooseFS client.

`mfsmount -o mfstimeout=N ...`

N = define maximum timeout in seconds before I/O error is returned.
By default it is set to 0 - which means no timeout

**Comment by oxide94** [comment]
@Network-shooter: Can you please tell us a little bit more about your current setup? Do you have all ports mentioned in documentation open (i.e. 9419-9422)?

How can we reproduce the issue?

Best regards,
Peter / MooseFS Team
