### ISSUE TITLE
force changing builtin goal/sc seems not respect chunkserver label

### ISSUE THREAD

**Issue by tclh123** [moosefs/moosefs#134]
The builtin goal 3 has labels "*, *, *". I force change it to "B, B, B". The wrong labels replication seems not occurred.

**Comment by borkd** [comment]
This issue seems to be related to #146

**Comment by acid-maker** [comment]
Yes. I've just checked the code and I can confirm that such a bug exists. There are conditions that treat classes 1-9 little differently. It should be easy to fix.

**Comment by acid-maker** [comment]
fixed by 8ab9f05098f8abcda75ea83f9552154b50fe3b6c
