### ISSUE TITLE
[feature] Chunk replication should use posix_fadvise

### ISSUE THREAD

**Issue by pflorczyk** [moosefs/moosefs#137]
From what I see chunk replication doesn't currently use posix_fadvise. You could use mix of POSIX_FADV_SEQUENTIAL and POSIX_FADV_DONTNEED and maybe new mode for it in hdd_io_begin(). This will give nice speed boost (bigger read-ahead cache with POSIX_FADV_SEQUENTIAL) and lower memory pressure on chunk servers. The same goes for internal rebalancing.

**Comment by chogata** [comment]
MooseFS 4 has implemented `posix_fadvise` for various reads and writes now - please test the new version. If there are any comments to be made, please, open a new issue or discussion (whichever will be appropriate in this case).
