### ISSUE TITLE
master: connection lost (data)

### ISSUE THREAD

**Issue by shiwen5** [moosefs/moosefs#141]
here, master lost connection many times;this is sometings

@info
#server
    ##master:32 cpu + 64G memory
    ##metalogger
    ##ch01 ,ch02，ch03
#system
    ##centos6.9 2.6.32-754.el6.x86_64
    ##3.0.100
    ##net：10G／s  FIBRE；   driver: bnx2x-1.712.30-0
     
     ch01:
            UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:37582595 errors:0 dropped:0 overruns:0 frame:0
          TX packets:14609209 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:54042318646 (50.3 GiB)  TX bytes:17179323585 (15.9 GiB)
          Interrupt:44 Memory:94000000-947fffff
      ch02:
          RX packets:842805700 errors:0 dropped:0 overruns:0 frame:0
          TX packets:769682748 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1204368004254 (1.0 TiB)  TX bytes:1086938295715 (1012.2 GiB)
          Interrupt:44 Memory:94000000-947fffff
      ch03:
            RX packets:3351470194 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3818212476 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:4446625092114 (4.0 TiB)  TX bytes:5189366770008 (4.7 TiB)
          Interrupt:44 Memory:94000000-947fffff
@master-memory
      
<img width="558" alt="mfs-memory" src="https://user-images.githubusercontent.com/16426409/47011812-6626d580-d175-11e8-9e19-15b1ad3bb0f3.png">

@log
Oct 15 06:49:41 ch01 mfsmount[3141]: master: connection lost (data)
Oct 15 06:49:41 ch01 mfsmount[3141]: registered to master
Oct 15 10:24:07 ch01 mfsmount[3141]: master: connection lost (data)
Oct 15 10:24:07 ch01 mfsmount[3141]: registered to master
Oct 16 09:13:43 ch01 kernel: bnx2x 0000:01:00.1: em2: NIC Link is Down
Oct 16 09:13:50 ch01 mfschunkserver[3076]: masterconn: connection timed out
Oct 16 09:13:52 ch01 mfschunkserver[3076]: connecting ...
Oct 16 09:13:52 ch01 mfsmount[3141]: master: tcp recv error: ETIMEDOUT (Operation timed out) (header)
Oct 16 09:13:53 ch01 mfschunkserver[3076]: connection timed out
Oct 16 09:13:54 ch01 mfsmount[3141]: can't connect to master ("192.168.13.252":"9421")
Oct 16 09:13:56 ch01 mfsmount[3141]: can't connect to master ("192.168.13.252":"9421")
Oct 16 09:13:57 ch01 mfschunkserver[3076]: connecting ...

Oct 15 06:49:33 ch02 kernel: bnx2x 0000:01:00.1: em2: NIC Link is Down
Oct 15 06:49:41 ch02 mfschunkserver[3280]: masterconn: connection timed out
Oct 15 06:49:46 ch02 mfschunkserver[3280]: connecting ...
Oct 15 06:49:47 ch02 mfschunkserver[3280]: connection timed out
Oct 15 06:49:51 ch02 mfschunkserver[3280]: connecting ...
Oct 15 06:50:32 ch02 mfschunkserver[3280]: connection timed out
Oct 15 06:50:36 ch02 mfschunkserver[3280]: connecting ...
Oct 15 06:50:37 ch02 mfschunkserver[3280]: connection timed out
Oct 15 06:50:41 ch02 mfschunkserver[3280]: connecting ...
Oct 15 06:50:42 ch02 mfschunkserver[3280]: connection timed out
Oct 15 06:50:46 ch02 mfschunkserver[3280]: connecting ...

Oct 15 06:49:41 ch03 mfsmount[3202]: master: connection lost (data)
Oct 15 06:49:41 ch03 mfsmount[3202]: registered to master
Oct 15 10:24:07 ch03 mfsmount[3202]: master: connection lost (data)
Oct 15 10:24:07 ch03 mfsmount[3202]: registered to master
Oct 16 05:33:01 ch03 auditd[2921]: Audit daemon rotating log files
Oct 16 09:13:52 ch03 mfsmount[3202]: master: connection lost (data)
Oct 16 09:13:52 ch03 mfsmount[3202]: registered to master
Oct 16 10:10:52 ch03 mfsmount[3202]: master: connection lost (data)
Oct 16 10:10:52 ch03 mfsmount[3202]: registered to master

Oct 15 09:00:01 localhost mfsmaster[15630]: store process has finished - store time: 1.234
Oct 15 09:05:49 localhost mfsmaster[15630]: structure check loop
Oct 15 10:00:01 localhost mfsmaster[15630]: child finished
Oct 15 10:00:01 localhost mfsmaster[15630]: store process has finished - store time: 1.233
Oct 15 10:00:26 localhost mfsmaster[15630]: structure check loop
Oct 15 10:24:07 localhost mfsmaster[15630]: csdb: found cs using ip:port and csid (192.168.13.98:9422,2)
Oct 15 10:24:07 localhost mfsmaster[15630]: chunkserver register begin (packet version: 6) - ip: 192.168.13.98 / port: 9422, usedspace: 43979032772608 (40958.67 GiB), totalspace: 113970582454272 (106143.38 GiB)
Oct 15 10:24:07 localhost mfsmaster[15630]: chunkserver register end (packet version: 6) - ip: 192.168.13.98 / port: 9422
Oct 15 10:24:07 localhost mfsmaster[15630]: connection with client(ip:192.168.13.100) has been closed by peer
Oct 15 10:24:07 localhost mfsmaster[15630]: connection with client(ip:192.168.13.97) has been closed by peer
Oct 15 10:24:07 localhost mfsmaster[15630]: connection with client(ip:192.168.13.99) has been closed by peer
Oct 15 10:55:03 localhost mfsmaster[15630]: structure check loop
Oct 15 11:00:01 localhost mfsmaster[15630]: child finished
Oct 15 11:00:01 localhost mfsmaster[15630]: store process has finished - store time: 1.224
Oct 15 11:33:11 localhost mfsmaster[15630]: DEL_LIMIT temporary increased to: 15 per server
Oct 15 11:49:40 localhost mfsmaster[15630]: structure check loop
Oct 15 12:00:01 localhost mfsmaster[15630]: child finished
Oct 15 12:00:01 localhost mfsmaster[15630]: store process has finished - store time: 1.224
Oct 15 12:44:16 localhost mfsmaster[15630]: structure check loop
Oct 15 12:53:08 localhost mfsmaster[15630]: DEL_LIMIT decreased back to: 10 per server
Oct 15 13:00:01 localhost mfsmaster[15630]: child finished
Oct 15 13:00:01 localhost mfsmaster[15630]: store process has finished - store time: 0.992
Oct 15 13:38:53 localhost mfsmaster[15630]: structure check loop
Oct 15 14:00:01 localhost mfsmaster[15630]: child finished
Oct 15 14:00:01 localhost mfsmaster[15630]: store process has finished - store time: 0.997
Oct 15 14:33:30 localhost mfsmaster[15630]: structure check loop
Oct 15 15:00:00 localhost mfsmaster[15630]: child finished
.............
Oct 16 00:00:01 localhost mfsmaster[15630]: child finished
Oct 16 00:00:01 localhost mfsmaster[15630]: store process has finished - store time: 1.007
Oct 16 00:34:15 localhost mfsmaster[15630]: structure check loop
Oct 16 01:00:00 localhost mfsmaster[15630]: child finished
Oct 16 01:00:00 localhost mfsmaster[15630]: store process has finished - store time: 0.984
Oct 16 01:28:52 localhost mfsmaster[15630]: structure check loop
Oct 16 02:00:01 localhost mfsmaster[15630]: child finished
Oct 16 02:00:01 localhost mfsmaster[15630]: store process has finished - store time: 1.232
Oct 16 02:23:28 localhost mfsmaster[15630]: structure check loop
Oct 16 03:00:01 localhost mfsmaster[15630]: child finished
Oct 16 03:00:01 localhost mfsmaster[15630]: store process has finished - store time: 1.227
Oct 16 03:18:05 localhost mfsmaster[15630]: structure check loop
Oct 16 04:00:01 localhost mfsmaster[15630]: child finished
Oct 16 04:00:01 localhost mfsmaster[15630]: store process has finished - store time: 1.233
Oct 16 04:12:42 localhost mfsmaster[15630]: structure check loop
Oct 16 05:00:01 localhost mfsmaster[15630]: child finished
...............
Oct 16 09:00:01 localhost mfsmaster[15630]: child finished
Oct 16 09:00:01 localhost mfsmaster[15630]: store process has finished - store time: 1.237
Oct 16 09:13:52 localhost mfsmaster[15630]: connection with 192.168.13.97:9422 timed out
Oct 16 09:13:52 localhost mfsmaster[15630]: chunkserver disconnected - ip: 192.168.13.97 / port: 9422, usedspace: 44059896717312 (41033.98 GiB), totalspace: 113970582454272 (106143.38 GiB)
Oct 16 09:13:52 localhost mfsmaster[15630]: connection with client(ip:192.168.13.99) has been closed by peer
Oct 16 09:13:52 localhost mfsmaster[15630]: connection with client(ip:192.168.13.100) has been closed by peer
Oct 16 09:13:53 localhost mfsmaster[15630]: server ip: 192.168.13.97 / port: 9422 has been fully removed from data structures
Oct 16 09:50:24 localhost mfsmaster[15630]: structure check loop
Oct 16 10:00:01 localhost mfsmaster[15630]: child finished
Oct 16 10:00:01 localhost mfsmaster[15630]: store process has finished - store time: 1.276
Oct 16 10:10:51 localhost mfsmaster[15630]: csdb: found cs using ip:port and csid (192.168.13.97:9422,4)
Oct 16 10:10:51 localhost mfsmaster[15630]: chunkserver register begin (packet version: 6) - ip: 192.168.13.97 / port: 9422, usedspace: 44059896717312 (41033.98 GiB), totalspace: 113970582454272 (106143.38 GiB)
Oct 16 10:10:52 localhost mfsmaster[15630]: chunkserver register end (packet version: 6) - ip: 192.168.13.97 / port: 9422
Oct 16 10:10:52 localhost mfsmaster[15630]: connection with client(ip:192.168.13.97) has been closed by peer
Oct 16 10:10:52 localhost mfsmaster[15630]: connection with client(ip:192.168.13.100) has been closed by peer
Oct 16 10:10:52 localhost mfsmaster[15630]: connection with client(ip:192.168.13.99) has been closed by peer

**Comment by xandrus** [comment]
Hi,
First look at your system logs and all is pointing to some phisical network problems.

`Oct 16 09:13:43 ch01 kernel: bnx2x 0000:01:00.1: em2: NIC Link is Down`
`Oct 15 06:49:33 ch02 kernel: bnx2x 0000:01:00.1: em2: NIC Link is Down`

Maybe some switch was restarted or something like that?

**Comment by shiwen5** [comment]
- impossibility；in this switch，i have other clusters and they are
   always ok   !
   - so it's useful things for you to me;


Aleksander Wieliczko <notifications@github.com> 于2018年10月23日周二 下午5:01写道：
