### ISSUE TITLE
Unable to limit space usage in mfshdd.cfg

### ISSUE THREAD

**Issue by suntabu** [moosefs/moosefs#142]
Hi,

I followed the manual to limit the disk usage for my mfschunkserver.

But could not set up right.

No matter positive or negative number both not working.

The error message:

> hdd space manager: can't create lock file '/mfs 200G/.lock': ENOENT (No such file or directory)
> hdd space manager: no hdd space defined in /etc/mfs/mfshdd.cfg file

> hdd space manager: can't create lock file '/mfs-10GiB/.lock': ENOENT (No such file or directory)
> hdd space manager: no hdd space defined in /etc/mfs/mfshdd.cfg file

> hdd space manager: can't create lock file '/mfs -10GiB/.lock': ENOENT (No such file or directory)

How should I set it up?

Thanks

**Comment by marcin-github** [comment]
Firstly, paste mfshdd.cfg without comments.

**Comment by xandrus** [comment]
Hi,
So correct syntax in mfshdd.cfg file should look like this:

`/mnt/hd1 200GiB`
`/mnt/hd2 -10GiB`


After hdd mount point, there should be one space and than size that you want to limit.
By the way, which MooseFS version you use?

**Comment by suntabu** [comment]
Hi,

Thanks for your help.

I'm using v1.6.27 and in this version's manual, I found it supports this feature. 
I followed your suggestion but failed. 

I finally set it up by using 
> HDD_LEAVE_DEFAULT = 10GB
in the mfschunkserver.cfg

I know my mfs version is too old and my system is a huge system for online service, so we are planning to update it recently.

Thanks again for your help.
