### ISSUE TITLE
[feature] more flexibility with storage class label specification

### ISSUE THREAD

**Issue by borkd** [moosefs/moosefs#143]
While it is possible to create a set of labels to be used in create-only storage class, there is no way to tell the system that any preexisting data stored using unlabeled "best-effort" replication goals 1,2,... should never be rebalanced and replicated over to chunkservers bearing "create-only" labels. This introduces unnecessary data migrations, adding extra wear, and accelerate time to data loss.

Possible workarounds / improvements:
- ~enable a way to set/alter site-specific Keep and Archive policies for "legacy" classes 1,2,..~ 
> "man mfsscadmin": -f force the changes on a predefined storage class (see PREDEFINED STORAGE CLASSES section), use with caution
- enable a way to exclude sets of labels from Create, Keep and Archive storage class specification. I.e. `-C 2[A+B+C] -K 3![A+B+C]`
- enable a way to mark a label as "create-only"

**Comment by chogata** [comment]
MooseFS 4 has a lot more options in its Storage Classes, including negation of labels. Please, upgrade and test. If comments are needed, please open a new issue or discussion (whichever is appropriate for the info you want to post).
