### ISSUE TITLE
oddness with mfschunkserver on BSD

### ISSUE THREAD

**Issue by tehbenneh** [moosefs/moosefs#15]
hi guys, setting up a new cluster here; have added current moosefs.conf as below;

> [administrator@test] /usr/home/administrator# cat /etc/pkg/moosefs.conf 
moosefs: { url: http://ppa.moosefs.com/moosefs-3/freebsd/10:x86:64, 
enabled: yes, mirror_type: NONE }

but on install it's giving me a copy from the 2x branch -

> Updating pcbsd-major repository catalogue...
pcbsd-major repository is up-to-date.
All repositories are up-to-date.
Checking integrity... done (0 conflicting)
The following 1 package(s) will be affected (of 0 checked):

>New packages to be INSTALLED:
	moosefs-chunkserver: 2.0.89

...any ideas? am i being a total noob?

**Comment by tehbenneh** [comment]
...as an aside i have edited the url to try different permutations; including swapping moosefs-3 with 'current' and even '3.0.80'... no luck :(

**Comment by oxide94** [comment]
Just to let you know - the discussion moved to MooseFS-Users Mailing List (by the way - I encourage you to subscribe :)) and it is resolved now
https://sourceforge.net/p/moosefs/mailman/message/35236535/

**Comment by tehbenneh** [comment]
@oxide94 apologies for blank email replies on the list, can't say why that was happening. anyway:

changed from TrueOS to genuine FreeBSD 10.3 and reinstalled everything that i needed; of course, it worked flawlessly - i would suggest I was experiencing issues that are specific to TrueOS/PC-BSD pkg updates.

...thanks for another great update guys!

**Comment by oxide94** [comment]
I'm closing the issue as it is resolved :)
