### ISSUE TITLE
[mfsmaster] forcefully ignoring metadata structure errors comes with inherent risks

### ISSUE THREAD

**Issue by Yaen1111** [moosefs/moosefs#151]
I have an old version of mfs of 2.0.66, and got Chunk lost error, this is my step:

1. 1 mater(A) and 1 metalogger(B), 3 chunk server, all ok
2. A lost, B upgrate to master by mfsmaster -i
3. A recovered, do file sync and become master again, B downgrade to metalogger again (but the changelog.mfs file exists), about in Apr 2018.
4. A lost again in Dec 2018, B upgrate to master by mfsmaster start ( no -i, so it thinks it is the master in Apr 2018 ??)
5. many file lost since Arp 2018
6. stop B and restart with mfsmaster -i
7. file tree come back, but can not read data, say 
/usr/local/mfs/bin/mfsfileinfo 2018072300000000000000005409.xlsx 
2018072300000000000000005409.xlsx [0]: Chunk lost
8. the file that exists before Apr 2018 is ok

will this cause permanent data loss ??!!  any good way to recover the data ? (we are trying to update to version 3.0, but it may take a long time as we has hundreds of clients)

the server version info :
Master Server, Chunkservers version : 2.0.66-1

client :
 MFS version 2.0.66-1
 FUSE library version: 2.8.3
 fusermount version: 2.9.3

**Comment by Yaen1111** [comment]
I have confirmed the data loss in the trunk servers, and trying to use data-recovery tool to recover the removed trunk data from server, but there 5-days past data loss and the server is still running, 50% of data being recoverred is good enough.

So be careful of the "old version master" -- if the master is older than the trunk, the newly-added trunk data will be removed permanently !

All the test is done in 2.0.66, new version is not mentioned.

**Comment by xandrus** [comment]
Hi,
Can you tell us what MooseFS version was after the upgrade?
Did you upgrade to 3.0.101?

Why did you use mfsmaster -i option?
You should use mfsmaster -a option.

If I understand you correctly. From our perspective, it is not possible to lost date in case of connecting the latest chunkserver to an older Master server. This kind of upgrade scenario is not recommended but will now cause data loss.

It looks like you forced the master to ignore errors during metadata load.
I mean mfsmaster -i option.

**Comment by Yaen1111** [comment]
sorry for my miss-written in the past post, I DID use mfsmaster -a for recover.

but as you mentioned, I remember that when I use mfsmaster -a, it failed to start due to some error (some what like file is broken), so I forced it to start use mfsmaster -a -i. So maybe this make the mfs master crazy ?

As I confirmed the data loss, I stopped upgrading and begin to restore the file, and still in process, current version is still 2.0.66 .


Now working on:
1. recovery file using low-level file tool, and recover the chunk id from the MFSC header, to the file like chunk_00000000002025FF_00000001.mfs ( and be confirmed that this file is not exist in the chunk server)
2. find the file info through mfsdump, mainly the inode
3. find the file name(with full path) by mfsfilepaths command
4. confirm the file exits in the mfs index, and the chunk is lost in all chunk servers, and mfsfileinfo tells chunk lost
5. copy the recovered file back to chunk servers, and restart chunk and master, the mfsfileinfo can tell chunk exists, but the chunk file is auto deleted after a short while
6. try to re-make file from the chunk mfs and other info (cut the heading 5120 bytes and trunk to file size, rename, etc)  <------- now working on this step
7. copy all recovered file back and overwrite the old-chunk-lost-one

I have little time to read the source code as I lost 50w+ files in 10 minutes (maybe the point I run mfsmaster -a -i), and must be recovered in this day or two.

pleaze help me if there is good way to recover the file, or if there is some mistake in my recovery step, thanks !

**Comment by borkd** [comment]
@xandrus 

`mfsmaster -h` shows:
> -i : ignore some metadata structure errors (attach orphans to root, ignore names without inode, etc.)

`man mfsmaster` is less specific:
> -i     ignore some metadata structure errors

It would help to have the same, most up-to-date and specific info shown in both places.
