### ISSUE TITLE
Dynamic control permissions

### ISSUE THREAD

**Issue by Initarts** [moosefs/moosefs#153]
Now I set the following permissions
cat mfsexports.cfg

10.0.16.91-10.0.16.92                   /       rw,alldirs,admin,maproot=0:0
10.0.6.167-10.0.6.180                   /storage        rw,alldirs,admin,maproot=0:0,password=data
10.0.16.94                              /storage        ro,alldirs,admin,maproot=0:0,password=data

How do I change permissions and restart the service each time.Restarting if the data is large will cause the client to jam for a while

Whether there is online permission to change without restarting the service ?

**Comment by richarson** [comment]
No need to restart, reloading is enough, e.g.:

mfsmaster reload
