### ISSUE TITLE
Why do I have 3 chunks with a goal of 2?

### ISSUE THREAD

**Issue by Sveeeeeen** [moosefs/moosefs#157]
Hello!

I have a big problem right now. All of my storage classes have a goal of 2. But I have alot of chunks with 3 copies and I do not know why. MooseFS filled all of my drives! Why is MooseFS creating 3 copies if the goal is only 2?

![unbenannt](https://user-images.githubusercontent.com/18014962/48985202-72536a80-f105-11e8-840a-b320b1d811fb.PNG)
![server](https://user-images.githubusercontent.com/18014962/48985207-84350d80-f105-11e8-8f64-d0ae5db955a4.PNG)

**Comment by oxide94** [comment]
Hi @Sveeeeeen,
Can you please send us screenshots of "DISKS" and "RESOURCES" tabs from MFS CGI?

Thank you,
Best regards,
Peter / MooseFS Team

**Comment by Sveeeeeen** [comment]
Hi @oxide94 

Here you go.
Too bad disks is not working properly.

![screenshot_20181126-150302 3](https://user-images.githubusercontent.com/18014962/49018890-dec57c80-f18c-11e8-8921-9413c8254c15.png)
![screenshot_20181126-150226 2](https://user-images.githubusercontent.com/18014962/49018891-dec57c80-f18c-11e8-90a0-d7a864317caf.png)
![screenshot_20181126-150002 2](https://user-images.githubusercontent.com/18014962/49018892-df5e1300-f18c-11e8-868e-df77bf402247.png)
![screenshot_20181126-150207 2](https://user-images.githubusercontent.com/18014962/49018894-df5e1300-f18c-11e8-89e9-a0d0d82bbc9c.png)
![screenshot_20181126-150302 2](https://user-images.githubusercontent.com/18014962/49018897-df5e1300-f18c-11e8-8fda-53d41bb678c6.png)

**Comment by oxide94** [comment]
Hi @Sveeeeeen,

Thanks for sending us the screenshots. Actually "Disks" and "Resources" tabs are the most important - could you plz check you have your `moosefs-cgi` and `moosefs-cgiserv` packages in the version at least equal or greater than other MooseFS components? We haven't observed such behaviour on our clusters. Also, as there are timeouts - are you sure the server which runs MFS CGI is able to contact Chunkservers at port 9422?

Could you also please adjust charts range to show a spike of replications?

Thanks,

Best regards,
Peter / MooseFS Team

**Comment by Sveeeeeen** [comment]
Hi @oxide94 ,

Thank you for your fast response.

Here is the DISK tab.
![tempsnip](https://user-images.githubusercontent.com/18014962/49033857-9750e780-f1b0-11e8-91f6-142de304741a.png)

I still have the error with the ressources tab:

Traceback (most recent call last):
  File "/usr/share/mfscgi/mfs.cgi", line 5989, in 
    color = "#%02X0000" % (255-255*msperc)
TypeError: %X format: an integer is required, not float


Replication with a longer range:
![replication](https://user-images.githubusercontent.com/18014962/49034016-07f80400-f1b1-11e8-934d-e1ae4a3325eb.PNG)


> EDIT: Is there any info you find important to let us know? Have anything changed in your environment recently (e.g. new storage class definition, new labels, HDD became broken, ...)?

I replaced one server in August (6x3TB drives) with 2 other servers. 8TB + 6TB.
I think the problem are my 2 NAS with the LABEL A. They have only a  limited bandwidth and they are throttled right now (only 10Mbit). But even when they are throttled. MFS should not create 3 copies..

**Comment by oxide94** [comment]
Hi @Sveeeeeen,
Thanks for the reply.

> I still have the error with the ressources tab
Are you sure `moosefs-cgi` package is in the newest stable version?

What do the following commands:
```
mfscli -v
mfscli -SRS -H master.host.name -P PORT
```
say?

What does logfile on this server (ID: 12)
![screen shot 2018-11-27 at 3 35 19 am](https://user-images.githubusercontent.com/4892057/49054791-b7ef6080-f1f5-11e8-979e-6c5244672d0c.png)

say?

Thanks,
Best regards,
Peter / MooseFS Team

PS: I will be going on a business trip soon (today), so my replies may be delayed.

**Comment by Sveeeeeen** [comment]
Hi @oxide94,

`
mfscli -v
version: 3.0.103
`
`
mfscli -SRS -H mfsmaster
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                           Storage Classes                                                                                                                                            |
+----+---------+------------+----------------+-------------------------+----------------------+--------------------------------------------------------------------+-------------------------------------------------------------+---------------------------------------------------------------------+
|    |         |            |  # of inodes   |   # of standard chunks  | # of archived chunks |                               create                               |                             keep                            |                               archive                               |
| id |   name  | admin only +--------+-------+-------+--------+--------+-------+-------+------+------+------------------+------+-----------------------------------+------------------+------+-----------------------------------+------------------+------+-----------------------------------+-------+
|    |         |            | files  |  dirs | under | exact  |  over  | under | exact | over | mode | can be fulfilled | goal |               labels              | can be fulfilled | goal |               labels              | can be fulfilled | goal |               labels              | delay |
+----+---------+------------+--------+-------+-------+--------+--------+-------+-------+------+------+------------------+------+-----------------------------------+------------------+------+-----------------------------------+------------------+------+-----------------------------------+-------+
|  1 | 1       |     NO     |      0 |     0 |     - |      0 |      - |     - |     - |    - | STD  |       YES        |    1 | *                                 |       YES        |    1 | *                                 |       YES        |    1 | *                                 |     - |
|  2 | 2       |     NO     |      0 |     0 |     - |      0 |      - |     - |     - |    - | STD  |       YES        |    2 | * , *                             |       YES        |    2 | * , *                             |       YES        |    2 | * , *                             |     - |
|  3 | 3       |     NO     |      0 |     0 |     - |      0 |      - |     - |     - |    - | STD  |       YES        |    3 | * , * , *                         |       YES        |    3 | * , * , *                         |       YES        |    3 | * , * , *                         |     - |
|  4 | 4       |     NO     |      0 |     0 |     - |      0 |      - |     - |     - |    - | STD  |       YES        |    4 | * , * , * , *                     |       YES        |    4 | * , * , * , *                     |       YES        |    4 | * , * , * , *                     |     - |
|  5 | 5       |     NO     |      0 |     0 |     - |      0 |      - |     - |     - |    - | STD  |       YES        |    5 | * , * , * , * , *                 |       YES        |    5 | * , * , * , * , *                 |       YES        |    5 | * , * , * , * , *                 |     - |
|  6 | 6       |     NO     |      0 |     0 |     - |      0 |      - |     - |     - |    - | STD  |       YES        |    6 | * , * , * , * , * , *             |       YES        |    6 | * , * , * , * , * , *             |       YES        |    6 | * , * , * , * , * , *             |     - |
|  7 | 7       |     NO     |      0 |     0 |     - |      0 |      - |     - |     - |    - | STD  |       YES        |    7 | * , * , * , * , * , * , *         |       YES        |    7 | * , * , * , * , * , * , *         |       YES        |    7 | * , * , * , * , * , * , *         |     - |
|  8 | 8       |     NO     |      0 |     0 |     - |      0 |      - |     - |     - |    - | STD  |       YES        |    8 | * , * , * , * , * , * , * , *     |       YES        |    8 | * , * , * , * , * , * , * , *     |       YES        |    8 | * , * , * , * , * , * , * , *     |     - |
|  9 | 9       |     NO     |      0 |     0 |     - |      0 |      - |     - |     - |    - | STD  |       YES        |    9 | * , * , * , * , * , * , * , * , * |       YES        |    9 | * , * , * , * , * , * , * , * , * |       YES        |    9 | * , * , * , * , * , * , * , * , * |     - |
| 11 | storage |     NO     | 260386 | 22470 |     - | 352094 | 133396 |     - |     - |    - | STD  |       YES        |    2 | F+K+L , F+K+L                     |       YES        |    2 | K+L , A+K+L                       |       YES        |    2 | * , *                             |     - |
| 12 | ssd     |     NO     | 358555 |   104 |     - | 358657 |      - |     - |     - |    - | STD  |       YES        |    2 | L , L                             |       YES        |    2 | L , K+L                           |       YES        |    2 | * , *                             |     - |
+----+---------+------------+--------+-------+-------+--------+--------+-------+-------+------+------+------------------+------+-----------------------------------+------------------+------+-----------------------------------+------------------+------+-----------------------------------+-------+

+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
`
And there is also a long list with open files...do you need the complete list?


> What does logfile on the server with ID: 12 say? (this one):
This is the one (of two) lowend NAS (ARM 2x800Mhz) with only a 10Mbit connection due to the bandwidth limit.
I build this on another server and the logging is not working. Atleast I do not have anything in my syslog of moosefs. Can I choose a own file for logging?

**Comment by acid-maker** [comment]
Python 3 error in mfs.cli fixed by e21874a47b4db9d838fa69ddc106c1345f9b31be

**Comment by Sveeeeeen** [comment]
Here is the storage class tab with the python3 fix.
Thanks @acid-maker

![unbenannt](https://user-images.githubusercontent.com/18014962/49099866-d9daf880-f272-11e8-8ca8-eb1f14c0073d.PNG)

**Comment by acid-maker** [comment]
Could you send one more thing. "Chunk operations info" table from "Info" tab.

Your class with overgoals ("storage") needs constant replication created chunks to chunkservers with label 'A'. They can be created only on 'K' and 'L' - because servers with label 'A' are less occupied than servers 'K' and 'L' then for every created chunk one copy has to be quickly replicated to one of servers with label 'A'.

Replication works in such way that first new copy is created, and then (usually in next loop - typically hour later) one copy is deleted. In the meantime you have three copies for each new chunk. This is quite normal.

The only thing that looks weird is the number of 'overgoal' chunks. According to your charts you have about 100 replications per minute. If your chunk loop is about hour then number of overgoal chunks should be around 6000 (+/- 50%) - still not 133000. Looks like there are problems with chunk deletions - do you have maybe some unusuall entries in mfsmaster/mfschunkserver syslog that mention problems with chunk deletion?

**Comment by Sveeeeeen** [comment]
Here is the screenshot:
![Uploading Unbenannt.PNG…]()

**Comment by oxide94** [comment]
Oh, indeed this could have been the issue. Please let us know @Sveeeeeen whether changing these limits did the job!

Thanks,
Peter / MooseFS Team

**Comment by oxide94** [comment]
Hi @Sveeeeeen,

That's great, thanks for the update!
Closing the issue then.

Best regards,
Peter / MooseFS Team
