### ISSUE TITLE
How to check which chunkserver is performance bottle neck？

### ISSUE THREAD

**Issue by scotthuang1989** [moosefs/moosefs#161]
## Have you read through available documentation and open Github issues?

Yes

QUESTION for the COMMUNITY

## System information
moosefs version: 3.0.101  GPL version
install from apt source

#### Operating system (distribution) and kernel version.

ubuntu 17.10 
kernel: 4.13.0-46-generic

## Describe the problem you observed.

I found that sometimes my mfs is very slow. I have 5 chunkserser, How do I find which one is the bottle neck?

**Comment by borkd** [comment]
Scott - you did not fill out a good bit of the new issue template, which seems relevant in this case. Pls consider adding needed info, or this issue will be marked as invalid and closed.

**Comment by scotthuang1989** [comment]
@borkd  I updated the moosefs version. I think this is the only relevant information.  my question is ask if there is a tool or log for me to check performance of chunkserver.

**Comment by acid-maker** [comment]
Main indicator that there is something wrong with chunkserver is 'load', so first check in 'mfs.cgi' your 'load' value for all your chunkservers in 'Servers' tab. You can also check history in 'Server Charts' - 'load - max operations in queue'.

Another good indicator is time of I/O performed on your HDD. You can go to 'Disks' tab and check 'read' and 'write' columns in 'max time'. If one of your HDD has problems then you should see times much higher than for others.

**Comment by scotthuang1989** [comment]
thanks. it's very helpful. I found a possible bad chunkserver. I will verify it by doing some experiments..
