### ISSUE TITLE
[feature] use a different shade or color to mark maintenance mode periods in master and server tabs

### ISSUE THREAD

**Issue by borkd** [moosefs/moosefs#162]
## Have you read through available documentation and open Github issues?

Yes

## Is this a BUG report, FEATURE request, or a QUESTION? Who is the indended audience?
FEATURE request

## What and why?

It would be helpful to annotate the data presented via graphs in CGI with markers showing any periods when any of the cluster members was in maintenance mode. Different shade/color or even vertical lines. If nothing else, this would make it much easier to spot and explain performance or behavior issues.

**Comment by chogata** [comment]
MooseFS 4 has this feature in its Master Charts: it has a chart called "number of chunk servers", that is divided between connected, disconnected in maintenance mode and disconnected not in maintenance mode. Please, test the CGI of MooseFS 4, it has a lot more features, including a lot of new charts. If there are any comments to be made, please open a new issue or discussion (whichever will be appropriate for the info you want to post).
