### ISSUE TITLE
Cache Control

### ISSUE THREAD

**Issue by machiasiaweb** [moosefs/moosefs#163]
Hello,

There are some cache control parameters under mfsmount selection. 

-o mfscachemode=CMODE
-o mfswritecachesize=N

I would like to highlight 2 of them for my initial question.

1) Where is the cache created?  Client, Chunk or Master?
2) The cache is created by RAM?
3) How can I check the cache running statistic?
4) Is it only write cache can config.  How about read cache?

Thanks!

**Comment by borkd** [comment]
User's manual, FAQ and man pages cover most of this topic.
