### ISSUE TITLE
Block device setup

### ISSUE THREAD

**Issue by machiasiaweb** [moosefs/moosefs#166]
Hello,

Sorry first I think here is not correct place to put my question.  However, the support (I thru submit form) still did not any reply for long time.

I got a problem when trying setup Block device.  The daemon is able to start 
```
#> mfsbdev start -H moosefsmaster
mfsmaster accepted connection with parameters: read-write,restricted_ip,admin ; root mapped to root:root ; settrashtime limited to (0s:0s)
```

However, it got error as below.
```
# > mfsbdev map -f ./mybdev1.bin -s 10Gi -n mytestvm
```
can't find free NBD device

Could you please advise or assistant pass this question to your support team?

Also, where I can get correct channel to contact your support team?

Thanks!

**Comment by acid-maker** [comment]
Maybe this is silly question but:

Did you load nbd module? (`modprobe nbd`)

If no - then load it, if yes then also check if you have proper nbd devices in your '/dev' directory (`ls -al /dev/nbd*`)

**Comment by machiasiaweb** [comment]
Hello,

Thanks for comment.  Since my CentOS 7 did not have such nbd module, so need need compile the module.  It can manage now.

Further question

I run setup under the fuse mount point / 
`>mfsbdev map -f ./mybdev1.bin -s 2Gi -n mytestvm`

However, it looks not created under fuse mount point 

Where is the mybdev1.bin to be located?   As I want to apply to Sclass coming on.

`> mfsbdev list file: ./mybdev1.bin ; device: /dev/nbd0 ; link: mytestvm ; size: 2147483648 (2.000GiB)`

Thanks!

**Comment by acid-maker** [comment]
You should see all files created by mfsbdev in your fuse mount point as normal files.
We will check it.

**Comment by machiasiaweb** [comment]
Hello,

I done a test again.  Please find following my steps:

The moosefs fuse mount point is located at 
`># pwd`
`/mnt/mfsmaster2`

and run the command at /mnt/mfsmaster2

If I create the new Block Device with full path.  Then it will got error like following
`># mfsbdev map -f /mnt/mfsmaster2/mybdev1.bin -s 2Gi -n mytestvm`
`error opening MFS file /mnt/mfsmaster2/mybdev1.bin: No such file or directory`

But when I using following command.  It is succesful create
`># mfsbdev map -f ./mybdev1.bin -s 2Gi -n mytestvm
started block device: (/dev/mfs/mytestvm->/dev/nbd0 : MFS:/./mybdev1.bin : 2.000GiB)`

There is no file mybdev1.bin created under /mnt/mfsmaster2/
so it caused why I have question where does mybdev1.bin created?

Q1. Where is mybdev1.bin located?

Q2. Is it allow to apply storage class? If yes, then how to do it?

Thanks!

**Comment by machiasiaweb** [comment]
Hello,

It is able to see the file with 0 byte.  Filesize will same as creation parameters after done Parted/fdisk.  

Thanks for comment.

**Comment by vkhatuwala** [comment]
Hello,
```
# uname -r
3.10.0-957.1.3.el7.x86_64
# cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)
```
I have already installed the rpm "nbd-3.14-2.el7.x86_64".

Is there block device support available under centos 7? Im unable to find the nbd module.
```
# modprobe nbd
modprobe: FATAL: Module nbd not found.

# mfsbdev start
mfsmaster accepted connection with parameters: read-write,restricted_ip,admin ; root mapped to root:root

# mfsbdev list

# mfsbdev map -f devices/testblock1.bin -s 5Ti -n testblock1
can't find free NBD device
```
Please advise what i can do.

Thanks.

**Comment by richarson** [comment]
I had to install a newer kernel from elrepo.org (http://elrepo.org/tiki/tiki-index.php) to make the nbd module work on centos.
