### ISSUE TITLE
moosefs mfsmount  issue

### ISSUE THREAD

**Issue by zhs077** [moosefs/moosefs#17]
moosefs version2.0.71-1 , many  mfschunk  client CPU usage 170% and different mfschunk client Access to the same file the result are different.

The solution:
 umount -l /mnt/mfs
/usr/local/mfs/bin/mfsmount /mnt/mfs -H XXX.XXX.XXX.XX

Why is this case?thank you

**Comment by oxide94** [comment]
Hi @zhs077,

MooseFS v. 2.0.71 is a really old and unsupported version (it was released over a year ago!). Please upgrade your instance to stable MooseFS 2.0.89 or 3.0.81. The way of the upgrade is described in Chapter 2 ("MooseFS upgrade to newer version") of MooseFS Upgrade Guide (you can obtain it from https://moosefs.com/documentation/moosefs-3-0.html).

There are 2 very important things do to when we consider upgrading MooseFS:

1. Do a backup of your `/var/lib/mfs` directory after Master stop
2. The order of the upgrade (1. Master Server, CGI, CLI, 2. Metaloggers, 3. Chunkservers, 4. Clients - it is described in a document I mentioned)

You can also find more information about changes between versions here: https://moosefs.com/documentation/changes-in-moosefs-2-0.html

Please let me know after the upgrade if it helped.

Peter

**Comment by zhs077** [comment]
Hi @oxide94 
OK,thank you
