### ISSUE TITLE
moosefs metadata document

### ISSUE THREAD

**Issue by ktlcove** [moosefs/moosefs#172]
I want know the format of metadata.mfs.back, but I can't find the document.
Origin requirement is dump all inode and size info of all directory, and I only think of this.

**Comment by gangshushu** [comment]
@ktlcove 在源码mfsmaster/metadata.c中有，可以参考 `meta_load`和`meta_store`这两个函数。这个issue可以关闭了。

**Comment by ktlcove** [comment]
Thanks @gangshushu  @oxide94 

mfsmetadump is a good solution, but for write my script I have to read the source code finally, it has more useful information. And now the script works well. Thanks all again.
