### ISSUE TITLE
Replacing mfsmaster

### ISSUE THREAD

**Issue by rforberger** [moosefs/moosefs#176]
Hi,

I needed to replace my mfsmaster because the old server had a hard disk failure.

Now when I want to connect the mfschunkserver to the new mfsmaster, I get the following error message:

 MATOCS_MASTER_ACK - wrong meta data id (files .metaid:5846B6A37B2D4CAD ; received from master:5C44D5D587EC0FC9). Can't connect to master

Looks like the metadata of the chunks only want to connect to the old master server with the old ID.
The ID of the new master changed though (because I set it up from scratch).

I already tried to delete the .metaid in the chunkserver hdd path and also deleted the /var/mfs/chunkserverid.mfs. 

Then the chunkserver will connect to the new master, but when I mount the path from the mfsmaster, I have an empty directory and all my data seems lost.

Also the rescan of the chunks takes zero seconds, which is weird. 

How can I make the chunkserver connect to the master with the old .metaid?

Thanks for your reply.

**Comment by oxide94** [comment]
Hi @rforberger,

> because I set it up from scratch

When you set up your Master Server from scratch, you **have to** copy `metadata.mfs` file from your old Master Server! This file contains all your metadata (i.e. files' names, paths, ownership, permissions, info about what chunks belong to what file and many more). Without metadata your data stored in chunks may be useless!

If you set up a new machine, you need to copy whole `/var/lib/mfs` from old one to new one or **at least  `metadata.mfs` file. If you do not have this file, but e.g. you have `metadata.mfs.back`, copy this one (or the most recent `*.back` file you have) + changelogs. If you have broken disk on your old machine and you cannot recover `/var/lib/mfs`, use `/var/lib/mfs` from Metalogger.

> I already tried to delete the `.metaid` in the chunkserver hdd path and also deleted the `/var/mfs/chunkserverid.mfs`.

So you have deleted our **protection** against connecting Chunkserver(s) to wrong Master Server or to **EMPTY** Master Server. This is not good. These files' aim was to indicate that something is not right, and it doesn't mean you should delete them.

I strongly recommend to **stop your empty Master Server as soon as possible**. Please take screenshots of MFS CGI interface (especially INFO tab) just before doing this and post them here, we will try to help.

If you were able to connect all chunkservers by removing `.metaid` / `chunkserverid.mfs` files to empty Master, it probably was not able to recognize chunks available on these (as **empty** Master is empty and does not contain any information you had... including information about Chunks (I hope still) present on your Chunkservers).

Such Chunks which empty Master thinks does not belong to any files (as empty Master does not also have info about files, this is why you may see empty mountpoint) are locked for a week. After this time they are deleted and you are in trouble, this is why I recommend to stop the empty Master.

Please provide as much necessary info as possible, including screenshots and `ls -la` of `/var/lib/mfs` on your **old** Master Server and Metalogger(s) and we will try to help.

Best,
Peter / MooseFS Team

**Comment by rforberger** [comment]
Hi Peter,

thank you for explaining and your support.

I managed to get the files appear again by copying back the metadata.back* and changelog* files from another metalogger to the master.

Thanks.

Best regards,
Ronny

**Comment by oxide94** [comment]
Hi Ronny,
Thanks for a prompt feedback. I'm glad I could help!

Best regards,
Peter / MooseFS Team
