### ISSUE TITLE
Can mfschunkserver and mfsmount support multiple ethernet ports？

### ISSUE THREAD

**Issue by skyjally** [moosefs/moosefs#18]
Hi，@acid-maker：
       I have used moosefs for several weeks, in mfschunkserver and mfsmount machine, both of them have two ethernet ports. Could I use all ethernet ports to improve moosefs transfer efficiency?
       Regards

**Comment by oszafraniec** [comment]
What you're looking for is: https://en.wikipedia.org/wiki/Link_aggregation
It's done on network level, not application level.

**Comment by oxide94** [comment]
@skyjally: Link aggregation @oszafraniec mentioned is probably the solution you need. I'd also like to pay your attention to a feature which is built in MooseFS 3 - there's a possibility to separate "data network" (I/O network) from "metadata network".

It's available since MooseFS 3.0.74: `(master) added mapping chunkserver IP classes (allow to have separate network for I/O and separate for other activity)`.

I'll do my best to describe it a bit tomorrow.

Peter

**Comment by skyjally** [comment]
Hi, all:
        Thank you for reply. I will try MooseFS 3.0+, separate network is an amazing ideal

**Comment by skyjally** [comment]
Hi, @oxide94, @oszafraniec :
       Thank you for your reply.
	In Moose3.0.74 mfsmaster.cfg:
	# REMAP_BITS = 24
        # REMAP_SOURCE_IP_CLASS = 192.168.1.0
        # REMAP_DESTINATION_IP_CLASS = 10.0.0.0
        REMAP_SOURCE_IP_CLASS for mfschunkserver communicate with master
	REMAP_DESTINATION_IP_CLASS for mfschunkserver communicate with client so separate I/O network. 
	In my environment, there are two mfschunkserver in different machine,
	each of them has two ip:
	chunk1: IP1,IP2,IP3,IP4
	chunk2: IP5,IP6,IP7.IP8
	When mfsmount start, not all of chunk ip can communicate with mfsmount.
	only REMAP_DESTINATION_IP_CLASS  can get network I/O.
        We have tried Link_aggregation, but the result is not good.
        We hope that mfschunkservers can use all the network port for data transmission.
        Could you give some suggestion?
	Looking forward to your reply.													
															Best Regards

**Comment by oxide94** [comment]
Please use MooseFS 3.0.81, 3.0.74 is not recommended version for production environments. This feature is available **since** 3.0.74, so especially is also available in newer versions, including MooseFS 3.0.81.

I'll help you with this on Monday.

Best regards,
Peter / MooseFS Team

**Comment by skyjally** [comment]
Hi @oxide94:
If I use multiple ip when mfschunkserver regist to mfsmater. Dose data transmit through all the ips?
I'm not sure if I use this way,  mfschunkserver or mfsmaster can work normally .
Best regards
