### ISSUE TITLE
manpage-section-mismatch: usr/share/man/man8/mfsbdev.8.gz:1 8 != 1

### ISSUE THREAD

**Issue by onlyjob** [moosefs/moosefs#183]
`mfsbdev` have inconsistent man page section number:

https://github.com/moosefs/moosefs/blob/master/mfsmanpages/mfsbdev.8

Probably this file should be installed as `mfsbdev.1` instead of `mfsbdev.8` (unless it is meant to be used only by _root_)...

**Comment by acid-maker** [comment]
I think that this is rather root only tool.

**Comment by onlyjob** [comment]
Currently it is installed for everybody into `/usr/bin`...

Root-only tool should be installed into `/usr/sbin` and we will have to adjust section number from `1` to `8` in the first line of the man page.
