### ISSUE TITLE
[question] "Heavy load server detected"

### ISSUE THREAD

**Issue by hanzhengjing** [moosefs/moosefs#194]
<!--
can  you  help me to make the error ？：
Feb 12 14:11:59 lf2-aidevops-spark-71-70-1 mfsmaster[39826]: Heavy load server detected (10.71.67.16:9422); load: 217 ; threshold: 150 ; loadavg (without this server): 25.00 ; ratio_threshold: 3.00
Feb 12 14:12:59 lf2-aidevops-spark-71-70-1 mfsmaster[39826]: Heavy load server detected (10.71.67.16:9422); load: 231 ; threshold: 150 ; loadavg (without this server): 22.00 ; ratio_threshold: 3.00

how to solve ?

Mfs version is 3.0.86

**Comment by oxide94** [comment]
Hi @hanzhengjing,
Your question does not have any content. Please let us know what you would like to ask about.

Best,
Piotr

**Comment by hanzhengjing** [comment]
Feb 12 13:29:00 lf2-aidevops-spark-71-70-1 mfsmaster[39826]: Heavy load server detected (10.71.67.16:9422); load: 170 ; threshold: 150 ; loadavg (without this server): 27.00 ; ratio_threshold: 3.00
Feb 12 14:11:56 lf2-aidevops-spark-71-70-1 mfsmaster[39826]: Heavy load server detected (10.71.67.16:9422); load: 188 ; threshold: 150 ; loadavg (without this server): 25.00 ; ratio_threshold: 3.00
Feb 12 14:11:59 lf2-aidevops-spark-71-70-1 mfsmaster[39826]: Heavy load server detected (10.71.67.16:9422); load: 217 ; threshold: 150 ; loadavg (without this server): 25.00 ; ratio_threshold: 3.00
Feb 12 14:12:59 lf2-aidevops-spark-71-70-1 mfsmaster[39826]: Heavy load server detected (10.71.67.16:9422); load: 231 ; threshold: 150 ; loadavg (without this server): 22.00 ; ratio_threshold: 3.00

**Comment by hanzhengjing** [comment]
load File fail by mfs，MFS log：
Feb 12 13:29:00 lf2-aidevops-spark-71-70-1 mfsmaster[39826]: Heavy load server detected (10.71.67.16:9422); load: 170 ; threshold: 150 ; loadavg (without this server): 27.00 ; ratio_threshold: 3.00
Feb 12 14:11:56 lf2-aidevops-spark-71-70-1 mfsmaster[39826]: Heavy load server detected (10.71.67.16:9422); load: 188 ; threshold: 150 ; loadavg (without this server): 25.00 ; ratio_threshold: 3.00
Feb 12 14:11:59 lf2-aidevops-spark-71-70-1 mfsmaster[39826]: Heavy load server detected (10.71.67.16:9422); load: 217 ; threshold: 150 ; loadavg (without this server): 25.00 ; ratio_threshold: 3.00
Feb 12 14:12:59 lf2-aidevops-spark-71-70-1 mfsmaster[39826]: Heavy load server detected (10.71.67.16:9422); load: 231 ; threshold: 150 ; loadavg (without this server): 22.00 ; ratio_threshold: 3.00

how to  solve ？
