### ISSUE TITLE
CGI: adding time stamp to a page? [feature]

### ISSUE THREAD

**Issue by onlyjob** [moosefs/moosefs#197]
Could it be useful to add a timestamp to CGI pages?

Similar to this: https://github.com/lizardfs/lizardfs/pull/687

**Comment by onlyjob** [comment]
Perfect, thanks. Though IMHO it would be better to use ISO date notation: `YYYY-MM-DD HH:MM:SS TZ`.

**Comment by onlyjob** [comment]
Any chance to make a change to the date format please? Thanks.

**Comment by chogata** [comment]
Yes, adding that for the next release.

**Comment by onlyjob** [comment]
Thank you.

**Comment by onlyjob** [comment]
Time stamp looks perfect, thanks. :)
