### ISSUE TITLE
CGI: equalize charts on Y scale [feature]

### ISSUE THREAD

**Issue by onlyjob** [moosefs/moosefs#199]
Server Charts are not equalised on Y-axis and that makes it difficult to compare charts.

If charts were equalised it would be easier to find slowest (or most active) server by looking on charts.

It would be nice to be able to pin all graphs to certain scale -- user-defined or auto-detected maximum.

**Comment by borkd** [comment]
I see enormous value in being able to quickly spot systems that "fall behind", especially when done in a quantitative way, paving the way for automation. Picking a common Y-axis for graphs is not the best approach in my opinion though. Why?

- I/O and network capabilities of chunkservers can and usually do vary greatly in both in DIY/homelab setups and in larger deployments. In real world it is quite likely one will find a mix or hardware, networks and backend storage technologies (hardware AND filesystems) all playing their role in a single MooseFS cluster. RPi may be fine for throwaway experiments with storage class A, beefier consumer-grade machine may be appropriate for class B, and server grade system for irreplaceable data in class C. There is nothing wrong with having them all participate in the same cluster, but having all the plots scaled to the highest-performers would make absolutely no sense.
- The only benefactors of a common Y-axis would be admins running very simple, homogenous clusters, which do not span more than a single switch or stack. Even then, when their workloads no longer keep the cluster in a steady state a lot of info would be hidden from view.
- Even for trivial installations, it would still be a hack requiring the admin to scroll around and eyeball all graphs to look for odd patterns. Waste of time.

I wanted to propose a different feature, but will piggyback here and ask for feedback from the community and developers:

Step 1 - Let's bug the deveopers for an option to spit out all cluster stats as JSON, which could then be fed to a more elaborate setup, without having to reinvent the wheel just to make things prettier. If you wonder why that would be useful, look no further than https://github.com/lizardfs/lizardfs/issues/788.

Step 2 - Existing tab is not perfect but can be usefull for eyeball check, and scales to the actual performance numbers for each and every chunkserver. Let's keep it as-is, but enable users to switch to log-scale (locking the Y-axis range would actually make sense there, and would help eyeballing performance during bursty workloads on whatever junkyard of chunkservers you operate).

**Comment by oxide94** [comment]
Thanks for your input @borkd.

> Let's bug the deveopers for an option to spit out all cluster stats as JSON

It's on our roadmap to add JSON output of everything CGI / CLI can return and we are going to add support for it also for other tools (which is being already done for new tools like `mfsmetadirinfo` – see 6af88b6, there is JSON and CSV available apart from classic output).

**Comment by onlyjob** [comment]
Being able to switch to log-scale might be useful.

However I would defend the original proposal to allow equalising charts (not necessarily by default but perhaps as an option such as clickable button).

Even when chunkservers are significantly vary in performance it is useful to spot the slowest one to identify bottleneck. Currently you can not _see_ if one chunkserver is faster or slower than another one because their charts could be differently scaled yet look very similar.

**Comment by borkd** [comment]
Unless your hardware is really slow to begin with, abnormal bursts of activity consistently render CGI plots useless for quick visual feedback of the cluster internals.

My cluster is in constant use during the period plotted below, but you would have a hard time answering what the baseline or normal fluctuations in activity look like based on the plots. In addition "bytes read/written" is often detached from reality, giving the operator an extra warm and fuzzy feeling..

![Screen Shot 2019-10-23 at 1 41 02 PM](https://user-images.githubusercontent.com/12971584/67419757-48b3f500-f59b-11e9-9fe7-dc85d831c618.png)

![Screen Shot 2019-10-23 at 1 49 06 PM](https://user-images.githubusercontent.com/12971584/67420608-f673d380-f59c-11e9-81c5-90883190e830.png)

![Screen Shot 2019-10-23 at 1 51 00 PM](https://user-images.githubusercontent.com/12971584/67420617-fc69b480-f59c-11e9-9974-ba886bb98c99.png)

**Comment by onlyjob** [comment]
Yes, @borkd I have the same issues. Also spikes can be due to bugs like #273. 

The problem with vertically unaligned charts is that similar hardware don't look similar and different hardware don't look different...

**Comment by onlyjob** [comment]
The flaw in the current charts design is obvious on "cpu usage" graph where none of the graphs have 100% at the highest point. Because of different scale of each graph, a graph of a server with 1.5% CPU usage can look higher than a graph of a server with 15% CPU usage.

Although individual graphs are somewhat useful, unaligned graphs are practically worthless for comparison...

**Comment by chogata** [comment]
MooseFS 4 CGI & CLI have many new features, including JSON output and Y-scale equalisation (switch to turn it on and off). Please, test version 4. If there are any comments you'd like to make, open a new issue or discussion (whichever will be appropriate in this case).
