### ISSUE TITLE
moosefs-cgi should use relative paths

### ISSUE THREAD

**Issue by njaard** [moosefs/moosefs#200]
Moosefs-cgi should use img tags to `chart.cgi/...` instead of `/chart.cgi/...`.

I have my moosefs monitoring up on `http://server/admin/mfs` because it is onerous to create a new subdomain for moosefs-cgi. With the absolute path, it tries to access `http://server/chart.cgi`, and that's not in the `/admin/mfs/` path.

**Comment by oxide94** [comment]
Hello @njaard,
Do you confirm commit d42404b fixes the issue?
Piotr

**Comment by onlyjob** [comment]
I've tried that commit and I can say that it doesn't break anything...

**Comment by njaard** [comment]
I manually applied this change to my install mfs.cgi and it works fine and corrects the issue.
