### ISSUE TITLE
if I install 2 disk on same server and I set copy of file to 2. is it possible that moosefs will store both copy on same server?

### ISSUE THREAD

**Issue by scotthuang1989** [moosefs/moosefs#202]
It's a question, not a issue., I search on stackoverflow, question related to moosefs is very inactive, so I just post it here.

I have 2 disks on same server, If add these 2 disk into moosefs file system and I configure moosefs that every file have 2 copies,

 **is it possible that both 2 copies of same file will be stored on this server?**

if this is the case, when this server is unavailable, there will be some missing files.

**Comment by zcalusic** [comment]
Of course not, @scotthuang1989 

MooseFS will take care to replicate chunk copies to different servers. Two disks in the same servers are not considered when replicating chunks.

**Comment by marcin-github** [comment]
If I would breake it, because I'd like to build one node personal, home storage server. What should I change in source to achieve it? :)

**Comment by acid-maker** [comment]
By default limit is 'one copy per one chunkserver', but it means 'one copy per one chunkserver process', so the solution is to run multiple chunkserver processes on one machine (on different ports) - for example one cs per hdd.

**Comment by scotthuang1989** [comment]
@zcalusic  thanks. It's very helpful.
