### ISSUE TITLE
V4: is it real?

### ISSUE THREAD

**Issue by guestisp** [moosefs/moosefs#205]
So, where is the new fully-opensource most awaited v4 ?

Is it real or just a joke to create hype and rumors about MooseFS?

**Comment by onlyjob** [comment]
Weren't you the one spreading those rumours?

**Comment by guestisp** [comment]
Sure, but there isn't any new news about this

Last thing i know Is that v4 is in private beta, i did some test with it, one year ago, then no more news

Just asking for an official and public response, let's see what they say

**Comment by marcomilano** [comment]
> So, where is the new fully-opensource most awaited v4 ?
> 
> Is it real or just a joke to create hype and rumors about MooseFS?

Very real.

**Comment by guestisp** [comment]
Very is it?
I'm talking about the open source, not the compiled one, i have the compiled version from last year but we are all waiting for the public open source release, as promised

**Comment by marcomilano** [comment]
> where is it?
> I'm talking about the open source, not the compiled one, i have the compiled version from last year but we are all waiting for the public open source release, as promised

I think, the decision on the licensing is still not finalized. However, v4 exists, and it is very very nice,
so it is not vaporware.

**Comment by marcomilano** [comment]
> Is it real or just a joke to create hype and rumors about MooseFS?

Other projects may have "hype and rumors", MooseFS doesn't do hype or rumors.
It is very, "hypeless",  :-)

**Comment by dragon2611** [comment]
@marcomilano any news on this one?

Will there be an opensource release of V4?

**Comment by guestisp** [comment]
so?

**Comment by chogata** [comment]
MooseFS 4 is real and has been released :)
