### ISSUE TITLE
is there a way to compile chunkserver for macosx?

### ISSUE THREAD

**Issue by eleaner** [moosefs/moosefs#211]
I have an older MacPro which means I have plenty of HDD space.
So in theory, if a few chunkservers running locally I should have a speed boost.

I tried to run chunkserver in the docker 
The write speed reported by moose is about 40MB
The write speed reported by macos is about 100MB so I assume it tries to do a lot of caching including memory.
Aafter a while it crashes the docker due to lack of virtual memory.

I have no idea how to fix it in docker so maybe a natively compiled chunkserver would work

**Comment by oxide94** [comment]
Hi @eleaner,
Have you tried using [this](https://github.com/moosefs/moosefs/blob/master/macosx/makepkg.sh) or [this](https://github.com/moosefs/moosefs/blob/master/macosx_build.sh) script?
First one should build MooseFS and give you `*.pkg` file, second one just builds.

Best,
Piotr

**Comment by eleaner** [comment]
Thank you.
Tried but probably missing some basics

```
(...)
config.status: executing depfiles commands
config.status: executing libtool commands
 cd . && /bin/sh /Volumes/Data/Users/kisiel/git/moosefs/missing automake-1.15 --foreign
/Volumes/Data/Users/kisiel/git/moosefs/missing: line 81: automake-1.15: command not found
WARNING: 'automake-1.15' is missing on your system.
         You should only need it if you modified 'Makefile.am' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'automake' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make: *** [Makefile.in] Error 1
```

but 

```
brew install automake
Warning: automake 1.16.1_1 is already installed and up-to-date
To reinstall 1.16.1_1, run `brew reinstall automake`
```

**Comment by nickb937** [comment]
Run this to re-generate the automake/autoconf files for your system so that they are 1.16 compatible.

`
aclocal
automake
autoconf
`

**Comment by eleaner** [comment]
Thank you @nickb937 but still no luck
```
aclocal automake autoconf
aclocal: error: non-option arguments are not accepted: 'automake'.
aclocal: Try '/usr/local/bin/aclocal --help' for more information.
```

**Comment by nickb937** [comment]
Looks like you missed out the `&&` between the commands.  Try each command separately:

`$ aclocal`
`$ automake`
`$ autoconf`

**Comment by eleaner** [comment]
oh sorry. the && disappeared in the email I received and I did simple copy/paste from there

now I was able to compile!!!
thank you
