### ISSUE TITLE
storage classes with mimimum goal - question

### ISSUE THREAD

**Issue by eleaner** [moosefs/moosefs#213]
I am just digesting the topic of storage classes and I am thinking about such scenario

a goal of 4 but minimum 2
two copies mandatory - minimum goal 2
and two copies optional
say 2A and optionally B and C

it would be useful in a situation when access to moosefs is required with maximum speed on chunks (B or C), but the content must be backed up for security (2A)
It would make it possible for B and C to be workstations with sizeable local drives.
If I am working on B, the write speeds of the first copy are pretty much HDD speeds.
The moose takes care of securing the data in the background.
In the meantime workstation, C  goes online. First accesses are from the network, but it builds up a local copy of chunks to increase speeds.
After a while, I have 2A, B, C situation but if B goes offline, it's all fine. I am not expecting moose to maintain a goal of 4 even if B and C are offline. 

Is this possible? Planned?

**Comment by marcomilano** [comment]
Can you explain little more clearly? I am having a hard-time understanding your setup.

**Comment by eleaner** [comment]
oops
I tried hard :)


I try to go to the baseline
Let's say I have storage that is on 24h.
I intend to have at least two copies on that

but then I have power-workstations with a significant amount of storage on their own.

My idea is to connect their storage to an overall storage pool.
if chunks are on local drive, access to the replicated mfs data is on almost hdd speed.
I would like to make use of that.
So instead of keeping data on local hdd and syncing with mfs
I would use local hdd as part of mfs.

Say I use goal of 3 
I can make it use one chunk on local hdd of my workstation and two somewhere else.
but as soon as my workstation goes down moose will try to ensure the goal of 3.
I would like to say - my minimum goal is 2 (not 3) but allow the third set of chunks to reside on my workstation

does this make sense?

**Comment by marcomilano** [comment]
OK, now I think I understand your question. I could be wrong but as far as I know, it is not possible to setup MooseFS the way you have described. Also, you said "access to the replicated mfs data will be almost hdd speed", this statement is wrong, if it is replicated, it will be slower.
What you are describing seems to me a whole different kind of replication, what I will call "lazy replication". I am not part of the official MooseFS team, so I could be wrong, but I don't think what you are describing is possible with the current MooseFS

**Comment by eleaner** [comment]
I created a feature request #218
