### ISSUE TITLE
after hard reset chunkservers cannot connect to master

### ISSUE THREAD

**Issue by eleaner** [moosefs/moosefs#214]
after a hard reset of the master, I am getting this kind of message.

`MATOCS_MASTER_ACK - wrong meta data id (file chunkserverid.mfs:5C72EC6C20591380 ; received from master:5C75DD2A8444D444). Can't connect to master`
and my chunkservers are dead.
I was able to get some of them running by simply removing .metaid
but some are persistent

version: 3.0.103-1

chunkservers failing on macos 10.13.6
master on ubuntu 16.04.5 LTS, kernel 4.4.0-142

**Comment by oxide94** [comment]
Hi @eleaner,
This is a protection against connecting Chunkservers to wrong Master and vice versa.

In your case (only!), if you are 100% sure you wanted to reset the Master with empty metadata and connect Chunkservers which were used with other Master / metadata earlier, you should do the following:

1. Stop a Chunkserver
2. Remove `/var/lib/mfs/chunkserverid.mfs` file
3. Remove `.metaid` file from all the HDDs which are listed in `/etc/mfs/mfshdd.cfg` on this Chunkserver
4. Start the Chunkserver

It should properly connect then.

Best,
Piotr

**Comment by eleaner** [comment]
hi @oxide94 
what do you mean by "reset the Master with empty metadata"?
I only want my chunkservers connected to my master. That's the only master I have.
I don't intend to reset anything. I already have some data on this cluster

Marcin

**Comment by eleaner** [comment]
I think I see what you mean.
it sort of look like my master has been reset (judging by the size of metadata) - I don't know why but it's worth investigating later.
I still have some data in metalogger (I stopped it just in case)

I guess now just to figure out how to restore metadata on master.

**Comment by oxide94** [comment]
I actually followed you:
> after a hard reset of the master

what did you mean by that? Like to plug the power cord from the wall? :)

**Comment by eleaner** [comment]
@oxide94 
I killed the process so in a way yes, but that's not my concern now

The master is restored now, but in the fury of trying to fix it, I think I busted my chunkservers by removing those important files. As per your message I probably reset them
is there a way to reindex the data?

**Comment by oxide94** [comment]
> I killed the process so in a way yes

When you do so (or have a powercut), you need to restore the metadata file, i.e. run `mfsmaster -a` (see more info in `man mfsmaster`). It will combine lastly saved `metadata.mfs.back` and `changelog.*.mfs` (changelogs), create a proper metadata file and start master.

Actually if you deleted `chunkserverid.mfs` and/or `.metaid` its not a problem – Chunkserver will create these files when started.

Best,
Piotr

**Comment by eleaner** [comment]
ok, here an update

the MATOCS_MASTER_ACK message is engenious. Unfortunately, I ignored it.
The inconsistency between metadata ID of master and chunkservers was caused by the cleared master server. I will have to look closer into it as I am not entirely sure what happened. I was also moving /var/lib/mfs around so anything is possible.

I tried to force chunks to connect to master by removing files .metaid
Bad Idea because without metadata the master simply decided that the chunks should be deleted. 

Finally, I managed to restore metadata from metalogger, although I am pretty sure that metalogger was not that clever and does not seem to have MATOCS_MASTER_ACK implemented. It happily started accepting metadata from the reset-clean master.
@oxide94 please have a look at it. If it's true that's a recipe to lose also metadata backup

With running master, it was enough to remove .metaid again to force connection.

**Comment by jkiebzak** [comment]
depending on how long metalogger ran, and depending on your configuration,
there should be a couple days of history in /var/lib/mfs/ (on metalogger).
If you make a second copy of this directory to work from, I believe you can
then remove the unwanted changelog* files.

>

**Comment by eleaner** [comment]
@jkiebzak 
yes, metalogger holds a history so it is possible to restore from metadata_ml.mfs.back*
but those files are backed u periodically
more granular changes are stored only in changelog* files

if metalogger automatically accepts connection from master with different ID I am losing all recent changelog* files and can fallback only to the last metadata_ml.mfs.back*

is there a reason MATOCS_MASTER_ACK is not there for metaloggers?

**Comment by jkiebzak** [comment]
I thought changelog* files where rotated on an hourly basis.

That would be interesting to confirm if metalogger connected to a
"new/fresh" master, would metalogger wipe out all existing changelog*
files? If that is the case, I'll want to backup all my changelogs
throughout the day.

>

**Comment by eleaner** [comment]
/var/lib/mfs on zfs mirror and snapshotted often saved my bacon.
