### ISSUE TITLE
how to duplicate "endangered files" as soon as possible

### ISSUE THREAD

**Issue by scotthuang1989** [moosefs/moosefs#216]
one of my chunkserver is down(disk error, can't recover), so I got many "endangered files". How can I configure moosefs to duplicate these files ASAP in case I got another failed chunkserver?

**Comment by jkiebzak** [comment]
make sure the chunkserver that went "down" is not marked "maintenance
mode", and make sure you have enough free space for the replicated chunks.
Moose will do the rest automatically.

>

**Comment by richarson** [comment]
Check also options CHUNKS_WRITE_REP_LIMIT and CHUNKS_READ_REP_LIMIT in mfsmaster.cfg, you might want to temporarily increase them to speed up recovery in exchange for a higher load/slower access.

**Comment by scotthuang1989** [comment]
@richarson  It works, number of  "endergered files" decrease much faster.
