### ISSUE TITLE
number of trash file is inconsistant with MCGI

### ISSUE THREAD

**Issue by scotthuang1989** [moosefs/moosefs#217]
on interface of MCGI, there are over 6 million pending deletion files. but when I mount trash with this command:

> mfsmount -H 192.168.0.33 -o mfsmeta,mfsflattrash /mnt/mfsmeta/

and count the file in this directory. 

> cd /mnt/mfsmeta/trash
> ls -l | wc -l

**the result is 1369570. there are a big mismatch!!!**

![image](https://user-images.githubusercontent.com/5325686/53623599-8fce2e00-3c38-11e9-9612-045edb963807.png)

**Comment by oxide94** [comment]
"Pending deletion" chunks are not chunks of files in trash. Chunks of files which exist in the trash are treated as "Normal" chunks.

**Comment by scotthuang1989** [comment]
if I want force delete all files. what else I should do beside delete all files in meta trash directory?

**Comment by richarson** [comment]
@scotthuang1989 you might want to temporarily increase CHUNKS_SOFT_DEL_LIMIT and CHUNKS_HARD_DEL_LIMIT in your mfsmaster.cfg file (don't forget to reload you mfsmaster process) to speed up the removing of those chunks, but you'll get more load on your chunkservers.

```
# Soft maximum number of chunks to delete on one chunkserver (default is 10)
# CHUNKS_SOFT_DEL_LIMIT = 10

# Hard maximum number of chunks to delete on one chunkserver (default is 25)
# CHUNKS_HARD_DEL_LIMIT = 25
```

We actually have cronjobs to lower those settings (plus CHUNKS_WRITE_REP_LIMIT and CHUNKS_READ_REP_LIMIT) during the day and increase them at night to avoid disrupting operations during peak hours.

**Comment by scotthuang1989** [comment]
@richarson, thanks for the reply. these configuration works, but what I want is free these disk space immediately when I am confident that I will not need these file anymore..

**Comment by oxide94** [comment]
@scotthuang1989
> what I want is free these disk space immediately when I am confident that I will not need these file anymore

You can play with `mfssettrashtime`. Default is one day (86400 seconds). If you decrease trash time for files (you can do it recursively to a certain subtree), files will stay in trash for defined time.

In order to skip the trash completely, simply use `mfssettrashtime 0 file` or `mfssettrashtime -r 0 dir/` (recursively).

You can find more information in `man mfstrashtime`.

Best,
Piotr
