### ISSUE TITLE
mfsmount: run samba server on it

### ISSUE THREAD

**Issue by yinjiawind** [moosefs/moosefs#22]
I have a samba server that it running on the MooseFS(e.g “/mnt/mfs/share” is shareded by samba. “/mnt/mfs” is  mount point )， In the windows, when I create file in the share directory, the samba server have a system call that is flock(fd, 0x20). What's the problem is mfsmount just return without fuse_reply. So the server can not get response.
What should I do to solve this probelm?

**Comment by xandrus** [comment]
Hi,
Can you tell us something more about your setup. I mean kernel version, fuse version, SAMBA version.
MooseFS mount is in 3.0.81 version. Yes?

**Comment by yinjiawind** [comment]
The system is CentOS6.8.The kernel version is in 2.6.32 version.The fuse version is in 2.8.3 verison.The SAMBA version is in 3.6.23.

**Comment by yinjiawind** [comment]
You can reappearance it with the follow code
#include <stdio.h>
#include <sys/file.h>
#include <sys/types.h>

int main()
{
        int fd = open("123", O_RDWR); // in your MFSMount should have this file
        if (fd == -1)
        {
                printf("open file error");
        }
        flock(fd, 0x20);
        return 0;
}
My gcc version is in 4.4.7 version.

**Comment by xandrus** [comment]
Hi,
Thank you for all this information.

First of all flock mechanism needs to be supported by your version of fuse library and kernel.

Basically there are two locking mechanisms: 
"posix_locks" (ioctl,lockf) -  introduced in fuse version 2.6
"bsd_locks" (flock) - introduced in fuse version 2.9

Please consider to upgrade FUSE and kernel to latest stable version.
In my humble opinion is high time to upgrade whole operating system.

**Comment by yinjiawind** [comment]
Thank you for your advise

**Comment by xandrus** [comment]
Thank you.
