### ISSUE TITLE
chunkserver: reload can stop

### ISSUE THREAD

**Issue by onlyjob** [moosefs/moosefs#221]
I've added new path to `mfshdd.cfg` and `systemctl reload moosefs-chunkserver.service` but chunkserver unexpectedly stopped because new path was incorrect:

    hdd space manager: can't create lock file '/var/lib/mfs/3/ext4/.lock': ENOENT (No such file or directory)

However correct behaviour in such situation would be to mark new partition as "DAMAGED" without terminating chunkserver.

Please consider making necessary corrections to avoid chunkserver suicide on reload when invalid path is added to `mfshdd.cfg`.

Thanks.

**Comment by acid-maker** [comment]
Chunkserver doesn't stop in such situation. We can't reproduce this.

Such disks with errors during initialization defined in `mfshdd.cfg` are just ignored.

**Comment by onlyjob** [comment]
I'm not sure what's happened but I can not reproduce the issue any more... Let's close for now. Thanks for investigating.

**Comment by PC-Admin** [comment]
I had this same error and the chunkserver won't start, it has another disk that isn't generating this error.

`hdd space manager: can't create lock file '/mfsbrick.2/16tb-ironwolf/.lock': EACCES (Permission denied)`
