### ISSUE TITLE
[question] what  means load in pointy brackets e.g. <4> 

### ISSUE THREAD

**Issue by eleaner** [moosefs/moosefs#230]
The documentation for version 3.0 explains only () or [] brackets

**Comment by oxide94** [comment]
It means "server in heavy load state" (if you hover it for a few seconds, a tooltip should appear). See here:

https://github.com/moosefs/moosefs/blob/af60d3928fb21460e51687df3b33519d8af9b550/mfsscripts/mfscli.py.in#L4052

Best,
Piotr
