### ISSUE TITLE
mfssetquota  Operation not permitted 

### ISSUE THREAD

**Issue by zgqing** [moosefs/moosefs#24]
I have got the problem when I tried to use the mfssetquota  command to set the directory of the users, it showed that **Operation not permitted** , the shell command like this : 
```
mfssetquota -R 1024  /var/storage/user/19064/
```

**Comment by oxide94** [comment]
Hi @zgqing,

to allow specific mount to change the quota, you have to add ``admin`` flag in ``/etc/mfs/mfsexports.cfg`` to the specific export, which should be allowed to change the quota.

This parameter is described here: https://moosefs.com/manpages/mfsexports-cfg.html

> ``admin``: administrative privileges - currently: allow changing of quota values and storage classes management

In case of any further questions, please don't hesitate to ask!

Best regards,
Peter / MooseFS Team
