### ISSUE TITLE
"NO SPACE" with around 12% space left [question]

### ISSUE THREAD

**Issue by eleaner** [moosefs/moosefs#241]
moosefs 3.0.104
my goal 2 reports NO space
![image](https://user-images.githubusercontent.com/5169203/56063276-c6828280-5d66-11e9-9a29-734fe09cc926.png)

yet there should be plenty of space still left on the chunk servers
![image](https://user-images.githubusercontent.com/5169203/56063377-02b5e300-5d67-11e9-8639-f29ac4d364a6.png)

I use the default settings for the storage on all drives
I believe this should lead to mossefs using
HDD_LEAVE_SPACE_DEFAULT = 256MiB

I was not expecting 2TB 
Any ideas what might be happening?

**Comment by acid-maker** [comment]
Your servers 1-3 in given pictures are in "heavy load state", so only server number 4 can be used for replicating chunks - this is why system reports that goal 2 can't be fullfiled.

The only question is why it reports it as "NO SPACE" instead of "OVERLOADED" - I have to check it.
