### ISSUE TITLE
feature: filesystem access without mfsmount

### ISSUE THREAD

**Issue by njaard** [moosefs/moosefs#243]
It would be nice for a low-level (C or C++) API into moosefs that doesn't go through mfsmount. This is useful because mfsmount has not only the overhead associated with a system call, but then going back to userspace and then back into the kernel. Fuse surely caches a lot, but if I'm doing huge amounts of random accesses, this would be terrible for performance.

It can also help with deployment in HPC cases where all I need to do is ship a single binary.

**Comment by oxide94** [comment]
Have you tried using [`mfsio.c`](https://github.com/moosefs/moosefs/blob/master/mfsclient/mfsio.c)? It is compiled as `libmfsio` library and can be dynamically linked in other C projects. In MooseFS it is currently used by Block Device.

Best regards,
Piotr / MooseFS Team
