### ISSUE TITLE
Where should one disable updateDB feature (Linux only)

### ISSUE THREAD

**Issue by pault28** [moosefs/moosefs#244]
This is more of question more than anything else.

In the best practices section of moosefs support it states:  "Disabled updateDB feature (Linux only)"

I understand how to do this. However it is not clear where it should be done? Master(s), Metaloggers, Chunkservers, or Client?

Clarity on this would be very helpful. I am about to do it for the client machines.

Thanks.

**Comment by zcalusic** [comment]
Hello @pault28,

updatedb is a service separate from MooseFS, used to visit all files on all filesystems, save the list to a database, and then later on you can do quick lookups by filename using `locate` command.

MooseFS being networked, traversing all its files can be quite problematic. So, it's generally a good advice to disable MFS mount traversal. Especially on high latency links.

The exact solution will depend on the make of locate command (there are several) and your specific OS distribution.

Here's what worked for me (cca 2017), for specific GNU findutils version in Debian Linux:
```
[/etc]% cat updatedb.findutils.cron.local 
PRUNEFS="$PRUNEFS fuse.mfs"
```

**Comment by oxide94** [comment]
[It was fixed](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=810902#22) in Debian in Nov 2016 by Tollef Fog Heen, so in the most recent versions of `mlocate` MooseFS (i.e. `fuse.mfs` should automatically be added to `PRUNEFS` list).

> However it is not clear where it should be done? Master(s), Metaloggers, Chunkservers, or Client?
> 
> Clarity on this would be very helpful. I am about to do it for the client machines.

Answering your question: it should be done on each machine where MooseFS cluster is mounted, so on Clients.

**Comment by pault28** [comment]
Thanks @oxide94 and @zcalusic for the quick response.

**Comment by richarson** [comment]
It might also be also useful to exclude the chunkserver's directories (from /etc/mfs/mfshdd.cfg) if not already.

We use /mnt/chunkXX as mountpoints and /etc/updatedb.conf (CentOS location) already excludes /mnt, but might be worth checking the PRUNEPATHS setting.
