### ISSUE TITLE
Incorrect release NEWS

### ISSUE THREAD

**Issue by andrewsali** [moosefs/moosefs#246]
Hi,

It seems the release date is incorrect (2018 instead of 2019?):

https://github.com/moosefs/moosefs/blob/6a9849814d4f4da1abf702c2d50ba86313bf55ea/NEWS#L3

**Comment by oxide94** [comment]
Good catch,
thank you!

Best regards,
Piotr / MooseFS Team

**Comment by acid-maker** [comment]
Did you check it recently? Because I've found it more than week ago and fixed in dd4ef3dbde1c9b47ecbf1d83260e59cd2c82cb56 !!!
