### ISSUE TITLE
STRICT policy is not strictly obeyed; SC boundaries not respected

### ISSUE THREAD

**Issue by onlyjob** [moosefs/moosefs#249]
All my Storage Classes (SC) are in `STRICT` mode to enforce boundaries (see #237) and to avoid this very issue.

Yet one chunkserver defined with exclusive SC and label received 6 chunks despite having no files in the corresponding SC. In CGI, _Servers_ and _Disks_ show 6 chunks placed to unallocated chunkserver (confirmed by checking chunkserver's data directory) whilst _Resources_ tab show `0` (zero) chunks -- clearly a spill from other Storage Class in violation of _STRICT_ policy.

Please investigate.

**Comment by acid-maker** [comment]
STRICT mode only applies to "chunk creation". We are thinking of adding also similar policy to KEEP.

**Comment by onlyjob** [comment]
Please do. Storage classes are _sacred_ and violations of data placement should never happen (and should never be allowed by default).

**Comment by onlyjob** [comment]
This is a serious issue. I have reasons to believe that we have experienced a significant cross-SC spill of _archive_ chunks to chunkservers where they should never be placed (according to _Storage Class_ definition).

#### Please enforce _Storage Class_ compliance for all chunks -- _create_, _keep_ and _archive_.

To stress the importance of this, consider scenario when your precious mission-critical SSD capacity is consumed by spill from _archive_ storage class -- this should never happen under any circumstances.

**Comment by onlyjob** [comment]
Thank you very much for addressing this very important issue in 3.0.112.

I'm yet to provide a feedback on this and so far my cluster is massively "`replicate to correct label (all modes)`", already for over 24 hours. I'll evaluate (and report) data placement here when cluster finish moving data.

What would be very useful to add is some indication of how many chunks are out of place to "CGI/Resources" page.

**Comment by onlyjob** [comment]
Appears to be fixed by 52371d0. Thanks!
