### ISSUE TITLE
ISCSI server on MFSMount

### ISSUE THREAD

**Issue by yinjiawind** [moosefs/moosefs#25]
Hi:
I run a ISCSI server on MFSMount, some problem occured.
In the mount point, I create a block device. The size of block device is 10TB.Then I share this block device by ISCSI server. In the win7 client, I mount this block device as disk,Then I write this disk for a long time(I have a python script that have 10 threads to create files, The file size between in 100MB and 800MB).The time may less than 10 hours(In the ISCSI server you may simulated network packet loss to make this problem occured faster).In the ISCSI server, you will find the client connected for many times.In  mount point that you can open this block device. But seek this block device would block without any reply.
System info:
```
[root@YU-73 mnt]# mfsmount -V
MFS version 3.0.84-1
FUSE library version: 2.8.3
fusermount version: 2.8.3
```
```
[root@YU-73 mnt]# cat /etc/issue
CentOS release 6.8 (Final)
Kernel \r on an \m
```
```
[root@YU-73 mnt]# tgtd -V
1.0.24
```

**Comment by xandrus** [comment]
Hi,
Basically we had small bug in our MooseFS client code. Right now you can download corrected source code (fixed by ef431a585c589ff64d6c70d18b10f037cd3916cb).
Packages will be available this week.

The other question is - which iSCSI software should be used?
We tried couple of them, and SCST was most suitable for MooseFS.

Please consider to update you operating system because linux kernel and fuse library are quite old.

**Comment by yinjiawind** [comment]
Thank you.

**Comment by yinjiawind** [comment]
Sorry, I view the code. I can't understand what bug is fixed by this code. Anywhere the inode would by modify?
And this problem also occured when I read files from this disk for a long time on the client. And I open this file and seek it as follow is also block.
```
[root@YU-73 mfs]# python 
Python 2.6.6 (r266:84292, Aug 18 2016, 15:13:37) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> f = open("iscsi-disk", "r+") # iscsi-disk is block device
>>> f.seek(0)
```
 I use mfsnetdump catch network package. I find seek opration is not send package to master.

**Comment by yinjiawind** [comment]
Sorry, I view the code. I can't understand what bug is fixed by this code. Anywhere the inode would by modify?
And this problem also occured when I read files from this disk for a long time on the client. And I open this file and seek it as follow is also block.
```
[root@YU-73 mfs]# python 
Python 2.6.6 (r266:84292, Aug 18 2016, 15:13:37) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> f = open("iscsi-disk", "r+") # iscsi-disk is block device
>>> f.seek(0)
```
 I use mfsnetdump catch network package. I find seek opration is not send package to master.

**Comment by xandrus** [comment]
Hi,

Problem was connected with our new data structure that we have used in this version.
Please update the MooseFS client and do some tests.

I'm looking forward to hearing from you.

**Comment by yinjiawind** [comment]
OK,
I will update fuse version to 2.9.3! Should I update my kernel version or change iSCSI to SCST?

**Comment by xandrus** [comment]
Hi,

According to iSCSI target software.
With SCST and MooseFS we achieved the best performance and stability. Basically only SCST was able to use block size larger than 4k.

About kernel. In my humble opinion newer and stable kernel is always good option.
Please consider to use relatively new Linux distributions like CentOS 7 or Ubuntu 16 in your cluster.

**Comment by yinjiawind** [comment]
Thank you.

**Comment by yinjiawind** [comment]
Hi @xandrus ,
When I install SCST, I have some problem.
When I install SCST without patching my kernel, The same problem would occured.
In the SCST source code, I can't find "scst_exec_req_fifo-2.6.32.patch" to patch my kernel.(PS. I can find "put_page_callback-2.6.32.patch"). I also try to run the "rebuild-rhel-kernel-rpm", but useless.
I will change My Linux distributions to CentOS 7. Can you give me some suggestion to install SCST on CentOS 7? Can I install SCST without patching kernel?

**Comment by xandrus** [comment]
Please search for something like SCST DKMS.
This solution will allow you to build only modules for kernel not whole kernel.

**Comment by yinjiawind** [comment]
Thank you for much!
