### ISSUE TITLE
chunkserver tunnning for ancient machine [question]

### ISSUE THREAD

**Issue by eleaner** [moosefs/moosefs#254]
Hi

mfs 3.0.104

I am running chunkserver on ancient HP microserver N54L.
Technically these are two chunkservers on one machine running dockerised.
The machine does nothing else (I hope)
The CPU has two cores and my current load on the system is slightly exceeding 2
![image](https://user-images.githubusercontent.com/5169203/57196658-e583c700-6f56-11e9-8c4c-ca28030e1639.png)

the chunkservers are tuned for
MFSCHUNKSERVER_WORKERS_MAX: 15
MFSCHUNKSERVER_WORKERS_MAX_IDLE: 3

yet the web-ui shows heavy load in hundreds
![image](https://user-images.githubusercontent.com/5169203/57196695-2ed41680-6f57-11e9-85b8-9e662e4725aa.png)

I don't suppose that's OK
Any ideas?

**Comment by acid-maker** [comment]
That is ok.

In chunkserver there is task queue (250 elements) and then worker threads. "WORKERS" options only decrease number of threads (which might be a good idea for old machines), but "load" you see in the table is chunkservers load not OS load. Here "load" = "max number of tasks waiting in queue", so values up to 250 are perfectly ok.

**Comment by eleaner** [comment]
thank you
I am trying to run the chunkserver(s) on bare metal and see what happens.

**Comment by onlyjob** [comment]
> Here "load" = "max number of tasks waiting in queue"

Then why not rename Server's "load" column to "queue" in CGI?

**Comment by marcomilano** [comment]
> > Here "load" = "max number of tasks waiting in queue"
> 
> Then why not rename Server's "load" column to "queue" in CGI?

I don't see any need for a rename. "load" is defined the same way at the OS level.
There is no need to freak out just because this is a high number.

**Comment by onlyjob** [comment]
"Queue" expresses better what it is than "load" hence I recommend to rename.
