### ISSUE TITLE
[ASK] moosefs strightforward tutorial

### ISSUE THREAD

**Issue by codenoid** [moosefs/moosefs#257]
hi, i'm new in distributed file system world, i wanna make a replication set + multi data center with moosefs, but i can't find strightforward tutorial for it, something like :

1. what i must do in master-server
2. what i must do in node server
3. where (the config file) and how to config master/node server
4. how other server (as client) can connect to moosefs service
5. how file path be arranged
6. more something like that

my server is ubuntu 16.04, thank you !

**Comment by oszafraniec** [comment]
And what about https://moosefs.com/support/#documentation ???

1 link on this page is about „Instaling moosefs step by step”: https://moosefs.com/Content/Downloads/moosefs-installation.pdf

What else do you expect? Docs and complicated tutorials like Ceph? 🤭😂😂😂

**Comment by codenoid** [comment]
@oszafraniec https://docs.gluster.org/en/latest/Quick-Start-Guide/Quickstart/ actually easy af

**Comment by oxide94** [comment]
Hello @codenoid,

In general you can start with default configuration and follow either "Step by Step Tutorial" mentioned by @oszafraniec or try with [`README.md`: Minimal Setup](https://github.com/moosefs/moosefs/blob/master/README.md#minimal-setup) (README is even more condensed I reckon). You can add `mfsmaster` entry to your DNS in order not to modify `MASTER_HOST` variable in all configs.

 The only thing you need to change (i.e. add actually) in config files is `LABELS = ` string in `/etc/mfs/mfschunkserver.cfg` file on Chunkservers. So if you e.g. want to have DC "A" and DC "B", on Chunkservers which are set up in DC "A" you configure `LABELS = A`, and on those in DC "B" you set `LABELS = B`.

Then, after setting everything up and when you have a working cluster, on mounted MooseFS Mountpoint (e.g. `/mnt/mfs`), issue:

```
mfsscadmin create -K A,B myStorageClassName
```

Then check if it was created properly in "Resources" tab in MFS CGI or by running `mfslistsclass -l` or `mfscli -SRS`, and then apply it to whole `/mnt/mfs` mountpoint:

```
mfssetsclass myStorageClassName /mnt/mfs
```

In order to get more information about every MooseFS' command-line tool, just issue `man toolname`, e.g. `man mfsscadmin` or `man mfssetsclass` – they are quite well documented.

If you want to get more information on Storage Classes management with examples and pictures, refer to "[MooseFS User's Manual](https://moosefs.com/Content/Downloads/moosefs-3-0-users-manual.pdf)", Chapter 4: "Storage Classes", pp. 26-46, especially paragraph 4.4 "Common use scenarios". On page 26 you will find explanation on what are LABELS and what are Storage Classes and pages 27-32 will guide you well, step by step.

If something wouldn't be clear or if you found any obstacles, do not hesitate to ask us here.

PS: I wouldn't say MooseFS is harder to set up. In general it comes down to:
1. Adding `mfsmaster` entry to DNS or to `/etc/hosts` on all machines where you have or will have any of MooseFS' components installed
2. Installing packages
3. Starting services

Thanks,

Best regards,
Piotr / MooseFS Team

**Comment by codenoid** [comment]
i have no idea

systemctl status moosefs-master : 
```
May 08 06:04:23 localhost.localdomain mfsmaster[8816]: chunkserver register end (packet version: 6) - ip: 30.30.30.1 / port: 9422
May 08 06:05:05 localhost.localdomain mfsmaster[8816]: csdb: found cs using ip:port and csid (30.30.30.1:9422,1), but server is still connected
May 08 06:05:05 localhost.localdomain mfsmaster[8816]: can't accept chunkserver (ip: 30.30.30.1 / port: 9422)
May 08 06:05:05 localhost.localdomain mfsmaster[8816]: chunkserver disconnected - ip: 30.30.30.1 / port: 9422, usedspace: 0 (0.00 GiB), totalspace: 0 (0.00 GiB)
May 08 06:05:06 localhost.localdomain mfsmaster[8816]: csdb: found cs using ip:port and csid (30.30.30.1:9422,1), but server is still connected
May 08 06:05:06 localhost.localdomain mfsmaster[8816]: can't accept chunkserver (ip: 30.30.30.1 / port: 9422)
May 08 06:05:06 localhost.localdomain mfsmaster[8816]: chunkserver disconnected - ip: 30.30.30.1 / port: 9422, usedspace: 462848000 (0.43 GiB), totalspace: 160982630400 (149.93 GiB)
May 08 06:05:11 localhost.localdomain mfsmaster[8816]: csdb: found cs using ip:port and csid (30.30.30.1:9422,1), but server is still connected
May 08 06:05:11 localhost.localdomain mfsmaster[8816]: can't accept chunkserver (ip: 30.30.30.1 / port: 9422)
May 08 06:05:11 localhost.localdomain mfsmaster[8816]: chunkserver disconnected - ip: 30.30.30.1 / port: 9422, usedspace: 462848000 (0.43 GiB), totalspace: 160982630400 (149.93 GiB)
```

30.30.30.1 is my gateway, one of chunkserver connected to master, but another one is fail

```
May 08 06:05:37 localhost.localdomain mfschunkserver[3334]: connection was reset by Master
May 08 06:05:37 localhost.localdomain mfschunkserver[3334]: closing connection with master
May 08 06:05:42 localhost.localdomain mfschunkserver[3334]: connecting ...
May 08 06:05:42 localhost.localdomain mfschunkserver[3334]: connected to Master
May 08 06:05:42 localhost.localdomain mfschunkserver[3334]: connection was reset by Master
May 08 06:05:42 localhost.localdomain mfschunkserver[3334]: closing connection with master
May 08 06:05:47 localhost.localdomain mfschunkserver[3334]: connecting ...
May 08 06:05:47 localhost.localdomain mfschunkserver[3334]: connected to Master
May 08 06:05:47 localhost.localdomain mfschunkserver[3334]: connection was reset by Master
May 08 06:05:47 localhost.localdomain mfschunkserver[3334]: closing connection with master
```

**Comment by codenoid** [comment]
i try to connect from my ubuntu client but : 

systemctl status moosefs-master : 

```
May 08 06:08:48 localhost.localdomain mfsmaster[8816]: created new sessionid:6
May 08 06:09:09 localhost.localdomain mfsmaster[8816]: created new sessionid:7
May 08 06:09:09 localhost.localdomain mfsmaster[8816]: main master server module: (ip:30.30.30.11) write error: ECONNRESET (Connection reset by peer)
```
client : 
```
error receiving data from mfsmaster: EAGAIN (Resource temporarily unavailable)
```

**Comment by oxide94** [comment]
Hi @codenoid,
1. If it is your GW and Chunkservers are behind it and you have ports forwarded on it, you may need to change port number for every Chunkserver. You can use e.g. 10221, 10222, 10223, ... Just change `CSSERV_LISTEN_PORT` variable in `/etc/mfs/mfschunkserver.cfg`. Remember to forward ports for every Chunkserver on Gateway. And also remember that in such case your GW may be a bottleneck.
2. Do you have ports 9419-9422 and 9425 open (9425 is for CGI Server / Web interface only, so less important, but 9419-9425 are "must-have")?
3. Also, please make sure you have the same MTU set on all machines.
4. If you tried to set up MooseFS earlier, connected some Chunkservers and then wanted to start over with vanilla metadata and empty, fresh Master Server, Chunkserver will not connect to such "new" Master Server. This is our protection against human error and connecting a Chunkserver to wrong Master Server (as one may have many MooseFS clusters).

If you have a situation I described in number 4 and you are sure you don't have any data on these Chunkservers, for every Chunkserver do as follows:
1. Stop Chunkserver process,
2. Go to `/var/lib/mfs` and remove `chunkserverid.mfs` file. Do not start the Chunkserver process,
3. For every path from `mfshdd.cfg`, remove `/path/from/mfshdd/.metaid` file, so assuming you have `/mnt/mfschunks1`, `/mnt/mfschunks2` and `/mnt/mfschunks3`, do:

```
rm /mnt/mfschunks1/.metaid /mnt/mfschunks2/.metaid /mnt/mfschunks3/.metaid
```

4. Start the Chunkserver process

Let me know if it helped.

Best,
Piotr / MooseFS Team

**Comment by codenoid** [comment]
thank you @oxide94 , another chunkserver successfully connected to master, now the problem is between client and master

in client : 
```
root@crawling-1:/mnt/storage# mount -t moosefs mfsmaster: /mnt/storage/wamon   
error receiving data from mfsmaster: EAGAIN (Resource temporarily unavailable)   
root@crawling-1:/mnt/storage# mount -t moosefs mfsmaster: /mnt/storage/wamon   
error receiving data from mfsmaster: EAGAIN (Resource temporarily unavailable)   
root@crawling-1:/mnt/storage# mount -t moosefs mfsmaster: /mnt/storage/wamon   
error receiving data from mfsmaster: EAGAIN (Resource temporarily unavailable)   
```

systemctl status moosefs-master : 

```
May 08 06:37:18 localhost.localdomain mfsmaster[8816]: created new sessionid:9
May 08 06:37:28 localhost.localdomain mfsmaster[8816]: created new sessionid:10
May 08 06:37:32 localhost.localdomain mfsmaster[8816]: created new sessionid:11
```

**Comment by oxide94** [comment]
Helloe @codenoid,
Would you please let the Community know what was the issue and what actually helped to resolve it? It may be valuable for other users.

Thanks in advance,
Piotr / MooseFS Team

**Comment by codenoid** [comment]
Experimental Mode : 

Fedora Server 30 (yum package)

3 Server with specification :

* 8 Core CPU
* 12 GB RAM
* 25 GB OS DISK (HDD)
* 150 GB Storage DISK (HDD)

`/etc/hosts` file : 

```
5.5.5.41 server1
5.5.5.42 server2
5.5.5.43 server3

5.5.5.41 mfsmaster
```

1. All firewall in 3 server are turned off
2. i follow guide for moosefs minimal setup (https://github.com/moosefs/moosefs/blob/master/README.md#minimal-setup)
3. moosefs chunkserver status

server2 : 

```
● moosefs-chunkserver.service - MooseFS Chunkserver
   Loaded: loaded (/usr/lib/systemd/system/moosefs-chunkserver.service; disabled; vendor preset: disabled)
   Active: active (running) since Wed 2019-05-08 06:36:20 WIB; 14h ago
  Process: 3923 ExecStart=/usr/sbin/mfschunkserver start (code=exited, status=0/SUCCESS)
 Main PID: 3925 (mfschunkserver)
    Tasks: 9 (limit: 4915)
   Memory: 138.5M
   CGroup: /system.slice/moosefs-chunkserver.service
           └─3925 /usr/sbin/mfschunkserver start

May 08 06:36:20 localhost.localdomain mfschunkserver[3923]: hdd space manager: start background hdd scanning (searching for available chunks)
May 08 06:36:20 localhost.localdomain mfschunkserver[3925]: main server module: listen on *:10221
May 08 06:36:20 localhost.localdomain mfschunkserver[3923]: main server module: listen on *:10221
May 08 06:36:20 localhost.localdomain mfschunkserver[3925]: connecting ...
May 08 06:36:20 localhost.localdomain mfschunkserver[3925]: stats file has been loaded
May 08 06:36:20 localhost.localdomain mfschunkserver[3923]: stats file has been loaded
May 08 06:36:20 localhost.localdomain mfschunkserver[3923]: mfschunkserver daemon initialized properly
May 08 06:36:20 localhost.localdomain mfschunkserver[3925]: connected to Master
May 08 06:36:20 localhost.localdomain systemd[1]: Started MooseFS Chunkserver.
May 08 06:36:20 localhost.localdomain mfschunkserver[3925]: scanning folder /data/brick1/: complete (0s)
```

server3 : 

```
● moosefs-chunkserver.service - MooseFS Chunkserver
   Loaded: loaded (/usr/lib/systemd/system/moosefs-chunkserver.service; disabled; vendor preset: disabled)
   Active: active (running) since Wed 2019-05-08 06:36:28 WIB; 14h ago
  Process: 3446 ExecStart=/usr/sbin/mfschunkserver start (code=exited, status=0/SUCCESS)
 Main PID: 3448 (mfschunkserver)
    Tasks: 9 (limit: 4915)
   Memory: 138.5M
   CGroup: /system.slice/moosefs-chunkserver.service
           └─3448 /usr/sbin/mfschunkserver start

May 08 06:36:28 localhost.localdomain mfschunkserver[3446]: hdd space manager: start background hdd scanning (searching for available chunks)
May 08 06:36:28 localhost.localdomain mfschunkserver[3448]: main server module: listen on *:10222
May 08 06:36:28 localhost.localdomain mfschunkserver[3446]: main server module: listen on *:10222
May 08 06:36:28 localhost.localdomain mfschunkserver[3448]: connecting ...
May 08 06:36:28 localhost.localdomain mfschunkserver[3448]: stats file has been loaded
May 08 06:36:28 localhost.localdomain mfschunkserver[3446]: stats file has been loaded
May 08 06:36:28 localhost.localdomain mfschunkserver[3446]: mfschunkserver daemon initialized properly
May 08 06:36:28 localhost.localdomain mfschunkserver[3448]: connected to Master
May 08 06:36:28 localhost.localdomain systemd[1]: Started MooseFS Chunkserver.
May 08 06:36:28 localhost.localdomain mfschunkserver[3448]: scanning folder /data/brick1/: complete (0s)
```
**server1/master**

```
   Loaded: loaded (/usr/lib/systemd/system/moosefs-master.service; disabled; vendor preset: disabled)
   Active: active (running) since Wed 2019-05-08 05:55:35 WIB; 15h ago
 Main PID: 8816 (mfsmaster)
    Tasks: 2 (limit: 4915)
   Memory: 323.4M
   CGroup: /system.slice/moosefs-master.service
           ├─8816 /usr/sbin/mfsmaster start
           └─8817 mfsmaster (data writer)

May 08 19:00:00 localhost.localdomain mfsmaster[8816]: store process has finished - store time: 0.054
May 08 19:10:49 localhost.localdomain mfsmaster[8816]: structure check loop
May 08 20:00:00 localhost.localdomain mfsmaster[8816]: child finished
May 08 20:00:00 localhost.localdomain mfsmaster[8816]: store process has finished - store time: 0.055
May 08 20:05:26 localhost.localdomain mfsmaster[8816]: structure check loop
May 08 21:00:00 localhost.localdomain mfsmaster[8816]: child finished
May 08 21:00:00 localhost.localdomain mfsmaster[8816]: store process has finished - store time: 0.058
May 08 21:00:03 localhost.localdomain mfsmaster[8816]: structure check loop
```

it seems normal right, then

4. in ubuntu client, i install `moosefs-client fuse libfuse2`
5. when trying to connect with 

```
mount -t moosefs mfsmaster: /mnt/storage/wamon
```
in ubuntu, i got :

```
error receiving data from mfsmaster: EAGAIN (Resource temporarily unavailable)
```

in master fs server : 

```
May 08 21:20:24 localhost.localdomain mfsmaster[8816]: created new sessionid:12
May 08 21:20:24 localhost.localdomain mfsmaster[8816]: main master server module: (ip:5.5.5.11) write error: ECONNRESET (Connection reset by peer)
```

**Comment by oxide94** [comment]
Hi @codenoid,

It seems to be a network issue. Is your `/etc/hosts` file consistent among **all** MooseFS machines (including Client)? In order to check if you can connect to Master Server on all ports, try to use:

```
telnet mfsmaster 9419
telnet mfsmaster 9420
telnet mfsmaster 9421
```

You can also use `mfsnetdump` in order to see all MooseFS packets. See `man mfsnetdump` for more details.

Thanks,
Piotr / MooseFS Team

**Comment by codenoid** [comment]
1. from telnet, all port are conected

2. `mfsnetdump`  (server incoming connection): 

```
1557328325.860134 :  5. 5. 5. 11 : 48516 ->  5. 5. 5. 41 :  9421 ... new connection ...
1557328325.860175 :  5. 5. 5. 41 :  9421 ->  5. 5. 5. 11 : 48516 ... new connection ...
1557328325.860417 :  5. 5. 5. 11 : 48516 ->  5. 5. 5. 41 :  9421 CLTOMA_FUSE_REGISTER
        0x00000: 44 6A 49 31 47 41 51 44 55 4C 49 35 64 32 59 6A 41 32 36 79 70 63 33 6F 76 6B 68 6A 76 68 63 69
        0x00020: 54 51 56 78 33 43 53 34 6E 59 67 74 42 6F 55 63 73 6C 6A 69 56 70 73 45 72 4A 45 4E 48 61 77 30
        0x00040: 02 00 03 00 D0 00 00 00 13 2F 6D 6E 74 2F 73 74 6F 72 61 67 65 2F 77 61 6D 6F 6E 00 00 00 00 02
        0x00060: 2F 00
1557328325.860626 :  5. 5. 5. 41 :  9421 ->  5. 5. 5. 11 : 48516 MATOCL_FUSE_REGISTER
        0x00000: 00 03 00 D0 00 00 00 0D 5C D1 F7 BF 0E E6 8C A6 08 00 00 00 00 00 00 00 00 00 00 00 00 03 E7 00
        0x00020: 00 03 E7 01 09 00 00 00 00 FF FF FF FF
1557328325.860641 :  5. 5. 5. 41 :  9419 ->  5. 5. 5.  1 : 36266 MATOAN_METACHANGES_LOG
        0x00000: FF 00 00 00 00 00 00 00 27 31 35 35 37 33 32 38 33 32 35 7C 53 45 53 41 44 44 28 23 36 38 32 36
        0x00020: 35 32 31 30 32 37 36 36 32 35 35 36 39 38 38 2C 31 2C 38 2C 30 30 30 30 2C 30 2C 30 2C 39 39 39
        0x00040: 2C 39 39 39 2C 31 2C 39 2C 30 2C 34 32 39 34 39 36 37 32 39 35 2C 35 30 35 32 39 30 32 35 31 2C
        0x00060: 2F 6D 6E 74 2F 73 74 6F 72 61 67 65 2F 77 61 6D 6F 6E 29 3A 31 33 00
1557328325.860675 :  5. 5. 5. 11 : 48516 ->  5. 5. 5. 41 :  9421 ... close connection ...
1557328325.860828 :  5. 5. 5. 41 :  9419 ->  5. 5. 5.  1 : 36266 MATOAN_METACHANGES_LOG
        0x00000: FF 00 00 00 00 00 00 00 28 31 35 35 37 33 32 38 33 32 35 7C 53 45 53 44 49 53 43 4F 4E 4E 45 43
        0x00020: 54 45 44 28 31 33 29 00
1557328325.860858 :  5. 5. 5. 11 : 48516 ->  5. 5. 5. 41 :  9421 ... close connection ...
1557328326.062905 :  5. 5. 5. 11 : 48516 ->  5. 5. 5. 41 :  9421 CLTOMA_FUSE_REGISTER
        0x00000: 44 6A 49 31 47 41 51 44 55 4C 49 35 64 32 59 6A 41 32 36 79 70 63 33 6F 76 6B 68 6A 76 68 63 69
        0x00020: 54 51 56 78 33 43 53 34 6E 59 67 74 42 6F 55 63 73 6C 6A 69 56 70 73 45 72 4A 45 4E 48 61 77 30
        0x00040: 02 00 03 00 D0 00 00 00 13 2F 6D 6E 74 2F 73 74 6F 72 61 67 65 2F 77 61 6D 6F 6E 00 00 00 00 02
        0x00060: 2F 00
1557328326.062939 :  5. 5. 5. 41 :  9421 ->  5. 5. 5. 11 : 48516 ... close connection ...
1557328329.984529 :  5. 5. 5.  1 : 39336 ->  5. 5. 5. 41 :  9420 CSTOMA_CURRENT_LOAD
```

the client is `5. 5. 5. 11`

**Comment by codenoid** [comment]
something wrong with Fedora Server 30
