### ISSUE TITLE
Opening cgi is very slow？We have nearly 80 chunk servers

### ISSUE THREAD

**Issue by smallTang123** [moosefs/moosefs#263]
Is there any solution?

**Comment by oxide94** [comment]
Hello @smallTang123,

Opening CGI (especially tabs "Servers" or "Mounts") may be slow because of querying DNS server each time. You may want to consider adding some DNS caching on the machine where your CGI and CGI Server are installed.

Best regards,
Piotr / MooseFS Team

**Comment by smallTang123** [comment]
ok, thanks
