### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by asyslinux** [moosefs/moosefs#265]
MooseFS Version: 3.0.105

Please fix typo in log:

no metedata to store

un 27 05:53:47 server mfsmaster[26666]: main master server module: closing *:9421
Jun 27 05:53:47 server mfsmaster[26666]: master <-> chunkservers module: closing *:9420
Jun 27 05:53:47 server mfsmaster[26666]: master control module: closing *:9419
Jun 27 05:53:47 server mfsmaster[26666]: no metedata to store
Jun 27 05:53:47 server mfsmaster[26666]: process exited successfully (status:0)

**Comment by acid-maker** [comment]
Thanks :)
