### ISSUE TITLE
how to solve chunk server disk t be 100%

### ISSUE THREAD

**Issue by GYUMO** [moosefs/moosefs#268]
### Recently, I have add to chunk server to my moosefs system, however, I found that two old servers to be almost 100%, and the two new chunk server just to be 16%. how can I speed up the data to transfer from old server to new chunk server. Or can I limit the old server's store .
![image](https://user-images.githubusercontent.com/17978899/60559464-04e47800-9d7f-11e9-811f-81f8853d2f9a.png)

**Comment by xandrus** [comment]
You can tweak these settings in mfsmaster.cfg file. The fourth number is responsible for rebalancing chunks between other servers.

CHUNKS_WRITE_REP_LIMIT = 2,1,1,8
CHUNKS_READ_REP_LIMIT = 10,5,2,10

After that just reload the moosefs master server.
If this will be to slow please try to increase the last number twice, reload server and observe the cluster.

```
# Maximum number of chunks to replicate to one chunkserver (default is 2,1,1,4)
# one number is equal to four same numbers separated by colons
#  first limit is for endangered chunks (chunks with only one copy)
#  second limit is for undergoal chunks (chunks with number of copies lower than specified goal)
#  third limit is for rebalance between servers with space usage around arithmetic mean
#  fourth limit is for rebalance between other servers (very low or very high space usage)
# usually first number should be grater than or equal to second, second greater than or equal to third, and fourth greater than or equal to third ( 1st >= 2nd >= 3rd <= 4th )
# CHUNKS_WRITE_REP_LIMIT = 2,1,1,4

# Maximum number of chunks to replicate from one chunkserver (default is 10,5,2,5)
# one number is equal to four same numbers separated by colons
# limit groups are the same as in write limit, also relations between numbers should be the same as in write limits ( 1st >= 2nd >= 3rd <= 4th )
# CHUNKS_READ_REP_LIMIT = 10,5,2,5
```

**Comment by GYUMO** [comment]
> You can tweak these settings in mfsmaster.cfg file. The fourth number is responsible for rebalancing chunks between other servers.
> 
> CHUNKS_WRITE_REP_LIMIT = 2,1,1,8
> CHUNKS_READ_REP_LIMIT = 10,5,2,10
> 
> After that just reload the moosefs master server.
> If this will be to slow please try to increase the last number twice, reload server and observe the cluster.
> 
> ```
> # Maximum number of chunks to replicate to one chunkserver (default is 2,1,1,4)
> # one number is equal to four same numbers separated by colons
> #  first limit is for endangered chunks (chunks with only one copy)
> #  second limit is for undergoal chunks (chunks with number of copies lower than specified goal)
> #  third limit is for rebalance between servers with space usage around arithmetic mean
> #  fourth limit is for rebalance between other servers (very low or very high space usage)
> # usually first number should be grater than or equal to second, second greater than or equal to third, and fourth greater than or equal to third ( 1st >= 2nd >= 3rd <= 4th )
> # CHUNKS_WRITE_REP_LIMIT = 2,1,1,4
> 
> # Maximum number of chunks to replicate from one chunkserver (default is 10,5,2,5)
> # one number is equal to four same numbers separated by colons
> # limit groups are the same as in write limit, also relations between numbers should be the same as in write limits ( 1st >= 2nd >= 3rd <= 4th )
> # CHUNKS_READ_REP_LIMIT = 10,5,2,5
> ```

Oh,thak you very much.
