### ISSUE TITLE
buster repo?

### ISSUE THREAD

**Issue by dragon2611** [moosefs/moosefs#275]
Can we get a repo added for debian 10 (buster) please?

**Comment by onlyjob** [comment]
MooseFS is pending review/approval for inclusion to official Debian repositories.
Once accepted, I will prepare package for _buster-backports_.

**Comment by Zorlin** [comment]
Can we get a build for ARM devices such as the ODROID HC2?

**Comment by onlyjob** [comment]
ARMs are production architectures so yes, we should get it automatically as soon as package is accepted...

**Comment by oxide94** [comment]
Hi Dmitry @onlyjob,

Do you know is there any way to ask ftp-master Team to review and accept MooseFS packaging rather sooner than later? :) It's been pending for almost 8 months and [it's 15th on the list](https://ftp-master.debian.org/new.html) at this moment.

I understand that they may be busy or have other packages with higher priority (and I don't want to put any pressure on them), but basing on the [graphs about the queue](https://ftp-master.debian.org/stat.html), many other packages were accepted during this time.

Many thanks,
Piotr

**Comment by onlyjob** [comment]
I think we just have to wait. I'd rather not ask as we are so close to the top of the list. :)

It takes a while sometimes and in this particular case I have uploaded during pre-release freeze which added to delay.

Some packages may be taken from the queue in a matter of priority such as when a library blocks a dependency or when package is trivial.

**Comment by oxide94** [comment]
Thanks a lot for your comment on that. Piotr
