### ISSUE TITLE
error when compiling under macos

### ISSUE THREAD

**Issue by eleaner** [moosefs/moosefs#279]
I cloned the latest version 
thenI have executed
aclocal && automake && autoconf

and then ./macosx_build.sh
complain about systemd

```
./configure: line 16543: PKG_PROG_PKG_CONFIG: command not found
./configure: line 16544: syntax error near unexpected token `SYSTEMD,'
./configure: line 16544: `PKG_CHECK_MODULES(SYSTEMD, systemd,'
make: *** No targets specified and no makefile found.  Stop.
```
I  am not sure if this is available under macos 

osx version 10.13.6

**Comment by oxide94** [comment]
Hello @eleaner,
> thenI have executed
> aclocal && automake && autoconf

This is not necessary. Please clone the repo again and just run `./macosx_build.sh` without running anything else earlier, it should work properly.

Best regards,
Piotr / MooseFS Team

**Comment by oxide94** [comment]
You can also try using:

```
cd /path/to/repo/macosx
./makepkg.sh
```

which will generate `*.pkg` file. Or you can download a ready package from [here](http://ppa.moosefs.com/moosefs-3/osx/10.11/moosefs-3.0.105-1.pkg).

Best regards,
Piotr / MooseFS Team

**Comment by eleaner** [comment]
I went for a prebuilt package
Thank you!
