### ISSUE TITLE
After reboot mfs-master server, the master server can't be connected

### ISSUE THREAD

**Issue by buweilv** [moosefs/moosefs#28]
I install mfs-server3 in kvm vm based on centos7, After reboot mfs-master server, the master server can't be connected: 

- the cgi web page can't be connected
- chunkserver can't be connectet to master
- client can;t be mounted on master

how to solve it?

**Comment by yinjiawind** [comment]
Hi,
Can you provide more information? Such as chunkserver log, master log, client log...

**Comment by buweilv** [comment]
@yinjiawind  am soory to find just close every server's firewall, all the connections can work properly!
