### ISSUE TITLE
Reset "damaged" disks

### ISSUE THREAD

**Issue by colindaven** [moosefs/moosefs#291]
## Have you read through available documentation and open Github issues?

Yes

## Is this a BUG report, FEATURE request, or a QUESTION? Who is the indended audience?

QUESTION for the COMMUNITY

#### Your moosefs version and its origin (moosefs.com, packaged by distro, built from source, ...).
 mfschunkserver -v
version: 3.0.104-1

#### Operating system (distribution) and kernel version.

Linux 4.15.0-47-generic #50~16.04.1-Ubuntu SMP
x86_64 x86_64 x86_64 GNU/Linux

#### Hardware / network configuration, and underlying filesystems on master, chunkservers, and clients.

3 chunkservers, 1 separate master.

#### How much data is tracked by moosefs master (order of magnitude)?

About 60 TB

## Describe the problem you observed.

After a planned power outage at the University hospital, networks went down for ~30 minutes. The servers continued running fine and still show a long uptime.

However mfs has listed all the files as "missing" and disks as "damaged". Is there a way to overrride this damaged setting, perhaps in the metadata ? Or a DB field which could be changed ? 
We are sure that the disks are not all damaged, just that the network connection to the mfs master server were completely gone.

This happened midweek and mfs contents only change via ansible rsync at the weekend, so can I just replace the metadata with backed up metadata from before the blackout ?

Thank you for a great system and for your help!
Colin

#### Can you reproduce it? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

I don't want to :-)

**Comment by oxide94** [comment]
Hello @colindaven,

In order to "clear" damaged mark, just restart the chunkservers one-by-one (i.e. restart the chunkserver, wait for it to connect, check "All Chunks State Matrix in MFS CGI – tab "Info" and see if all the chunks are properly seen, then repeat this process for the rest of chunkservers).

However please also check Chunkservers' logs, as MooseFS marks disks as "damaged" when there are I/O errors.

Best regards,
Piotr / MooseFS Team

**Comment by colindaven** [comment]
Thanks a lot Piotr !

Restarting the individual chunkservers then starting mfschunkserver solved the issue

To be clear,:
`sudo reboot`
`sudo mfschunkserver start`

We couldn't find any errors in the logs.

Next time, we'll stop the servers over a blackout (we sometimes have problems restarting them, so left them on this time).

Colin
