### ISSUE TITLE
[question] how to install chunkserver on odroid HC2?

### ISSUE THREAD

**Issue by eleaner** [moosefs/moosefs#294]
Hi,

I just bought this pretty machine 
https://www.hardkernel.com/shop/odroid-hc2-home-cloud-two/

It runs Arm7
I managed to instal Xenial 16.04.6 
kernel 4.14.5-92

now when I try to use ubuntu repo I get the following message
`N: Skipping acquire of configured file 'main/binary-armhf/Packages' as repository 'http://ppa.moosefs.com/moosefs-3/apt/ubuntu/xenial xenial InRelease' doesn't support architecture 'armhf'`

I am not hell-bent on ubuntu, anything will do as long as it runs a chunkserver

**Comment by oxide94** [comment]
Hello @eleaner,

At http://get.moosefs.com, at the very bottom, you have a description how to add Raspbian Jessie ARM repository (please collapse "Ubuntu" and expand "Raspberry Pi 3"). This is the latest build for ARM we currently have and these packages will probably work with Ubuntu Xenial on Odroid. If you have any issues with this, [here](https://ppa.moosefs.com/moosefs-3/apt/raspbian/jessie/pool/main/m/moosefs) is a direct link to the packages.

Of course I agree that the best is to have a native build, so you can build MooseFS from sources on this platform easily, as described [here](https://github.com/moosefs/moosefs#source-code).

Hopefully MooseFS will get approved as a Debian packages soon (see #275) and packages and repo for this architecture will be built automatically.

Best regards,
Piotr / MooseFS Team

**Comment by eleaner** [comment]
compilation on 16.04 threw a few errors so I gave up, but the linked Pi 3  package works like a charm
