### ISSUE TITLE
[question] chunkserver HDD direct or backed with bcache on SSD?

### ISSUE THREAD

**Issue by eleaner** [moosefs/moosefs#296]
Hi,

what are the recommendations on using or not SSD cache like bcache for the chunkservers?

**Comment by onlyjob** [comment]
First of all _bcache_ is probably the worst choice out there. I'd use [dm-writeboost](https://github.com/akiradeveloper/dm-writeboost) or _EnhanceIO_.

I recommend not to bother with SSD caching at all. Read caching will not be effective and the maintenance overhead is significant. Using SSD for write acceleration helps to improve performance but on MooseFS you should design your Storage Classes instead.

Consider something like 

    ## create new chunks on SSD but keep them on rotational disks:
    mfsscadmin /mnt/mfs create -m s -C S,S -K R,R,R ssd3r

    ## create new chunks on SSD, then keep one copy on SSD and another copy on rotational disks
    ## move all chunks to rotational disks after 7 days:
    mfsscadmin /mnt/mfs create -m s -C S,S -K R,S -A R,R -d 7 ssd2r

You can assign storage class using `mfssetsclass` command; read by `mfsgetsclass` command.

That implies that your SSD-based chunkservers are labelled `S` and rotational disks chunkservers are labelled `R`.

**Comment by eleaner** [comment]
following up the storage class idea
I have Microserver gen8 with a place for four HDD (SATA3) and one CD(SATA2)
if I connect SSD to SATA2 it is a waste but based on what I read it will still be faster than the HDD
So let's just assume that my machine has 4HDD (24T) and 1SSD (0.5T)
and I have two such machines
plus one machine for just HDD

Am I correct it means I would have to run separate chunk servers
one for SSD - tagged S
and one for HDD - tagged R

then I could be able to go with -C 2S -K 3R

is that what you mean?

**Comment by onlyjob** [comment]
I mean _read the documentation on Storage Classes_. You'll understand. ;)

**Comment by eleaner** [comment]
well...
I read it and that's exactly how I understand it.
Do you suggest I got it wrong?

**Comment by dragon2611** [comment]
@onlyjob Raid is not a backup it just gives a bit of breathing space if one disk dies, it's only a 3 disk array, even if I used a higher raid level it would still be a problem if the server motherboard fried (that's happened before)

If the only copy is on a single raid-5 then it's a file I don't care about.
If its on moosefs and the replication factor is set so it's also stored elsewhere it's a file I care about a little bit but not enough to backup.

If it's something I care about it's backed up elsewhere, regularly.
