### ISSUE TITLE
Could not recovery delete file from trash bin!

### ISSUE THREAD

**Issue by Hello-Linux** [moosefs/moosefs#30]
When I copy the delete jpg file to undel directory it show “cp: cannot create regular file `undel/0000054C|shop|goods_class|04849412911666956.jpg': Function not implemented” and I could not set the trashtime it show “mfssettrashtime -r 5 /home/shop/data/upload/
/home/shop/data/upload/:
 inodes with trashtime changed:              0
 inodes with trashtime not changed:       1303
 inodes with permission denied:              1
You have new mail in /var/spool/mail/root
“
mount the meta is “mfsmount  -H 192.168.1.205 -o mfsmeta,mfsflattrash,mfspassword=123456   /home/shop/data/mfsmeta” and the directory jurisdiction is “dr-xr-xr-x  4 root  root        0 Dec 26 11:22 mfsmeta” 
below is my configuration  screenshot
![qq 20161226111924](https://cloud.githubusercontent.com/assets/17851645/21474684/cf399492-cb5d-11e6-9024-4085ca55a5c4.png)
![qq 20161226112212](https://cloud.githubusercontent.com/assets/17851645/21474685/cf3a526a-cb5d-11e6-97c2-162a2c3bdaab.png)
![qq 20161226112243](https://cloud.githubusercontent.com/assets/17851645/21474686/cf3c6186-cb5d-11e6-8fca-9b88fce94411.png)

**Comment by uu** [comment]
Use `mv` instead of `cp`.
