### ISSUE TITLE
How to export an existing folder (a git repo which has files in it) to clients

### ISSUE THREAD

**Issue by shangma-brainoft** [moosefs/moosefs#301]
## Have you read through available documentation and open Github issues?

Yes

## Is this a BUG report, FEATURE request, or a QUESTION? Who is the indended audience?

QUESTION for the COMMUNITY

#### Your moosefs version and its origin (moosefs.com, packaged by distro, built from source, ...).
Installed on ubuntu 16.04 from apt-get

mfsmaster -v    gives  version: 3.0.105-1

#### Operating system (distribution) and kernel version.

Master, metalogger, and chunkserver: 
Linux 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

Client:
Linux 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.8 (stretch)
Release:	9.8
Codename:	stretch

MFS version 3.0.105-1
FUSE library version: 2.9.7
fusermount version: 2.9.7

#### Hardware / network configuration, and underlying filesystems on master, chunkservers, and clients.

I use three Ubuntun on x86_64 as master, chunck server, and metalogger respectively.
Two RPi 3b+ work as clients.

#### How much data is tracked by moosefs master (order of magnitude)?

 - All fs objects: Not applicable
 - Total space: Not applicable
 - Free space: Not applicable
 - RAM used: Not applicable
 - last metadata save duration: Not applicable

## Describe the problem you observed.
New on moosefs. Many thanks for your work!
I have master, chunk server, metalogger, and two clients (Raspberry Pi) running. If I create a file on one client, the other client can see it. Awesome! 
My question is I have some files (a git repo) on the master that I would like to share among clients, where should I put them? Or put in another way, where is that root  ('/') in the mfsexports.cfg? Is it somewhere on the master or chunk server? Can I just copy files to that location then all clients will be able to see those files or do I have to copy all files through one of the clients?

#### Can you reproduce it? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Yes. Fresh installation. Then put the host name of the master in the /etc/hosts files on metalogger, chunk server, and clients. Add a partition for chunk server to save it data. 
#### Include any warning/errors/backtraces from the system logs

```
mfsexports.cfg on master:
        # Allow everything but "meta".
        *			/	rw,alldirs,admin,maproot=0:0
        # Allow "meta".
        *			.	rw
mfshdd.cfg:
        /mnt/mfschunks1

Mount command on clients:
       sudo mfsmount /mnt/mfs/ -H master_host_name
```

**Comment by oxide94** [comment]
Hello @shangma-brainoft,
Just mount the client also on Master Server, copy necessary data an unmount if you do not need it mounted on Master anymore.

> Or put in another way, where is that root ('/') in the mfsexports.cfg?

That rootdir (`/`) is a rootdir mounted on client.

Example:
Imagine you mount `ext4` file system – then rootdir is mounted in selected directory, e.g. `/mnt/disk` and you use `mount` command (`mount -t ext4 /dev/sdx1 /mnt/disk`). With MooseFS, as it is a filesystem, it is similar: you mount it with `mount` command (e.g. `mount -t moosefs mfsmaster.hostname: /mnt/mfs` somewhere (e.g. `/mnt/mfs`) and rootdir of the file system (MooseFS in this case) goes where you mounted it. At least unless you mount a subdir with `-o mfssubfolder=/subdir/path` or `-S /subdir/path`.

Best regards,
Piotr / MooseFS Team

**Comment by shangma-brainoft** [comment]
@oxide94  Thanks for your quick reply. 
Questions, what do you mean by  "Just mount the client also on Master Server"? Are you suggesting that I should make the client a server so my master can mount from it  OR I should install moosefs-client on the master as well so I can run mfsmount as I did on a regular client and copy those files over? And I just did the latter and it works! Many thanks for the help.

**Comment by oxide94** [comment]
Hello @shangma-brainoft,

> (...) OR I should install moosefs-client on the master as well so I can run mfsmount as I did on a regular client and copy those files over?

Indeed I meant this :) Glad it helped you.

Best regards,
Piotr / MooseFS Team
