### ISSUE TITLE
MooseFS 3.0.86+FUSE3.0.1,Compilation fails

### ISSUE THREAD

**Issue by itongqingbo** [moosefs/moosefs#302]
**I compile MooseFS3.0.86 with FUES3.0+, and failed to compile. Do Moosefs support fuse3.0+ ? please，give me a help to compile MooseFS 3.0.86 with FUSE3.0.1. **

My error:
1. main.c:548:4: error: too many arguments to function ‘fuse_parse_cmdline’
    fuse_parse_cmdline(&helpargs,NULL,NULL,NULL);
2.main.c:976:3: error: too few arguments to function ‘fuse_session_loop_mt’
   err = fuse_session_loop_mt(se);
3.main.c:548:4: error: too many arguments to function ‘fuse_parse_cmdline’
    fuse_parse_cmdline(&helpargs,NULL,NULL,NULL);
4.moosefs-3.0.86/mfsmount/main.c:898: undefined reference to `fuse_lowlevel_new'
moosefs-3.0.86/mfsmount/main.c:931: undefined reference to `fuse_session_add_chan'
moosefs-3.0.86/mfsmount/main.c:993: undefined reference to `fuse_session_remove_chan'

**Comment by acid-maker** [comment]
MooseFS does not support fuse 3.x - please use 2.9.

**Comment by onlyjob** [comment]
@acid-maker, is there a ticket to track progress of transition to libfuse 3?

**Comment by acid-maker** [comment]
Migration to libfuse3 is on our roadmap. Since it shouldn't be much work probably we will do it sooner than later :)

**Comment by acid-maker** [comment]
I've migrated code to libfuse3 - this is still work in progress. As for now everything looks fine - we need to do more tests.

**Comment by onlyjob** [comment]
Thanks, @acid-maker. Please make sure that https://github.com/lizardfs/lizardfs/issues/807 is not repeated i.e. under FUSE3 it should not be possible to mount directory more than once.

**Comment by acid-maker** [comment]
Thanks for hint - yes we have the same issue - fixing
