### ISSUE TITLE
moosefs and qemu write locks do not work together well

### ISSUE THREAD

**Issue by steffenb7333** [moosefs/moosefs#305]
I am not really sure were the origin of the problem lies, but I have a lot of trouble getting qemu 4.[01].0 work, when VM images are stored on a moosefs filesystem.

Basically after running an image once and then trying to restart it, qemu complains about not being able to obtain a write lock. The only working solution I found until now to mitigate the problem is unmounting the filesystem and then mounting it again.

A shared read lock is shown in the resources tab of mfscgiserv even after qemu terminates. (Is there a way to force a lock to be dropped?)

Since the qemu internal locking seems to work on any other filesystem I think something may be off regarding the used posix locks.

```
# qemu-img create -f qcow2 test.img.qcow2 5G
Formatting 'test.img.qcow2', fmt=qcow2 size=5368709120 cluster_size=65536 lazy_refcounts=off refcount_bits=16
# qemu-system-x86_64 test.img.qcow2
VNC server running on ::1:5900
^Cqemu-system-x86_64: terminating on signal 2
# qemu-system-x86_64 test.img.qcow2
qemu-system-x86_64: test.img.qcow2: Failed to get "write" lock
Is another process using the image [test.img.qcow2]?

```

I am using moosefs 3.0.103 and qemu 4.[01].0.

**Comment by acid-maker** [comment]
Confirmed - we were able to reproduce this. Working on solution.

**Comment by acid-maker** [comment]
ok. This is bug in qemu/kernel - likely in the kernel. During close I got from kernel wrong lock_owner.

here is the example log from mfsmount for qemu:
```
10.28 06:55:20.514173: uid:0 gid:0 pid:13603 cmd:setlk (inode:15337 owner:CB6643B3F852916F start:201 end:202 type:U) [handle:02000001] ...
10.28 06:55:20.514830: uid:0 gid:0 pid:13603 cmd:setlk (inode:15337 owner:CB6643B3F852916F start:201 end:202 type:U) [handle:02000001]: OK
10.28 06:55:20.515413: uid:0 gid:0 pid:13603 cmd:flush (15337) [handle:02000001] ...
10.28 06:55:20.516104: uid:0 gid:0 pid:13603 cmd:flush (15337) - releasing all POSIX-type locks for 6CAD9DC1D921824A (received from kernel): OK
10.28 06:55:20.516110: uid:0 gid:0 pid:13603 cmd:flush (15337) [handle:02000001,uselocks:2,lock_owner:6CAD9DC1D921824A]: OK
```

As you can see in lock commands (setlk) owner is here `0xCB6643B3F852916F` and then in close (flush) owner sent by kernel is `0x6CAD9DC1D921824A`. Pid and inode is the same (pid=13603,inode=15337), so owner should be the same. Even file descriptor (handle) is the same !!!

The only difference between moose and kernel is that kernel releases all locks on last release, and this is why it works when locks are handled by the kernel. The only fix I can see is to do the same in moose - release all locks left by kernel on last release.

I'm working on such workaround.
