### ISSUE TITLE
This short test program deadlocks (ftruncate)

### ISSUE THREAD

**Issue by njaard** [moosefs/moosefs#306]
This program stops running and becomes unkillable after just a couple rows of stderr output.

0. Compile the program: `c++ -lpthread mfsdeadlock.cpp -o ~/mfsdeadlock`
1. mfsmount a volume normally
2. `cd /mfsmount` (cd into the mountpoint)
3. `dd of=file if=/dev/zero bs=1000 count=2018606` (though it should work with "any" filesize)
4. `~/mfsdeadlock` (run the attached test program)

removing the `ftruncate` "solves" the problem, though the output still has "weird" performance. Curiously, using only a single "read" thread works as expected.

[mfsdeadlock.txt](https://github.com/moosefs/moosefs/files/3775447/mfsdeadlock.txt)

The only way to exit the program is to `kill -9` mfsmount (and then `umount`).

The mfsmount remains usable, only the `ftruncate` thread blocks.

**Comment by njaard** [comment]
Here's it's reduced even more (the `F_DUPFD_CLOEXEC`) isn't necessary.

If I decrease the number of `write`, then it seems like the problem is harder to replicate (maybe impossible with only 1, but then the performance is *really* weird).

[mfsdeadlock.txt](https://github.com/moosefs/moosefs/files/3775453/mfsdeadlock.txt)

**Comment by acid-maker** [comment]
Confirmed.

**Comment by acid-maker** [comment]
Found.

If you need quick fix then find such lines in mfsclient/readdata.c (end of function `read_data_set_length_active`):

```
        if (ind->waiting_writers>0) {
                zassert(pthread_cond_signal(&(ind->writerscond)));
        } else {
                zassert(pthread_cond_signal(&(ind->readerscond)));
        } 
```

and change to:

```
        if (ind->waiting_writers>0) {
                zassert(pthread_cond_signal(&(ind->writerscond)));
        } else {
                zassert(pthread_cond_broadcast(&(ind->readerscond)));
        }
```

I will send patch to github later - together with other pending changes

**Comment by njaard** [comment]
Thanks for the incredibly quick response and fix! I have my own workaround so I'll wait for updated Debian packages.
