### ISSUE TITLE
ValueError thrown by mfscli -SIM

### ISSUE THREAD

**Issue by Programie** [moosefs/moosefs#308]
## Have you read through available documentation and open Github issues?

Yes

## Is this a BUG report, FEATURE request, or a QUESTION? Who is the indended audience?

BUG report

#### Your moosefs version and its origin (moosefs.com, packaged by distro, built from source, ...).

3.0.107 for Debian Stretch from https://ppa.moosefs.com

#### Operating system (distribution) and kernel version.

```
$ uname -vsrm; mfsmount -V; lsb_release -a
Linux 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u5 (2019-08-11) x86_64
MFS version 3.0.107-1
FUSE library version: 2.9.7
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.11 (stretch)
Release:	9.11
Codename:	stretch
```

## Describe the problem you observed.

Executing `mfscli -H localhost -SIM` throws a ValueError:

```
Traceback (most recent call last):
  File "/usr/bin/mfscli", line 1960, in <module>
    for sortip,strip,sortver,strver,statestr,statecolor,metaversion,memusage,syscpu,usercpu,lastsuccessfulstore,lastsaveseconds,lastsavestatus,exportschecksum,metaid,lastsavemetaversion,lastsavemetachecksum,usectime,chlogtime in masterlistinfo:
ValueError: not enough values to unpack (expected 19, got 16)
```

I've looked into the mfscli script and found [this line](https://github.com/moosefs/moosefs/blob/master/mfsscripts/mfscli.py.in#L1933) where the masterlistinfo list is filled:

```
masterlistinfo.append((sortip,strip,sortver,strver,statestr,statecolor,metaversion,memusage,syscpu,usercpu,lastsuccessfulstore,lastsaveseconds,lastsavestatus,exports_checksum,usectime,chlogtime))
```

Only 16 values are added, but metaid, lastsavemetaversion and lastsavemetachecksum are missing.

**Comment by Programie** [comment]
I just saw, the same exception is also thrown on the CGI frontend in the mfs.cgi.

**Comment by xandrus** [comment]
Hi,

Thank you for this information, but I suspect that you shouldn't use the localhost to communicate with the master. Please use your LAN IP or FQDN instead.

For example:
mfscli -SIM -H 192.168.100.1
