### ISSUE TITLE
I can't set trash time for file

### ISSUE THREAD

**Issue by Hello-Linux** [moosefs/moosefs#31]
when I run mfssettrash to file then it show
```
mfssettrashtime -r 5 /home/shop/data/upload
/home/shop/data/upload:
 inodes with trashtime changed:              0
 inodes with trashtime not changed:       1309
 inodes with permission denied:              1
```

msmount is in fstab：`mfsmount /home/shop/data/upload fuse defaults,nonempty,mfspassword=123456,mfsmaster=192.168.1.244,mfsport=9421 0 0`

the master configuration is
```
# Allow everything but "meta".
192.168.1.0/24                  /       rw,admin,alldirs,mapall=498:498,password=12345
# Allow "meta".
192.168.1.0/24                  .       rw,password=123456
```
master user is nginx  UID is 498 and web user is nginx   ID is 498，the mount point is `drwxr-xr-x  2 nginx nginx  4096 Dec 14 19:41 upload`  but when I run mfsmount  the upload is `drwxrwxrwx 10 root  root  2004173 Dec 29 19:53 upload`  why the upload‘s UID is root？ and I cant‘ change the trash time’

**Comment by xandrus** [comment]
Hi,
According to trash time.
If you set mfssettrashtime -r option it means that operation was done recursively, and upload folder will create new files with this specific trash time. So trash time is inheritance from upload folder.
You can check file status with mfsgettrashtime command.

About second problem.
What result do you see during mfsmount command execution?
You should see something like this:

`mfsmaster accepted connection with parameters: read-write,restricted_ip,map_all ; root mapped to nginx:nginx ; users mapped to nginx:nginx`

**Comment by xandrus** [comment]
Hi,
How things are going?
