### ISSUE TITLE
Chunkserver just open for a short amount of time on Ubuntu

### ISSUE THREAD

**Issue by Kindhearted57** [moosefs/moosefs#315]
Hi I'm testing moosefs on Ubuntu 18.04, installing chunkserver master server client and metalogger on this same os. I have come across some issues.
Here are the steps that I followed:

```
apt install build-essential libpcap-dev zlib1g-dev libfuse-dev pkg-config fuse Liz* -y

useradd -s /sbin/nologin mfs

cd /moosefs-master

./configure --prefix=/usr/local/mfs --with-default-user=mfs --with-default-group=mfs

make&&make install

cd /usr/local/mfs/etc/mfs/
 
cp mfschunkserver.cfg.sample  mfschunkserver.cfg
cp mfshdd.cfg.sample  mfshdd.cfg

 vi mfschunkserver.cfg
//I changed the following content
MASTER_HOST  =  172.16.253.222
MASTER_PORT  = 9420

vi   mfshdd.cfg
//add:
/data       

mkdir /data
 
chown -R mfs:mfs /data/

chown -R mfs.mfs /usr/local/mfs
ln -s /usr/local/mfs/sbin/* /usr/local/bin/

mfschunkserver start
 
```
I don't know what I have done wrong, but when I run `netstat -anpt | grep 'mfschunkserver' `, nothing returned. And I also discovered that if I run mfschunkserver start repeatedly, the following two log will return by turns, so I am assuming that the server is just opened for a really short amount of time, then it's closed.
```
open files limit has been set to: 16384
working directory: /usr/local/mfs/var/mfs
lockfile created and locked
setting glibc malloc arena max to 4
setting glibc malloc arena test to 4
initializing mfschunkserver modules ...
hdd space manager: path to scan: /data/
hdd space manager: start background hdd scanning (searching for available chunks)
main server module: listen on *:9422
stats file has been loaded
mfschunkserver daemon initialized properly
```
```
open files limit has been set to: 16384
working directory: /usr/local/mfs/var/mfs
can't start: lockfile is already locked by another process
```
I'm new to moosefs, and I have spent the whole night on this problem. Really want to know why. Many thanks to anyone who can help with that.

**Comment by uu** [comment]
why you didn't use prebuilt packages? 
https://moosefs.com/download/

**Comment by xandrus** [comment]
Hi,

First of all, can you tell us what you are installing when you are running this command ```apt install Liz*``` ?
Are you sure that you are using MooseFS?
Please check:
```mfschunkserver -v```

Without more details, we will not be able to do much.
Can you send us some system logs?

By the way.
You can start chunkserver in foreground and see what is going on.

```
mfschunkserver -f
```
And also there is a simple instruction on GitHub how to build MooseFS:
https://github.com/moosefs/moosefs#source-code

**Comment by Kindhearted57** [comment]
> Hi,
> 
> First of all, can you tell us what you are installing when you are running this command `apt install Liz*` ?
> Are you sure that you are using MooseFS?
> Please check:
> `mfschunkserver -v`
> 
> Without more details, we will not be able to do much.
> Can you send us some system logs?
> 
> By the way.
> You can start chunkserver in foreground and see what is going on.
> 
> ```
> mfschunkserver -f
> ```
> 
> And also there is a simple instruction on GitHub how to build MooseFS:
> https://github.com/moosefs/moosefs#source-code

Thanks for your reply and patience!
I followed some instructions of a blog when I did this, but it turns out `apt install Liz*` isn't really doing anything...
I followed your suggestion, and here's what I found:
`mfschunkserver -v`
it returns:
`version: 3.0.109-1 ; build: 1048`
`mfschunkserver -f`
```
mfschunkserver[7212]: open files limit has been set to: 16384
open files limit has been set to: 16384
mfschunkserver[7212]: set gid to 1001
mfschunkserver[7212]: set uid to 1001
working directory: /usr/local/mfs/var/mfs
lockfile created and locked
mfschunkserver[7212]: setting glibc malloc arena max to 4
setting glibc malloc arena max to 4
mfschunkserver[7212]: setting glibc malloc arena test to 4
setting glibc malloc arena test to 4
mfschunkserver[7212]: out of memory killer disabled
mfschunkserver[7212]: monotonic clock function: clock_gettime
mfschunkserver[7212]: monotonic clock speed: 194419 ops / 10 mili seconds
initializing mfschunkserver modules ...
mfschunkserver[7212]: hdd space manager: folder /data/ will be scanned
mfschunkserver[7212]: hdd space manager: setting open chunks limit to: 10922
hdd space manager: path to scan: /data/
hdd space manager: start background hdd scanning (searching for available chunks)
mfschunkserver[7212]: main server module: listen on *:9422
main server module: listen on *:9422
mfschunkserver[7212]: connecting ...
mfschunkserver[7212]: stats file has been loaded
stats file has been loaded
mfschunkserver daemon initialized properly
mfschunkserver[7212]: connected to Master
mfschunkserver[7212]: MATOCS_MASTER_ACK - wrong meta data id (file chunkserverid.mfs:5DEE121A164F0D0B ; received from master:5DEF677B2F55BBC8). Can't connect to master
mfschunkserver[7212]: closing connection with master
mfschunkserver[7212]: internal terminate request
mfschunkserver[7212]: closing *:9422
mfschunkserver[7212]: exited from main loop
exited from main loop
mfschunkserver[7212]: exititng ...
exititng ...
mfschunkserver[7212]: terminating aux threads
mfschunkserver[7212]: closing chunks
mfschunkserver[7212]: freeing data structures
mfschunkserver[7212]: hddspacemgr: terminating done
mfschunkserver[7212]: process exited successfully (status:0)
process exited successfully (status:0)
```
So I guess I'm getting this problem because I got a wrong meta data id. I found this situation much like issue#245. 
I tried `rm -rf data/.metaid`, but it didn't seem to help.
Plus I didn't use the prebuilt package because I wanted to build these four parts(masterserver\chunkserver\metalogger\client)at the same time....

**Comment by xandrus** [comment]
Hi,

Thanks for this information. No we have a clear picture. 
```
mfschunkserver[7212]: MATOCS_MASTER_ACK - wrong meta data id
(file chunkserverid.mfs:5DEE121A164F0D0B ; received from master:5DEF677B2F55BBC8).
Can't connect to master
```

If you are 100% sure that this chunk server should be connected to this specific master server you have to remove not only .metaid from mfshdd.cfg mount paths but also chunkserverid.mfs from the metadata folder. So I suspect that in your case it will be:
```
/usr/local/mfs/var/mfs/chunkserverid.mfs
```

I would like to add that this is MooseFS security mechanism to disallow connecting chunk servers from one MooseFS Cluster to another.  
Without such a mechanism there is a very easy way to lose data.

**Comment by Kindhearted57** [comment]
> Hi,
> 
> Thanks for this information. No we have a clear picture.
> 
> ```
> mfschunkserver[7212]: MATOCS_MASTER_ACK - wrong meta data id
> (file chunkserverid.mfs:5DEE121A164F0D0B ; received from master:5DEF677B2F55BBC8).
> Can't connect to master
> ```
> 
> If you are 100% sure that this chunk server should be connected to this specific master server you have to remove not only .metaid from mfshdd.cfg mount paths but also chunkserverid.mfs from the metadata folder. So I suspect that in your case it will be:
> 
> ```
> /usr/local/mfs/var/mfs/chunkserverid.mfs
> ```
> 
> I would like to add that this is MooseFS security mechanism to disallow connecting chunk servers from one MooseFS Cluster to another.
> Without such a mechanism there is a very easy way to lose data.

Thanks for your reply! it seems that the wrong meta data id has been solved. But when I input
`sudo mfschunkserver start -f`
it hangs here forever:
```
mfschunkserver[2082]: open files limit has been set to: 16384
open files limit has been set to: 16384
mfschunkserver[2082]: set gid to 1001
mfschunkserver[2082]: set uid to 1001
working directory: /usr/local/mfs/var/mfs
lockfile created and locked
mfschunkserver[2082]: setting glibc malloc arena max to 4
setting glibc malloc arena max to 4
mfschunkserver[2082]: setting glibc malloc arena test to 4
setting glibc malloc arena test to 4
mfschunkserver[2082]: out of memory killer disabled
mfschunkserver[2082]: monotonic clock function: clock_gettime
mfschunkserver[2082]: monotonic clock speed: 410010 ops / 10 mili seconds
initializing mfschunkserver modules ...
mfschunkserver[2082]: hdd space manager: folder /data/ will be scanned
mfschunkserver[2082]: hdd space manager: setting open chunks limit to: 10922
hdd space manager: path to scan: /data/
hdd space manager: start background hdd scanning (searching for available chunks)
mfschunkserver[2082]: main server module: listen on *:9422
main server module: listen on *:9422
mfschunkserver[2082]: connecting ...
mfschunkserver[2082]: stats file has been loaded
stats file has been loaded
mfschunkserver daemon initialized properly
mfschunkserver[2082]: connected to Master
mfschunkserver[2082]: scanning folder /data/: .chunkdb used - full scan not needed
mfschunkserver[2082]: scanning folder /data/: complete (0s)
```
So do I have to do something else after I delete the two files? Thanks a lot

**Comment by pkonopelko** [comment]
Hello @Kindhearted57,

`-f` ("Run in foreground, don't daemonize") parameter should be used for debugging purposes and since you resolved the issue, please just run it without `-f` parameter in order to allow the Chunkserver to be ran as daemon and not in foreground.

Best regards,
Piotr / MooseFS Team

**Comment by Kindhearted57** [comment]
Thanks you guys a lot!!!!! My problem is solved=)
