### ISSUE TITLE
mfsscripts/favicon.ico: incorrect name; file content is PNG

### ISSUE THREAD

**Issue by onlyjob** [moosefs/moosefs#328]
```
$ file mfsscripts/favicon.ico
mfsscripts/favicon.ico: PNG image data, 16 x 16, 8-bit/color RGBA, non-interlaced
```

Please correct the file name to make it consistent with the content. Thanks.

**Comment by acid-maker** [comment]
We should rather change the content - not the name. I'll prepare new favicon.ico

**Comment by onlyjob** [comment]
Why? IE6 legacy is over. All browsers support PNG these days.
