### ISSUE TITLE
mfsmount does not provide always the last file version

### ISSUE THREAD

**Issue by franciscopaniskaseker** [moosefs/moosefs#330]
I am using on chunkservers:

```bash
moosefs-chunkserver-3.0.109-1.rhsystemd.x86_64
```

and mfsmaster:

```bash
moosefs-master-3.0.105-1.rhsystemd.x86_64
```

Both on CentOS 7 with kernel 5.4.11-1.

I mount the moosefs data using mfsmount in some servers. All of my chunkservers are with load under near zero. I do not have too much files to write, but I will do a lot reads (actually is not a lot today, but will be). Today we are only validating this environment.

Sometimes I can see the softwares that use mounted directory from mfs get different versions of the files. Doing manually sha1 on these files in each server I am seeing thet moosefs chunkservers are taking too much time to update the data.

I have two questions here:

1. Why chunkservers take too much time to update replicated data?
2. It is ok to take some time to update the replicas, but moosefs master must deliver in the mfsmount the last file version, is not right? This is a basic procedure of any remote file system. So I think something is wrong here. 

I am using all default options that come with moosefs rpm packages. And the command to mount in fstab is:

```bash
mfsmount /mnt/mfs/ fuse defaults 0 0
```

I did not find a verbose mode on mfs services to try to debug what is happening. So this is my third question:
3. How set debug mode? I not saw anything in the config files documentation. Maybe there is a systemctl paramenter that I have to configure, I do not know.

**Comment by jSML4ThWwBID69YC** [comment]
Hello, 

Try upgrading the master to 3.0.109 and see if the issue persists. Also, try using mfsfileinfo instead of sha1 on the files. That will give you more information.

**Comment by franciscopaniskaseker** [comment]
Done. I will do a feedback in next days.

**Comment by jSML4ThWwBID69YC** [comment]
Hello @franciscopaniskaseker 

Are you still experiencing the issue after the upgrade?

**Comment by franciscopaniskaseker** [comment]
Hello @jSML4ThWwBID69YC 

Not anymore, but I the problem was due a misconfiguration about mfsmount in one server, so it produced a local data copy and other version on moosefs. I finally found that problem yesterday. 

I think even with different versions between chunk server and master server, everything was ok.

Thank you for all help.
