### ISSUE TITLE
< prefix in mfshdd.cfg leaves chunks behind, related to #327 

### ISSUE THREAD

**Issue by borkd** [moosefs/moosefs#333]
## Have you read through available documentation and open Github issues?

Yes

## Is this a BUG report, FEATURE request, or a QUESTION? Who is the intended audience?

BUG, related to #327 

#### Your moosefs version and its origin (moosefs.com, packaged by distro, built from source, ...).

3.0.109

#### Operating system (distribution) and kernel version.

Debian

#### Hardware / network configuration, and underlying filesystems on master, chunkservers, and clients.

irrelevant

#### How much data is tracked by moosefs master (order of magnitude)?

tens of terabytes

## Describe the problem you observed.

I have noticed that adding a `<` in front of a disk share does not leave the directory structure empty of chunks. Per`man mfshdd.cfg`:
> <      means that all data from this hard drive should be moved to other local hard drives

I checked the directory structure once activity stopped and master reported no undergoal and no overgoal chunks, stating there are 0 chunks in the share prefixed with `<`. Upon examination of the directory there are still thousands of chunks in there, ~16GB worth.

#### Include any warning/errors/backtraces from the system logs

The syslog entries for each disk mentioned in mfshdd.cfg, have different but static NCHUNKS number, and COUNTDOWN increasing, rather than decreasing every hour.

> MFSCS_ID[8331]: on drive '/mount/point/mfs/v3/' NCHUNKS chunk duplicates detected - will remove them in COUNTDOWN hours

##### Suggestion for #327

It appears that fixing the countdown will resolve this issue, but while I am glad that moosefs does not hastily remove duplicates I would even be in favor of artificially slowing down the countdown when errors are detected.

```
MFSCS_1[8331]: read_block_from_chunk: file: /rust/diska/mfs/v3//3D/chunk_00000000002D7C88_00000001.mfs ; block: 287 - crc error (data crc: D2EEC5BA ; check crc: BDE74F62)
MFSCS_1[8331]: move_chunk: file:/rust/diska/mfs/v3//34/chunk_00000000003F239F_00000001.mfs - data read error: EIO (Input/output error)
MFSCS_1[8331]: read_block_from_chunk: file: /rust/diskb/mfs/v3//6E/chunk_000000000040B90B_00000001.mfs ; block: 661 - crc error (data crc: 32EC75DD ; check crc: DB2C2CD1)
MFSCS_1[8331]: test_chunk: file:/rust/diska/mfs/v3//2F/chunk_00000000003C4CDB_00000001.mfs - data read error: EIO (Input/output error)
MFSCS_1[8331]: move_chunk: file:/rust/diska/mfs/v3//2B/chunk_000000000029C82E_00000001.mfs - data read error: EIO (Input/output error)
MFSCS_1[8331]: test_chunk: file:/rust/diskb/mfs/v3//75/chunk_00000000004A819F_00000001.mfs - data read error: EIO (Input/output error)
MFSCS_1[8331]: move_chunk: file:/rust/diska/mfs/v3//35/chunk_00000000004BDB56_00000001.mfs - data read error: EIO (Input/output error)
```

**Comment by chogata** [comment]
The leftover 16GB on your disk are explained by the duplicates - regular chunks will get copied and removed from a `<` disk, duplicates will not, they will still sit there for 168 hours. Your log shows you do have some duplicates on the chunk server. Of course, you can disconnect such a disk from the chunk server without waiting for the duplicates to be removed. 

Can you explain what you meant by the second part, "slowing down the countdown when errors are detected"? Which countdown should be slowed down?

**Comment by borkd** [comment]
As for "slowing down the countdown when errors are detected" - The default of 7 days or 168 hours to get rid of duplicate chunks is a sane default, but hardcoding it should be abandoned, and choice should be given to the cluster admins to adjust it as they see fit for their installation.

https://github.com/moosefs/moosefs/blob/fc8fd1269fd3006a085352705e01803dc0b8f2d4/mfschunkserver/hddspacemgr.c#L1580

- Simple fix would be to simply expose the 7 day TTL as a variable in `mfschunkserver.cfg` for the cluster admins. This TTL could be adjusted based on the perceived cost of maintaining some extra replicas at the expense of marginally increased space utilization.

- Another simple fix, in the spirit of hands-off approach MooseFS tends to offer, would be to also expose a rate multiplier for the countdown, which extends the TTL deadline if the chunkserver itself, or the master indicates a recent spike in chunk I/O errors.

**Comment by onlyjob** [comment]
Yes, timeout should be configurable. Restarting chunkserver resets the counter so one have to wait another week for duplicates to be deleted if (chunk)server is restarted...

**Comment by onlyjob** [comment]
Since timeout is now configurable by `HDD_KEEP_DUPLICATES_HOURS`, I think this issue can be closed.
