### ISSUE TITLE
How to migrate data to new Chunk servers?

### ISSUE THREAD

**Issue by aaafei123** [moosefs/moosefs#34]
Hi all! Here I have a question, pls help!

I want to migrate the mfs cluster servers to new cluster servers(master, metalogger and chunks included)?
How should I do? How to migrate the data from old chunk servers to new chunk servers?

**Comment by zcalusic** [comment]
Hello aaafei123,

As everything's new, the safest would probably be to build the new empty cluster from scratch, then mount both clusters on some machine and just copy/move data from the old instance to the new. After that reconfigure all the clients to point to the new cluster.

Any other procedure would be more complicated. You'd need to copy/move piece by piece of the old cluster to the new one. First master, then metaloggers, then chunkservers, then clients. And you'd need to be very careful during the move.

**Comment by aaafei123** [comment]
hi zcalusic,

thanks for your reply:) I will try it following your advice.  thanks a lot.

**Comment by oxide94** [comment]
Yes, it is one of possible options, but it may be slow.

Another one (but faster) is to add new Chunkservers to the existing instance, wait for everything to rebalance, then mark old servers for removal in `/etc/mfs/mfshdd.cfg` on every Chunkserver (add asterisk (`*`) at the beginning of every entry) and reload Chunkservers' processes.

Then, wait for data to be replicated (it may take quite long, but should be faster than copying everything through one mount.

After data is migrated to new Chunkservers, set up new Master Server (don't run it yet). Then, **stop** old one and copy file `/var/lib/mfs/metadata.mfs` to new machine. Of course you have to change DNS name mfsmaster (or your custom) to a new IP address or use IP address of old Master Server.

At the end run new Master Server - it should properly load `metadata.mfs` file and start. Then Chunkservers will automatically connect to the new machine.


PS: It is a shortened description - if you need more info or have additional questions, please don't hesitate to ask! :)

Best regards,
Peter / MooseFS Team

**Comment by aaafei123** [comment]
@oxide94 thank you very much:)

My MFS current version is v1.6.27, and it has been running for two years. 
Here also some quetions need your help:
1) When set up new Master Server, copy file var/lib/mfs/metadata.mfs to new machine. but on my MFS just have the following files on $MFS_HOME/var/mfs/:
 _changelog.*.mfs,  metadata.mfs.back, metadata.mfs.back.1, metadata.mfs.empty, sessions.mfs and stats.mfs._
Need I copy all files to new machine(new Master Server)?
2) I started the mfscgiserv service on Master Server($MFS_HOME/sbin/mfscgiserv start ),  and visit the URL http://IP:9425 to monitor, but seems the mfscgiserv service cant works well. how to fix it?
3) Can I upgrade the MFS from v1.6.27 to v3.0 when I migrate the old Master to new Master Server? from the docs, I just find the content from v2.0 to v3.0. Here any advices?

Thanks again. 

Best regards, 
Fei

**Comment by oxide94** [comment]
Hi @aaafei123, I'm sorry for late reply.

1. When you stop your Master Server, it will dump `metadata.mfs` file. Unfortunately in such migration there is no possibility to avoid downtime, so you have to stop your MFS Master 1.6 first, then copy `metadata.mfs` to a new machine (and additionally to a safe place and keep for a few days just in case)

2. What does it mean: "mfscgiserv service cant works well."? Could you please provide more details?

3. Yes, you can. The procedure of upgrade MFS 1.6.27 to MFS 3.0 is the same like from 1.6.27 to 2.0 (see MooseFS 2.0 Upgrade Guide on [this website](https://moosefs.com/documentation/moosefs-3-0.html) - especially Paragraph 1.1 "Introduction / 1.1 Backing-up data and configuration files" and Chapter 3 "MooseFS 1.6.27-5 to 2.0.x CE
upgrade". Please don't follow paragraph 1.2.2 "Repository Branches", because it is a bit outdated. Info about repositories is [here](https://moosefs.com/download.html)). **Please remember to do a backup of `metadata.mfs` after stopping your Master as I wrote above.**

In case of any further questions, please don't hesitate to ask!

Best regards,
Peter / MooseFS Team

**Comment by aaafei123** [comment]
@oxide94 Peter, thank you very much!

#2 mfscgiserv service works fine now. 

I will follow your advices to upgrade our MFS.  I will email you if there are any issues during upgrading. Hmmm...Can you give me your email address?

Thanks a lot.

Best regards,
Fei

**Comment by oxide94** [comment]
@aaafei123 Please write at support@moosefs.com. It will create a support ticket then. I think it will be the best way :)

**Comment by aaafei123** [comment]
@oxide94 Hi Peter, disturb you again.

if my MFS goal=1, can I REMOVE the old ChunkServer?

thanks.

Best regards,
Fei

**Comment by oxide94** [comment]
Hi @aaafei123,

if all conditions below are met / fulfilled:

- mentioned Chunkserver has **all** HDDs marked for removal (their paths in `/etc/mfs/mfshdd.cfg` are preceded by an asterisk (`*`) sign) **and**
- all Chunks are replicated (i.e. in MFS CGI, on INFO tab after switching to **regular** view (see screenshot) in chunk state matrix there are neither undergoal, nor missing chunks)
<img width="655" alt="screen shot 2017-01-17 at 7 03 41 pm" src="https://cloud.githubusercontent.com/assets/4892057/22033250/0f041da4-dce8-11e6-99c4-7f6a7933124d.png">

then - yes, you can safely disconnect it.

Please upload a screenshot of your chunks state matrix (both `all` and `regular`) before disconnecting it, I can verify the situation.

By the way, we **strongly** recommend to use goal greater than 1, because if you use goal = 1, in case of any failure (disk failure, Chunkserver failure, ...) you loose your data...

Best regards,
Peter / MooseFS Team

**Comment by aaafei123** [comment]
@oxide94 Hi Peter,
pls check the screenshot below, thanks!
![mfs_status](https://cloud.githubusercontent.com/assets/6510602/22090353/013d8da0-de2c-11e6-8940-54e16130f80a.jpg)

**Comment by oxide94** [comment]
@aaafei123: Could you please change the view to "regular" and then send the screenshot again?

**Comment by aaafei123** [comment]
@oxide94 ok, pls check below, thanks a lot:)

![mfs_status2](https://cloud.githubusercontent.com/assets/6510602/22091159/6d7aeca2-de30-11e6-9794-85940de17b76.jpg)

**Comment by oxide94** [comment]
@aaafei123 Ok, so now, if you have **all** HDDs (on the chunkserver you want to disconnect) marked for removal and situation as on both screenshoths above - yes, you can safely disconnect this specific Chunkserver. I can finally confirm it if you could send me last screenshot from "SERVERS" tab - on the list, next to the specific Chunkserver you want to disconnect, it's whole space should be listed in table's last column (`'marked for removal' hdd space`).

Best regards,
Peter / MooseFS Team

**Comment by aaafei123** [comment]
@oxide94 The “SERVER”tab screenshot:

![mfs_servertab](https://cloud.githubusercontent.com/assets/6510602/22091941/3ac01012-de35-11e6-8fbc-c3f75816c1df.jpg)

**Comment by oxide94** [comment]
Hi @aaafei123,

as I can see on the last screenshot, you haven't marked HDDs for removal. If you want to disconnect a chunkserver from the instance safely, please first of all mark all HDDs on it "for removal". As I wrote a few comments above, to do so, please put and asterisk sign (`*`) at the beginning of all HDDs paths in `/etc/mfs/mfshdd.cfg` (or `/etc/mfshdd.cfg`), so it will looks like:

```
*/mnt/chunk1
*/mnt/chunk2
*/mnt/chunk3
...
```

and then reload the chunkserver process (`mfschunkserver reload`).

After doing so, your SERVERS tab in MFS CGI should show green bar in "marked for removal" column:
<img width="334" alt="screen shot 2017-01-19 at 7 19 16 pm" src="https://cloud.githubusercontent.com/assets/4892057/22119554/462c7b1a-de7c-11e6-9809-3f684e9da49e.png">
(here should be a green bar).

Then you have to wait for chunks to replicate over the rest of Chunkservers.

After replications are finished ( = no undergoal or endangered chunks in "regular space matrix"), you can safely disconnect this chunkserver.

This is the supported procedure. Please let me know if you want me to clarify anything.

Best regards,
Peter / MooseFS Team

**Comment by aaafei123** [comment]
@oxide94 According to the steps(mark hdds for removal and reload the chunkserver), now the status is:

**info tab:**
![info-tab](https://cloud.githubusercontent.com/assets/6510602/22171711/eb764274-dfce-11e6-901e-2e8a01494c78.png)

**servers tab:**
![servers](https://cloud.githubusercontent.com/assets/6510602/22171712/f83efda2-dfce-11e6-94cb-e7d3857d93f0.png)

**disks tab:**
![disk-tab](https://cloud.githubusercontent.com/assets/6510602/22171713/fe9da0f4-dfce-11e6-8713-229d1797abd8.png)

there any issues?
thanks a lot~

Best regards,
Fei

**Comment by oxide94** [comment]
@aaafei123: Could you please also send a current screenshot of "regular" view of INFO tab?

Best regards,
Peter / MooseFS Team

**Comment by aaafei123** [comment]
@oxide94 ok, pls check below, thanks:)
![info-regulartab](https://cloud.githubusercontent.com/assets/6510602/22173092/965d15d6-dff3-11e6-890b-72da9ae0660d.png)

**Comment by oxide94** [comment]
Hi @aaafei123,
if situation looks like on presented screenshots, chunks from this marked for removal Chunkserver are replicated and you can safely stop the Chunkserver process on it.

Best regards,
Peter / MooseFS Team

**Comment by aaafei123** [comment]
@oxide94 Hi Peter, I have stopped the chunkserver which marked for removal. And I upload the screenshots for reference, and pls help to check everything are ok, thanks again.

info tab(all):
![mfs_infoall](https://cloud.githubusercontent.com/assets/6510602/22240907/0f8c938a-e258-11e6-8182-40eead27dfa3.jpg)

info(regular):
![mfs_inforegular](https://cloud.githubusercontent.com/assets/6510602/22240934/2c638aea-e258-11e6-80cc-c71a90e3ab17.jpg)

servers:
![mfs_servertab2](https://cloud.githubusercontent.com/assets/6510602/22240952/44752030-e258-11e6-9b05-104e6235d9cd.jpg)

disks:
![mfs_disk2](https://cloud.githubusercontent.com/assets/6510602/22240994/70b148d6-e258-11e6-9734-1c45971b4b01.jpg)

**Comment by oxide94** [comment]
Hi @aaafei123,

I'm sorry for so late reply - I somehow missed your last message. Actually there should be no "endangered" chunks after disconnection (and after properly marking for removal HDDs on a Chunkserver which is going to be disconnected).

I hope the situation is stable now and all data is replicated, but probably it took very long (because of old MooseFS 1.6 replication limit and mechanisms.

Anyway - I strongly recommend to upgrade your instance to MooseFS 2.0 or MooseFS 3.0 (you don't have to migrate anything, you can do an upgrade in-place on existing servers).

Best regards,
Peter / MooseFS Team

**Comment by aaafei123** [comment]
@oxide94 Hi peter, thanks a lot, everything is ok now:)
Next step, I plan to upgrade the MFS to v3.0
if there any issues during upgrading, I will disturb you again. thanks again.

Best regards,
Fei

**Comment by oxide94** [comment]
Hi @aaafei123,

great to hear that! :) No problem, ask anything you need!

For now I'm closing this issue, of course feel free to create a new one in case of any issues during the upgrade. Please follow the upgrade guide I mentioned in point 3 of this comment: https://github.com/moosefs/moosefs/issues/34#issuecomment-271271751.

Best regards,
Peter / MooseFS Team

**Comment by GYUMO** [comment]
> @oxide94 thank you very much:)
> 
> My MFS current version is v1.6.27, and it has been running for two years.
> Here also some quetions need your help:
> 
> 1. When set up new Master Server, copy file var/lib/mfs/metadata.mfs to new machine. but on my MFS just have the following files on $MFS_HOME/var/mfs/:
>    _changelog.*.mfs,  metadata.mfs.back, metadata.mfs.back.1, metadata.mfs.empty, sessions.mfs and stats.mfs._
>    Need I copy all files to new machine(new Master Server)?
> 2. I started the mfscgiserv service on Master Server($MFS_HOME/sbin/mfscgiserv start ),  and visit the URL http://IP:9425 to monitor, but seems the mfscgiserv service cant works well. how to fix it?
> 3. Can I upgrade the MFS from v1.6.27 to v3.0 when I migrate the old Master to new Master Server? from the docs, I just find the content from v2.0 to v3.0. Here any advices?
> 
> Thanks again.
> 
> Best regards,
> Fei

hai. I have a problem, when i change the master server. should I mark all chunk server to be disconnected. I mean, should I disconnect all the chunk server firstly, then copy metadata.mfs to new master server. Finally,change the configuration of all the chunk server to link to the new master node.
Thank you

**Comment by aaafei123** [comment]
> > @oxide94 thank you very much:)
> > My MFS current version is v1.6.27, and it has been running for two years.
> > Here also some quetions need your help:
> > 
> > 1. When set up new Master Server, copy file var/lib/mfs/metadata.mfs to new machine. but on my MFS just have the following files on $MFS_HOME/var/mfs/:
> >    _changelog.*.mfs,  metadata.mfs.back, metadata.mfs.back.1, metadata.mfs.empty, sessions.mfs and stats.mfs._
> >    Need I copy all files to new machine(new Master Server)?
> > 2. I started the mfscgiserv service on Master Server($MFS_HOME/sbin/mfscgiserv start ),  and visit the URL http://IP:9425 to monitor, but seems the mfscgiserv service cant works well. how to fix it?
> > 3. Can I upgrade the MFS from v1.6.27 to v3.0 when I migrate the old Master to new Master Server? from the docs, I just find the content from v2.0 to v3.0. Here any advices?
> > 
> > Thanks again.
> > Best regards,
> > Fei
> 
> hai. I have a problem, when i change the master server. should I mark all chunk server to be disconnected. I mean, should I disconnect all the chunk server firstly, then copy metadata.mfs to new master server. Finally,change the configuration of all the chunk server to link to the new master node.
> Thank you

yes, you must disconnect all the chunk servers firstly.

**Comment by GYUMO** [comment]
Thank you very much
 



------------------ 原始邮件 ------------------
发件人: "isharing"<notifications@github.com>; 
发送时间: 2019年6月30日(星期天) 下午5:02
收件人: "moosefs/moosefs"<moosefs@noreply.github.com>; 
抄送: "2994899095"<2994899095@QQ.COM>; "Comment"<comment@noreply.github.com>; 
主题: Re: [moosefs/moosefs] How to migrate data to new Chunk servers? (#34)



  
@oxide94 thank you very much:)
 My MFS current version is v1.6.27, and it has been running for two years.
 Here also some quetions need your help:
  
When set up new Master Server, copy file var/lib/mfs/metadata.mfs to new machine. but on my MFS just have the following files on $MFS_HOME/var/mfs/:
 changelog.*.mfs,  metadata.mfs.back, metadata.mfs.back.1, metadata.mfs.empty, sessions.mfs and stats.mfs.
 Need I copy all files to new machine(new Master Server)?
 
I started the mfscgiserv service on Master Server($MFS_HOME/sbin/mfscgiserv start ),  and visit the URL http://IP:9425 to monitor, but seems the mfscgiserv service cant works well. how to fix it?
 
Can I upgrade the MFS from v1.6.27 to v3.0 when I migrate the old Master to new Master Server? from the docs, I just find the content from v2.0 to v3.0. Here any advices?
  
Thanks again.
 Best regards,
 Fei
  
hai. I have a problem, when i change the master server. should I mark all chunk server to be disconnected. I mean, should I disconnect all the chunk server firstly, then copy metadata.mfs to new master server. Finally,change the configuration of all the chunk server to link to the new master node.
 Thank you
  
yes, you must disconnect all the chunk servers firstly.

**Comment by GYUMO** [comment]
> 嗨@ aaafei123，
> 
> 很高兴听到！:)没问题，问你需要什么！
> 
> 目前我正在关闭这个问题，当然可以在升级过程中出现任何问题时自由创建一个新问题。请按照我在本评论[第](https://github.com/moosefs/moosefs/issues/34#issuecomment-271271751) 3点中提到的升级指南进行操作：[＃34（评论）](https://github.com/moosefs/moosefs/issues/34#issuecomment-271271751)。
> 
> 最诚挚的问候，
> Peter / MooseFS团队
but when I disconnect every server，I can't find  metadata.mfs, I just find some file like you

**Comment by GYUMO** [comment]
but when I disconnect every server，I can't find  metadata.mfs, I just find some file like you

**Comment by GYUMO** [comment]
but when I disconnect every server，I can't find  metadata.mfs, I just find some file like / var / mfs /：changelog。*。mfs，metadata.mfs.back，metadata.mfs.back.1，metadata.mfs.empty，sessions.mfs 。 I am sure I disconnect every chunkserver

**Comment by GYUMO** [comment]
但是当我断开每个服务器时，我找不到metadata.mfs，我只找到一些文件，如/ var / mfs /:changelog.*.mfs,metadata.mfs.back,metadata.mfs.back.1,metadata。 mfs.empty，sessions.mfs。我确定我断开了每个chunkserver

**Comment by GYUMO** [comment]
but when I disconnect every chunkserver, and metalogger server. I can justs find / var / mfs /:changelog.*.mfs,metadata.mfs.back,metadata.mfs.back.1,metadata。 mfs.empty，sessions.mfs。
I can't find metadata.mfs

**Comment by aaafei123** [comment]
> but when I disconnect every chunkserver, and metalogger server. I can justs find / var / mfs /:changelog.*.mfs,metadata.mfs.back,metadata.mfs.back.1,metadata。 mfs.empty，sessions.mfs。
> I can't find metadata.mfs

you must stop your mfs master server firstly(#mfsmaster stop), and then you can see the metadata.mfs file.
