### ISSUE TITLE
[question] compatibility with macOS Catalina (10.15)

### ISSUE THREAD

**Issue by eleaner** [moosefs/moosefs#346]
Hi,

is there an issue with compatibility?
The moosefs.com says that macOS packages are compatible only up to 10.14

<img width="468" alt="image" src="https://user-images.githubusercontent.com/5169203/76154566-7c209780-60d6-11ea-8899-5960e030e19a.png">

I am afraid to upgrade

**Comment by acid-maker** [comment]
Just compiled from sources and it works fine on my 10.15.3.

**Comment by acid-maker** [comment]
And now also installed from packages - also works fine on 10.15.3.

**Comment by eleaner** [comment]
thank you, 
so that's just the info on the web site

**Comment by eleaner** [comment]
might be worth updating it

**Comment by pkonopelko** [comment]
Updated
