### ISSUE TITLE
3.0.112: sometimes failing "mfstest_clocks"

### ISSUE THREAD

**Issue by onlyjob** [moosefs/moosefs#351]
A minor thing: `mfstest_clocks` test fails spuriously sometimes (but not all the time).

```
FAIL: mfstest_clocks
====================

Starting test: monotonic_clocks
used method: clock_gettime
second: 0.013054 ; 13054 ; 13054489
Assertion 'en<0.012' failed:
'en' == 0.0130538610, '0.012' == 0.0120000000
Assertion 'enusec<12000' failed:
'enusec' == 13054, '12000' == 12000
Assertion 'ennsec<12000000' failed:
'ennsec' == 13054489, '12000000' == 12000000
50%: Checks: 6, Failures: 3
FAIL mfstest_clocks (exit status: 1)
```

**Comment by acid-maker** [comment]
My question is - what operating system do you use? I suppose it is Linux? Kernel version? Is it VM or physical machine?

Just checked my Mac OS X and it always fails there. It looks that both usleep and nanosleep often put the process to much longer sleep than expected. In case of Mac OS X it is 14.5ms.

I've even prepared simple program:

```
#include <unistd.h>

int main(int argc,char *argv[]) {
	int i;
	for (i=0 ; i<100 ; i++) {
		usleep(10000);
	}
	return 0;
}
```

compiled it and run it:

```
$ time ./x

real	0m1.453s
user	0m0.001s
sys	0m0.002s
```

It took 1.45 seconds and it should be little more than 1 second. It looks like (at least on my Mac OS X) usleep and nanosleep are broken (or not very precise).

But on Linux it looks more correct:

(Ubuntu with kernel 4.15 and 5.3):

```
time ./x

real	0m1.009s
user	0m0.003s
sys	0m0.000s
```

(Centos 7 with kernel 3.10):

```
time ./x

real	0m1.006s
user	0m0.000s
sys	0m0.001s
```

I don't think that it is a problem that usleep is not very precise on some systems. We do not use it to measure time - usually only to wait a bit in some threads between tasks. Hence I'll increase tolerance in this check.

**Comment by onlyjob** [comment]
Debian GNU+Linux amd64 (x86_64), Linux 5.4.19-1~bpo10+1, physical machine.

Test never failed before but given the narrow timing it might be a one time thing.
Subsequent build finished without errors.

Nevertheless it would be great if test could be made more reliable... Thanks.

**Comment by onlyjob** [comment]
Looks good/better, thanks.

**Comment by onlyjob** [comment]
3.0.115 just failed again as follows:

```
==========================================
   MFS 3.0.115: mfstests/test-suite.log
==========================================
# TOTAL: 4
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
.. contents:: :depth: 2
FAIL: mfstest_clocks
====================
Starting test: monotonic_clocks
used method: clock_gettime
second: 0.022788 ; 22788 ; 22787613 ; 22787
Assertion 'en<0.02' failed: 
'en' == 0.0227875090, '0.02' == 0.0200000000
Assertion 'enusec<20000' failed: 
'enusec' == 22788, '20000' == 20000
Assertion 'ennsec<20000000' failed: 
'ennsec' == 22787613, '20000000' == 20000000
Assertion 'wcenusec<20000' failed: 
'wcenusec' == 22787, '20000' == 20000
50%: Checks: 8, Failures: 4
FAIL mfstest_clocks (exit status: 1)
============================================================================
Testsuite summary for MFS 3.0.115
============================================================================
# TOTAL: 4
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
```

Re-trying the build succeeded.

**Comment by chogata** [comment]
We changed the test to run several times and check against the average - should help. Commit 4140927f0129fa3626eb02dc7acb3f991bdad454

**Comment by onlyjob** [comment]
Awesome, thanks. So far I have not seen any more spurious failures of this test in my CI infrastructure. Closing.
