### ISSUE TITLE
CGI: Warning: counters may not be valid - disconnections in progress

### ISSUE THREAD

**Issue by onlyjob** [moosefs/moosefs#356]
Few releases back CGI/Info page started to show "Warning: counters may not be valid - disconnections in progress" almost persistently: refreshing the page in browser make the warning disappear only to re-appear on next refresh (or several) only some seconds later.

Warning is there almost all the time, with all chunkservers working well and stable for a long time.

Otherwise cluster works properly so it appears to be a minor issue.

**Comment by chogata** [comment]
I know you use MooseFS in a production environment, so I'm not sure if you will be able to do it, but if it is possible, the best test to see what actually causes those warnings to show up would be:

1) Restart your master, wait an hour and see if those messages still appear after all the chunk servers connected and system is working as usual.
2) If yes, apply the patch for the commit mentioned here, start the patched master and see, if those messages still appear then or not.

**Comment by onlyjob** [comment]
Thanks, Agata. I've already did No.1 before submitting this bug report. I should be able to introduce the patch over the weekend to test. I'll report how it goes. :)

**Comment by onlyjob** [comment]
The problem is fixed. Many thanks for quick response -- much appreciated!
