### ISSUE TITLE
mfsclient errors including high packet travel time, and ebusy. 

### ISSUE THREAD

**Issue by jSML4ThWwBID69YC** [moosefs/moosefs#360]
## Is this a BUG report, FEATURE request, or a QUESTION? Who is the indended audience?

Unsure

#### Your moosefs version and its origin (moosefs.com, packaged by distro, built from source, ...).

Version: 3.0.112_1
Built from the FreeBSD ports tree. 
5x chunk servers
1x Master
1x Metadata 
3x Clients

10Gbe network using LACP with two links per server. MTU is set to 9198.

I'm using HEPT for the kern.timecounter.hardware. All servers run NTP and are in sync. 

#### How much data is tracked by moosefs master (order of magnitude)?

 - All fs objects: 10778345
 - Total space: 95TB
 - Free space: 90TB
 - RAM used: 3.8GB
 - last metadata save duration: ~3.9s

## Describe the problem you observed.
The mfsclient shows errors about packet travel time, or ebusy messages. I can't replicate any lag or delay on the network using Smokeping, nor find a cause for the ebusy errors.

#### Can you reproduce it? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

It happens randomly, though several times a day, generally a bunch at once. Higher loads seem to cause it more often, but network and server resources remain underutilized. 

#### Include any warning/errors/backtraces from the system logs

Here are the logs from two different clients (different machines) from startup to now. 
```
May  2 04:05:26 services00 mfsmount[78555]: monotonic clock function: clock_gettime
May  2 04:05:26 services00 mfsmount[78555]: monotonic clock speed: 158294 ops / 10 mili seconds
May  2 04:05:27 services00 mfsmount[51269]: my st_dev: 3976265474
May  2 04:05:27 services00 mfsmount[64722]: my st_dev: 3976265475
May  2 04:05:27 services00 mfsmount[78555]: my st_dev: 3976265476
May  2 04:05:58 services00 mfsmount[51269]: sysctl(kern.proc.filedesc) error: EBUSY (Device or resource busy)
May  2 04:05:58 services00 syslogd: last message repeated 1 times
May  2 04:05:58 services00 mfsmount[64722]: sysctl(kern.proc.filedesc) error: EBUSY (Device or resource busy)
May  2 04:05:58 services00 mfsmount[78555]: sysctl(kern.proc.filedesc) error: EBUSY (Device or resource busy)
May  2 04:05:58 services00 syslogd: last message repeated 1 times
May  2 06:00:09 services00 mfsmount[51269]: sysctl(kern.proc.filedesc) error: EBUSY (Device or resource busy)
May  2 06:15:09 services00 mfsmount[78555]: sysctl(kern.proc.filedesc) error: EBUSY (Device or resource busy)
May  2 06:15:09 services00 mfsmount[51269]: sysctl(kern.proc.filedesc) error: EBUSY (Device or resource busy)
May  2 06:15:09 services00 syslogd: last message repeated 1 times
May  2 06:15:09 services00 mfsmount[64722]: sysctl(kern.proc.filedesc) error: EBUSY (Device or resource busy)
May  2 07:00:01 services00 mfsmount[64722]: high packet travel time between client and master (0.869514s) - ignoring in time sync

Second client messages: 
May  2 04:06:38 web00 mfsmount[10884]: my st_dev: 3976265477
May  2 04:06:39 web00 mfsmount[19343]: my st_dev: 3976265478
May  2 04:06:39 web00 mfsmount[28015]: my st_dev: 3976265479
May  2 04:06:39 web00 mfsmount[45395]: my st_dev: 3976265480
May  2 04:07:09 web00 mfsmount[96247]: sysctl(kern.proc.filedesc) error: EBUSY (Device or resource busy)
May  2 04:07:09 web00 mfsmount[28015]: sysctl(kern.proc.filedesc) error: EBUSY (Device or resource busy)
May  2 12:00:01 web00 mfsmount[76465]: high packet travel time between client and master (0.104160s) - ignoring in time sync
May  2 12:00:01 web00 mfsmount[28015]: high packet travel time between client and master (0.513899s) - ignoring in time sync
May  2 12:00:01 web00 mfsmount[19343]: high packet travel time between client and master (0.115788s) - ignoring in time sync
May  2 12:00:01 web00 mfsmount[10884]: high packet travel time between client and master (0.287635s) - ignoring in time sync

```

The question is where are these errors coming from and how do I fix it? Secondly, why is there such a high packet delay reported? The average RTT time from smokeping using 9000 byte packets is 150 μs, a big difference from the 10ms+ MooseFS is reporting.

**Comment by chogata** [comment]
1. EBUSY
This is something you can safely ignore. A little explanation, why: we need to check periodically which directories are current working directories anywhere in the whole MooseFS instance, so if they get deleted (which can happen in a network file system), their inodes cannot be re-used as long as they remain CWDs. Now, in FreeBSD, if this occurs - an inode that is still a CWD of some long forgotten process or shell is re-used - nothing really bad happens. On Linux a lot of bad stuff happens ;) But since it's generally not a good idea to allow this situation - we are safeguarding all OSes, not only Linux, from reusing deleted CWDs' inodes.
Now, for some reason, from time to time the operation to get CWD info on FreeBSD fails. We don't know why and we can't replicate it reliably enough to be able to trace the problem, which is most probably a FreeBSD problem anyway. But if it fails once and works the next 100 times, it's not really a problem for MooseFS. Hence the advice to just ignore it. (BTW, FreeBSD man for sysctl doesn't even list EBUSY as a possible error for that command... go figure ;) ).

2. packet travel time
I see in the two logs you provided, that it always happens on the full hour. Did it ever occur at a different time? High travel time can only happen in two cases: one, if there is a problem with your network and the packet travel time is physically high, two, if master is very busy and "has no time to respond". If it only happens at full hour, I'm guessing the process of saving metadata is for some reason slowing it down. It should not, because master is forking before it starts the save, so the main process is not swamped with local disk i/o, but maybe for some reason this fork takes a long time on your instance? You can take a look at your master during that time and see what is happening there.

**Comment by jSML4ThWwBID69YC** [comment]
Hello, 

Thank you for the explanation. I won't worry about the ebusy messages anymore. 

I've checked the logs over the last week for each client server, and the packet travel time error is always at the top of the hour, or within a minute of it. It does not happen every hour and appears to be quite random. 

The mfs master server is dedicated hardware with only MoooseFS and node_exporter from the Prometheus project running on it. I can send you the graphs from our monitoring, but all its showing me is that the system is idle. 

Here's the output of the mfs-master log for May fourth, plus client logs showing the packet error. All times are UTC. I've stripped out non relevant log data. 

```
May  4 00:00:04 mfs-master mfsmaster[1894]: child finished
May  4 00:00:04 mfs-master mfsmaster[1894]: store process has finished - store time: 3.382
May  4 00:01:21 mfs-master mfsmaster[1894]: structure check loop
May  4 01:00:04 mfs-master mfsmaster[1894]: child finished
May  4 01:00:04 mfs-master mfsmaster[1894]: store process has finished - store time: 3.388
May  4 01:50:35 mfs-master mfsmaster[1894]: structure check loop
May  4 02:00:04 mfs-master mfsmaster[1894]: child finished
May  4 02:00:04 mfs-master mfsmaster[1894]: store process has finished - store time: 3.448
May  4 02:45:12 mfs-master mfsmaster[1894]: structure check loop
May  4 03:00:05 mfs-master mfsmaster[1894]: child finished
May  4 03:00:05 mfs-master mfsmaster[1894]: store process has finished - store time: 3.828
May  4 03:39:50 mfs-master mfsmaster[1894]: structure check loop
May  4 04:00:05 mfs-master mfsmaster[1894]: child finished
May  4 04:00:05 mfs-master mfsmaster[1894]: store process has finished - store time: 4.042
May  4 04:34:27 mfs-master mfsmaster[1894]: structure check loop
May  4 05:00:04 mfs-master mfsmaster[1894]: child finished
May  4 05:00:04 mfs-master mfsmaster[1894]: store process has finished - store time: 3.462
May  4 05:29:04 mfs-master mfsmaster[1894]: structure check loop
May  4 06:00:05 mfs-master mfsmaster[1894]: child finished
May  4 06:00:05 mfs-master mfsmaster[1894]: store process has finished - store time: 3.934
May  4 06:23:41 mfs-master mfsmaster[1894]: structure check loop
May  4 07:00:04 mfs-master mfsmaster[1894]: child finished
May  4 07:00:04 mfs-master mfsmaster[1894]: store process has finished - store time: 3.480
May  4 07:18:18 mfs-master mfsmaster[1894]: structure check loop
May  4 08:00:04 mfs-master mfsmaster[1894]: child finished
May  4 08:00:04 mfs-master mfsmaster[1894]: store process has finished - store time: 3.510
May  4 08:12:55 mfs-master mfsmaster[1894]: structure check loop
May  4 09:00:04 mfs-master mfsmaster[1894]: child finished
May  4 09:00:04 mfs-master mfsmaster[1894]: store process has finished - store time: 3.418
May  4 09:07:32 mfs-master mfsmaster[1894]: structure check loop
May  4 10:00:04 mfs-master mfsmaster[1894]: child finished
May  4 10:00:04 mfs-master mfsmaster[1894]: store process has finished - store time: 3.372
May  4 10:02:10 mfs-master mfsmaster[1894]: structure check loop
May  4 11:00:04 mfs-master mfsmaster[1894]: child finished
May  4 11:00:04 mfs-master mfsmaster[1894]: store process has finished - store time: 3.393
May  4 11:51:24 mfs-master mfsmaster[1894]: structure check loop
May  4 12:00:05 mfs-master mfsmaster[1894]: child finished
May  4 12:00:05 mfs-master mfsmaster[1894]: store process has finished - store time: 3.615
May  4 12:46:01 mfs-master mfsmaster[1894]: structure check loop
May  4 13:00:04 mfs-master mfsmaster[1894]: child finished
May  4 13:00:04 mfs-master mfsmaster[1894]: store process has finished - store time: 3.320
May  4 13:40:38 mfs-master mfsmaster[1894]: structure check loop
May  4 14:00:04 mfs-master mfsmaster[1894]: child finished
May  4 14:00:04 mfs-master mfsmaster[1894]: store process has finished - store time: 3.367
May  4 14:35:15 mfs-master mfsmaster[1894]: structure check loop
May  4 15:00:04 mfs-master mfsmaster[1894]: child finished
May  4 15:00:04 mfs-master mfsmaster[1894]: store process has finished - store time: 3.400
May  4 15:29:52 mfs-master mfsmaster[1894]: structure check loop
May  4 16:00:04 mfs-master mfsmaster[1894]: child finished
May  4 16:00:04 mfs-master mfsmaster[1894]: store process has finished - store time: 3.385
May  4 16:24:30 mfs-master mfsmaster[1894]: structure check loop
May  4 17:00:04 mfs-master mfsmaster[1894]: child finished
May  4 17:00:04 mfs-master mfsmaster[1894]: store process has finished - store time: 3.455
May  4 17:19:07 mfs-master mfsmaster[1894]: structure check loop
May  4 18:00:04 mfs-master mfsmaster[1894]: child finished
May  4 18:00:04 mfs-master mfsmaster[1894]: store process has finished - store time: 3.476
May  4 18:13:44 mfs-master mfsmaster[1894]: structure check loop
May  4 19:00:04 mfs-master mfsmaster[1894]: child finished
May  4 19:00:04 mfs-master mfsmaster[1894]: store process has finished - store time: 3.518
May  4 19:08:21 mfs-master mfsmaster[1894]: structure check loop
May  4 20:00:04 mfs-master mfsmaster[1894]: child finished
May  4 20:00:04 mfs-master mfsmaster[1894]: store process has finished - store time: 3.242
May  4 20:02:58 mfs-master mfsmaster[1894]: structure check loop
May  4 21:00:04 mfs-master mfsmaster[1894]: child finished
May  4 21:00:04 mfs-master mfsmaster[1894]: store process has finished - store time: 3.477
```

Client logs
```
May  4 15:00:01 web00 mfsmount[85885]: high packet travel time between client and master (0.370737s) - ignoring in time sync
May  4 15:00:01 web00 mfsmount[10884]: high packet travel time between client and master (0.342231s) - ignoring in time sync
```
```
May  4 03:00:01 web02 mfsmount[66118]: high packet travel time between client and master (0.796406s) - ignoring in time sync
May  4 09:00:01 web02 mfsmount[84726]: high packet travel time between client and master (0.560176s) - ignoring in time sync
May  4 15:00:01 web02 mfsmount[34909]: high packet travel time between client and master (0.410569s) - ignoring in time sync
May  4 20:00:01 web02 mfsmount[66118]: high packet travel time between client and master (0.997019s) - ignoring in time sync
```
```
May  4 07:00:01 services00 mfsmount[64722]: high packet travel time between client and master (1.230679s) - ignoring in time sync
```
There does not appear to be any correlation between the the mfs-master and mfs-client logs. Is there a different log I should be looking at? 

The mfsmaster.cfg file had 'LOCK_MEMORY = 0' set. I've changed it back to 1, and restarted the mfs-master. I'll report back if that changes anything. 

Thank you.

**Comment by xandrus** [comment]
Hi,

By the way.
Can you try to switch back to MTU 1500?
Just for the test.

I know that sometimes bonding and jumbo frames can cause a lot of problems.

**Comment by jSML4ThWwBID69YC** [comment]
Hello @chogata 

I changed the 'LOCK_MEMORY = 0' to 'LOCK_MEMORY = 1' and the high packet travel time messages have disappeared. At least I've not seen them since the change. Thank you for pointing out the cause. 

Hello @xandrus 
Should I switch it back on a single client, or the entire network? A client I can do, the full network would be a bit harder. Can you recommend a test to see if there is an issue using mtu 9198 over lacp? 

The only messages from mfsmount left are these:  
```
May  5 00:00:56 web02 mfsmount[43462]: no sustained stats for node: 3131146 - using defaults
May  5 00:00:56 web02 mfsmount[43462]: no sustained stats for node: 3131485 - using defaults
May  5 04:08:02 web02 mfsmount[54641]: no sustained stats for node: 822056 - using defaults
May  5 15:33:46 web02 mfsmount[43462]: no sustained stats for node: 2769923 - using defaults
May  5 15:34:17 web02 mfsmount[43462]: no sustained stats for node: 2085916 - using defaults
May  6 04:11:48 web02 mfsmount[54641]: no sustained stats for node: 4596660 - using defaults
```
They come in large groups all at once. I assumed those are informational, and do not indicate an error? 

Thank you for all the help.

**Comment by chogata** [comment]
LOCK_MEMORY is an option that should not, in general, be overused. It was designed for situations when on the same machines that serve for MooseFS storage some other processes are also run AND those other processes might possibly exhaust the machines' RAM. So that, if there is not enough physical RAM for everybody, MooseFS components are not the ones that will be "swapped out". But the option has consequences, one of them being that the system will no longer allocate RAM in "lazy way" when it is on and that sometimes is not a desired effect. So, unless your MooseFS shares machines with some kind of RAM-exhausting system (data computing or video serving for example), you should not turn it on. And most of the time, if at all, you turn it on on chunk servers, not on the master. The master should, if at all possible, just have its own dedicated machine that does (almost) nothing else.

**Comment by jSML4ThWwBID69YC** [comment]
Thank you @chogata 

Turning off lock_memory resolved the packet errors. Closing issue.
