### ISSUE TITLE
Compilation failed on musl. 3.0.113

### ISSUE THREAD

**Issue by uu** [moosefs/moosefs#366]
Hello, compilation failure in nbd subsystem on alpine (gcc 9.3.0).
Entire build log is attached. Thank you.
[mfs-3.0.113-failed.txt](https://github.com/moosefs/moosefs/files/4617924/mfs-3.0.113-failed.txt)

**Comment by chogata** [comment]
Please, let us know if the fix solved this problem for you.

**Comment by uu** [comment]
Applied & confirmed:)

![image](https://user-images.githubusercontent.com/95994/81813569-4e215e80-9530-11ea-91fa-2dfeed29da67.png)

Thank you!
