### ISSUE TITLE
chunkserver often fails to save chunkdb on F2FS

### ISSUE THREAD

**Issue by onlyjob** [moosefs/moosefs#367]
F2FS-formatted devices often being re-scanned on chunkserver restart. For whatever reason chunkserver often fails to save chunksdb to F2FS file system while _ext4_-formatted devices on the same chunk/server do not exhibit any problems.

**Comment by chogata** [comment]
The `.chunkdb` file is written with a simple open/write/close sequence, no magic here, so no reason to save it on one fs and not save it on another, unless the fs is really faulty. But there are some conditions in which `.chunkdb` will not be saved at all. For example, when you have some duplicates on a particular disk, it will not be saved for this disk. Basically, `.chunkdb` is a helper mechanism to start up the system faster, but only for a 'perfect state' system. So any abnormal situation (disk with duplicates, disk marked as faulty, for removal etc.) will cause the file NOT to be written at all.

**Comment by onlyjob** [comment]
That's all nice but I have observed this behaviour long enough (on different chunkservers) to report is as anomaly. I don't know _why_ is this happening and what's the significance of _f2fs_ comparing to _ext4_ in regards to saving `.chunkdb`. I doubt that _f2fs_ have greater probability of having duplicate chunks so the problem must due to something else.

**Comment by chogata** [comment]
OK, we don't have much experience with f2fs, we'll test it and see if we can come up with something.

**Comment by onlyjob** [comment]
New year, new distro, new kernel, new release of MooseFS and I no longer observe this problem.

Closing, thanks.
