### ISSUE TITLE
Mfsmaster terminates itself if metadata save child process is not finished before a next try of metadata save.

### ISSUE THREAD

**Issue by kopaczew** [moosefs/moosefs#369]
**BUG report**

Mfsmaster terminates itself if metadata save child process is not finished before a next try of metadata save.

#### MFS
- **version:** 3.0.113
- **source:** rpm package (repository: http://ppa.moosefs.com/moosefs-3/yum/el7)

#### Operating system (distribution) and kernel version.
```
$ rpm -q centos-release
centos-release-7-6.1810.2.el7.centos.x86_64
$ uname -r
3.10.0-957.21.3.el7.x86_64
```

#### How much data is tracked by moosefs master
 - **All fs objects:** 110087434
 - **Total space:** 321 TiB
 - **Free space:** 166 TiB
 - **RAM used:** 30 GiB
 - **last metadata save duration:** 57 min

## Problem description
Moosefs master terminated itself. In journal I found:
```
maj 20 08:00:00 xxx mfsmaster[7729]: metadata store lockf error: EACCES (Permission denied)
maj 20 08:00:00 xxx mfsmaster[7729]: can't store metadata - exiting
maj 20 08:00:00 xxx mfsmaster[7729]: internal terminate request
```
I checked permissions, but everything is fine. Directory `/var/lib/mfs` (and all files inside) belongs to user `mfs` and group `mfs`.

After investigation I found a potential explanation: **mfsmaster cannot lock metadata file because a previous metadata storing process is still running. It cannot recognize this situation properly. It assumes an unhandled error occurrence and terminates itself.**

### Hypothesis justification
https://github.com/moosefs/moosefs/blob/3fbfbbcef36b74ced70fced170582ca783c58013/mfsmaster/metadata.c#L686-L694

At first glance it seems that the problem shouldn't occur. There is `else` branch in `metadata.c` that handles previous unfinished process.

https://github.com/moosefs/moosefs/blob/3fbfbbcef36b74ced70fced170582ca783c58013/mfscommon/sockets.h#L27-L31

But macro `ERRNO_ERROR` returns `true` if a previous metadata storing child process is still running. Thus mfsmaster terminates itself. 

According to man: the function `lockf` returns `EACCES (13)` or `EAGAIN (11)` if a file is locked and `F_TLOCK` or `F_TEST` was specified. Macro `ERRNO_ERROR` handles only `EAGAIN`. 

I wrote a simple C application that simulates that situation. Main process starts two child processes. First one locks a file with `F_TLOCK` the second one tries lock the same file with `F_TEST`. The second child process gets `EACCES (13)` from `lockf` function ([source code](https://gist.github.com/kopaczew/4e2a811f08a472dc0e11485aaa933945)).  I ran the application on Centos 7 and Ubuntu 18.04. The same result (`EACCES (13)`):
```
$ ./lock-test 
First child locked the file: '/tmp/test' and it's going to sleep...
Second child couldn't lock the file: /tmp/test. Error: 13
```

**Comment by acid-maker** [comment]
Returning EACCES is specific to Linux. Other system returns EAGAIN here. Of course I'll add test against this EACCES.

BTW. metadata save should usually take couple of seconds - minutes at most. If it takes more than an hour then probably there is something really wrong with your hardware.
