### ISSUE TITLE
Maintenance mode: enhancement request

### ISSUE THREAD

**Issue by BillKen** [moosefs/moosefs#372]
FEATURE request
#### Your moosefs version and its origin (moosefs.com, packaged by distro, built from source, ...).

3.0.114 built from source (git)

#### Operating system (distribution) and kernel version.

Odroid 4.19 kernel with gentoo 32bit arm raspberry-pi based userland for chunksevers, 64 bit on the intel based master

#### Hardware / network configuration, and underlying filesystems on master, chunkservers, and clients.
5x odroid hc2 arm systems with an odroid h2 intel (32gb ram) for master.  Storage is 7x HDDs with 2 being on external usb3 adaptors
Network for the cluster is split into two VLAN's for internal/external data transfers. Internal 1gb switch with 4 bonded interfaces to the router for external data flows.

#### How much data is tracked by moosefs master (order of magnitude)?

 - All fs objects: 26845457
 - Total space: 20 TiB
 - Free space: 13 TiB
 - RAM used: 7.2 GiB
 - last metadata save duration: ~25.6s

Data types range from /home storage, NAS file storage (over davfs), live lxc images and the live data stores for the mail system, calendaring, dns, webservers etc. that run on the lxc images

#
In the manual for MFS 3.0, it is stated that "**Note: If number of Chunkservers in maintenance mode is equal or greater than 20% of all Chunkserver, MooseFS treats all Chunkservers like maintenance mode wouldn’t be enabled at all.**"

This is fine for a large installation but those with 5 or less chunkservers can never use maintenance mode - I would find it would be very handy to be able to restrict replication activity in downtime.  I am using 3 and 4 as the settings for replication and can keep operating with no zero copy chunks with 2 or sometimes 3 chunkservers offine - but find the resulting replication storm is affecting the performamce of the cluster. Could the following changes be considered?

1. a setting be added to change the fixed 20% to a user configurable integer value that goes down to zero (e.g., always force into maintenance)

2. enhancement: change it to per storage device instead of per chunkserver and on the amount of storage affected (%) rather than numbers of chunkservers - I have disks ranging from 6TB down to 2TB and can see this giving more flexibility.

3. feature: look at the viability of testing for a possible zero copy situation if maintenance is requested for a chunkserver and initiating a replication before putting into maintenance mode (and of course allowing for an overide if a valid copy doesnt exist, or time is an issue)

BillK

**Comment by chogata** [comment]
MooseFS should never replicate chunks if all _disconnected_ (offline) chunkservers are in maintenance mode. The 20% concerns chunkservers that are in maintenance mode, but are on-line. On-line maintenance servers are not picked as target for replications, unless more than 20% are in that mode, then the setting is ignored.

So, if I understand correctly, you say you have 5 chunkservers and when you turn off one or two, your system starts heavily replicating. This would mean they are not in maintenance mode. Are you manually setting them in maintenance mode before you shut them down? If not, they are in temporaty maintenace mode, which, if you did not change the setting (CS_TEMP_MAINTENANCE_MODE_TIMEOUT), lasts only 30 minutes. After that they will no longer be marked as maintenance and then, yes, the system starts replicating undergoral chunks.

The solution would be to either mark them as maintenance before shutting them down or changing the aforementioned parameter to 0. But the last solution is dangerous, if you don't monitor your system closely - if a chunkserver process is terminated cleanly by the system for some reason and you don't know it, it will stay so until you notice it, without a single replication happening.

**Comment by BillKen** [comment]
Tkx, that explains it. I did not pick up there is a difference in operation for online or offline chunkservers in maintenance.  So what I should be doing is placing them in maintenance mode and immediately stop the chunkserver software.

BillK

**Comment by chogata** [comment]
Yes, that's basically what you want to do to avoid replications caused by disconnected chunkservers - manually put them in maintenance mode before disconnecting (shutting them down).

**Comment by BillKen** [comment]
Thanks, Ill close this.  I did a quick test - its doing what I want.

BillK
