### ISSUE TITLE
[question] CREATE-> KEEP - how fast?

### ISSUE THREAD

**Issue by eleaner** [moosefs/moosefs#375]
Hi

I am using few SSD as target for CREATE
but I hardly see any usage on them
how fast would chunks move from CREATE to KEEP?

Thanks,
Marcin

**Comment by xandrus** [comment]
Hi,

Chunks are migrated immediately so it is highly probable that CGI or CLI is not able to catch them. 
The question is how many chunks are created per second?

Thanks,
Alex

**Comment by eleaner** [comment]
Thanks

not many, that's home use with two users
