### ISSUE TITLE
Does it support s3 storage?

### ISSUE THREAD

**Issue by oracleloyall** [moosefs/moosefs#378]
## Have you read through available documentation and open Github issues?

No

## Is this a BUG report, FEATURE request, or a QUESTION? Who is the indended audience?

Invalid

#### How much data is tracked by moosefs master (order of magnitude)?

 - All fs objects:
 - Total space:
 - Free space:
 - RAM used:
 - last metadata save duration:

**Comment by oracleloyall** [comment]
Can it compatible with Amazon S3, Google Cloud Storage, and other S3-based object stores?If it support ,how to parse config file?

**Comment by xandrus** [comment]
Hi,

MooseFS at the moment is a distributed file system only.
It is not S3 compatibile.

You can try to use [min.io](https://min.io/) project with MooseFS to create an S3 gate.
