### ISSUE TITLE
Archive delay in hours

### ISSUE THREAD

**Issue by oszafraniec** [moosefs/moosefs#38]
It would be nice to have option to set delay time for archive in hours, not only in days ;) This will allow f.ex. to create/keep data during the day and archive it at night.

**Comment by oxide94** [comment]
Hi @oszafraniec,

I am happy to let you know, that this feature is already implemented and will be released in upcoming MooseFS 4.x release! Also, in MooseFS 4.x it will be possible to set delay basing on `mtime`, `ctime` and `atime` (see #77).

Thanks for the idea.

Best regards,
Peter / MooseFS Team

**Comment by chogata** [comment]
Feature implemented in MooseFS 4 - please, upgrade and test. If comments are needed, please open a new issue or discussion (whichever is appropriate for the info you want to post).
