### ISSUE TITLE
[Question] Recovery of chunkserver

### ISSUE THREAD

**Issue by struthio** [moosefs/moosefs#382]
hi,

Is it possible to recover chunkserver by switching chunks disk to another machine ?

Given situation:
host1 : Master
host2 : ChunkServer

Host2 have two disks
/dev/sda1 - where /var/lib/mfs (configuration data is located)
/dev/sdb1 - used as data storage for chunks

Lets assume that sda1 got broken and it is not possible to recover, but sdb1 is totally fine.

Can I just setup new host3, switch sdb1 now host, install chunkserver software on it and somehow 'load' chunks from old disk to new chunkserver  ?

I am most interested here in chunks that had goal=1 (as chunks with goal > 1 will just replicate themselves as new server is available).

**Comment by chogata** [comment]
Yes, you can do that. You can setup a new machine (host3), connect the disk form the faulty machine (host2). Let's say the disk is also `/dev/sdb1` in your host3. Put the mountpoint of `/dev/sdb1` into your `mfshdd.cfg`.  Before you start the chunkserver process, delete a file called `.chunkdb` from the main directory of your `/dev/sdb1` disk (note that it might not even be there, if your old chunkserver was not shut down cleanly, but if it is there - delete it). Then start the chunkserver (don't forget to adjust configuration in `mfschunkserver.cfg` for your setup befor you do). The new chunkserver will read all the chunks form the old disk and your moosefs instance will see them.

**Comment by struthio** [comment]
That is great. Thanks.
