### ISSUE TITLE
Internal rebalance highspeed mode

### ISSUE THREAD

**Issue by oszafraniec** [moosefs/moosefs#39]
Internal rebalance is not a good state of a chunkserver from my practise. Such a CHSRV does not receive/write new data and it's free space for some time is present but can't be used.

Now internal rebalance of a chunkserver is quite slow. It's 1 mv operation at a time from one drive to the other. This is OK with big chunks and with 1 drive that only slightly drifted away from the others. The gap can be closed in reasonable time.

But, if you want to change f.ex. a drive in CHSRV for a bigger one you have a problem. You will empty the small/old drive (1TB?), remove it, insert new/empty big drive (4TB?) and... let the slow internal rebalance begin... 1 chunk at a time every few sec, not too fast. If avg chunk size will be ~5MB this process can take even 4 weeks! All this time this chunkserver is not taking part in writing/receiving new data. All this time it's free space won't be used. After this time this chunkserver will need to be rebalanced with other chunkservers that was receiving new data and drifted away with used space %.

My sugestion is to be make an option to be able to set chunkserver in some special mode (like MNT mode) in whith mfsmaster will not use this chunkserver and it will perform multiple mv operations from all drives with less space to all drive with more space internally. Administrator can set this mode for some time and let the internal rebalance end ASAP.

**Comment by zhs077** [comment]
+1

**Comment by 4Dolio** [comment]
I believe it may be possible to manually rebalance disks.  I have a script which takes a set of source disks and target disks and will move(offline) or copy(used while online) a given fraction (size averaged) of chunk files from the sources to the targets.  If done while live I finish the process by reloading the chunk server which purges the duplicates during the startup scan.  I designed this for LizardFS but it may be applicable to MooseFS also.

**Comment by oszafraniec** [comment]
Hmm... It was 2016 when I wrote something like this for our MooseFS setup ;) 

<pre>
#!/bin/bash
sourcedrive=`realpath "$1"`
targetdrive=`realpath "$2"`
filesizelimit="5M"
for moosedir in `find $sourcedrive -maxdepth 1 -mindepth 1 -type d -printf '%f\n'`; do
	time find $sourcedrive/$moosedir/ -type f -size +$filesizelimit -exec mv -v "{}" $targetdrive/$moosedir/ \; 
done 
</pre>

That's why I started this issue a year a go :)

**Comment by tclh123** [comment]
Yes, it's possible. I wrote a migration tool to migrate my moosefs data to another new data center.
 [see this issue](https://github.com/moosefs/moosefs/issues/80#issuecomment-348854425)

Something to know, you need to stop the target chunkserver and remove the `.chunkdb` file just generated, then start it, instead of just reloading the chunkserver which is not useful for moosefs 3.0 to do a full disk scan.

**Comment by oszafraniec** [comment]
Just to extend @tclh123 advice... Removing .chunkdb forces full-drive-scan for sure, so if you want it to happen and be sure about it, remove it.

But if you stop chunkserver, mess with something on it (just try remove 1 chunk or move it to different dir) and start chunkserver again, it will check .chunkdb against the drive and if there is any diffrence (and there will be), full-drive-scan is performed automatically.

BTW> Doing something with chunks when chunkserver is started it's not a good idea. We always stop the CS, do something, start it again and let him scan what has changed. This way it always worked so far.

**Comment by 4Dolio** [comment]
Thanks for the tips about .chunkdb file which I was not aware of.  Because, I went with LizardFS when it forked but really want to get back to testing MooseFS again and see if any of my homebrew HA solutions are applicable.

When I manipulate chunks while the service is running I completely agree this is playing dangerously and could cause all sorts of problems and I do not recommend anyone ever do so if they value their data.  With that said I am very glad that it is possible to manipulate chunks and leverage the various cluster services in so many non native ways.  Such is the nature of a truly powerful tool.

**Comment by acid-maker** [comment]
Soon we will publish version 4.x on GPL and we decided to move our HA to GPL, so be patient.

**Comment by oxide94** [comment]
@oszafraniec: This feature has been implemented in commit e3ba14da6fc7349bba86082119b35ec66acfe251 :)

Thanks for the idea!

Best regards,
Peter / MooseFS Team

**Comment by eleaner** [comment]
@acid-maker 
Any news about 4.x on GPL and HA?

**Comment by footlooseboss** [comment]
> @acid-maker 
> 
> Any news about 4.x on GPL and HA?

" "

**Comment by footlooseboss** [comment]
> **2018** 
> Soon

>  **2023**
> 💀

**Comment by bobapplemac** [comment]
Just saw the 4.56.5 announcement - it looks like HA is still being reserved for PRO only - can someone from the MooseFS team confirm?

**Comment by chogata** [comment]
We want to clarify that our team has decided not to incorporate this feature into the open source release at this time. This decision was primarily guided by our commitment to ensuring the effective maintenance of the open source project as a whole. Including high availability could stretch our resources, which may compromise the overall quality and support we strive to provide to our community.
Back in 2018, we had a plan to add the High Availability feature to the community edition; however, after careful evaluation, we determined that it would not be a sustainable decision for our ongoing development and support.
Maintaining long-term open source projects requires a careful balance between freely available features and those reserved for paying customers. These decisions are not easy, and we diligently consider their implications for both our users and the sustainability of the project.
Our goal is to maintain MooseFS in the long term, ensuring it remains a valuable resource for our community. We appreciate your understanding and continued support.
