### ISSUE TITLE
Buggy fuse server detected

### ISSUE THREAD

**Issue by jSML4ThWwBID69YC** [moosefs/moosefs#390]
## Have you read through available documentation and open Github issues?

Yes

## Is this a BUG report, FEATURE request, or a QUESTION? Who is the intended audience?
 
Bug report or maybe a question.

## System information

Hardware: 

Running FreeBSD 12.1p10
1x metadata 

Running FreeBSD 12.2p0
4x chunkservers 
1x master
4x clients running. This report is about the client error messages. 

Network: 
2x 10Gbe LACP per server
 
#### How much data is tracked by moosefs master (order of magnitude)?

 - All fs objects: 12073504                        
 - Total space: 76TiB
 - Free space: 69TiB
 - RAM used: 11GiB
 - last metadata save duration: 6.8s

Moosefs is version 3.0.115 installed from ports. 

## Describe the problem you observed.

There are new errors on FreeBSD 12.2 when using MooseFS. The errors show on the mfsclient servers. 
```
<snip> kernel: fuse_vnop_lookup: cache incoherent on /storage/chunk!  Buggy FUSE server detected.  To prevent data corruption, disable the data cache by mounting with -o direct_io, or as directed otherwise by your FUSE server's documentation
```
```
<snip> kernel: fuse_internal_do_getattr: cache incoherent on /storage/chunk!  Buggy FUSE server detected.  To prevent data corruption, disable the data cache by mounting with -o direct_io, or as directed otherwise by your FUSE server's documentation
```
The mount options I've tested are: 

mfsmount IP:/web -o mfspassword=PASS -o mfsmkdircopysgid=1 /storage/chunk
mfsmount IP:/web -o mfspassword=PASS -o mfsmkdircopysgid=1 -o mfscachemode=DIRECT /storage/chunk

The errors show regardless of the mfscachemode. They also show without Nginx running so I don't believe it's a duplicate of #381 

I've not detected any data corruption yet, but the errors are certainly scary.

**Comment by jSML4ThWwBID69YC** [comment]
Testing with caching disabled continues to trigger the above errors. Here's my new mfsmount command. 

```
mfsmount IP:/web -o mfspassword=pass -o mfsmkdircopysgid=1 -o mfscachemode=DIRECT -o mfsattrcacheto=0 -o mfsentrycacheto=0 -o mfsdirentrycacheto=0 -o mfsnegentrycacheto=0 /storage/chunk
```
I can also confirm issue #362 is still happening on FreeBSD 12.2 with MooseFS 3.0.115.

**Comment by chogata** [comment]
This must be something new to FreeBSD 12.2. Our FreeBSD machines are updating to 12.2, I'll run some tests and try to see, what this is about...

**Comment by jSML4ThWwBID69YC** [comment]
@chogata 

It's definitely new to FreeBSD 12.2. It floods the /var/log/messages log.

**Comment by gtech99** [comment]
is there an update on this issue ? We are on 12.1 right now, pondering upgrading to 12.2

**Comment by jSML4ThWwBID69YC** [comment]
@gtech99 

The issue is still present on FreeBSD 12.2, and 13.0.

**Comment by grahamperrin** [comment]
Maybe of interest, FreeBSD bugs: 

* [256936 – Buggy filesystem detected - message wrongly triggered by FUSE filesystems](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=256936)
* [256937 – Kernel panic on FUSE filesystem - lockmgr_xlock_hard: recursing on non recursive lockmgr](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=256937)

Historically (2020-03-11): 

* https://cgit.freebsd.org/src/commit/?id=b0ecfb42d1705bc1423c726a16a182c81047f854

> fusefs: avoid cache corruption with buggy fuse servers

**Comment by grahamperrin** [comment]
Reproducible with FreeBSD 14.2-RC1 or 15.0-CURRENT? 

Also: 

- https://github.com/moosefs/moosefs/issues/592

**Comment by jSML4ThWwBID69YC** [comment]
The error message does not display on FreeBSD 12.4-RC1. Closing issue.
