### ISSUE TITLE
mfsmaster stop fails due to lack of hard disk space

### ISSUE THREAD

**Issue by colindaven** [moosefs/moosefs#395]
I had problems where 

`sudo mfsmaster stop`

fails due to lack of local hard disk space (my bad) on a tiny VM, and cannot then be stopped.

Just a warning for other users.

**Comment by chogata** [comment]
Hi @colindaven 

May I ask why you closed this ticket already? MooseFS should not behave like that (master should always close, especially when there are some problems), I was about to ask for the details of your installation...

**Comment by chogata** [comment]
Just making sure I understand correctly: after you issued the command `sudo mfsmaster stop`, the process did not terminate (there was still active process with the name mfsmaster in your system after a couple of minutes), but at the same time the instance did not work (CGI did not show a working master). Was this what happened?

**Comment by colindaven** [comment]
Yes, exactly

**Comment by dagelf** [comment]
You ran `mfsmaster` manually, and not from systemd? Because `mfsmaster stop` won't stop that, for that you have to do `service moosefs-master stop`.

**Comment by colindaven** [comment]
Yes. Interesting. 
I always use the non-systemd variant, similarly with chunkservers. Seems to work fine (of course I don't restart or stop the master often, if I can, unless after a reboot etc).
```
mfsmaster start
mfsmaster restart
mfsmaster stop
```
