### ISSUE TITLE
chunk hasn't been deleted since previous loop - retry

### ISSUE THREAD

**Issue by xiewei9527** [moosefs/moosefs#40]
Recently,I found one of my chunkserver cpu wio sometime is very high,that make some write work failed.   check  the master log,I find some problem,just like below:

Feb  7 03:19:01 yz147 mfsmaster[20934]: chunk hasn't been deleted since previous loop - retry
Feb  7 03:19:32 yz147 last message repeated 368 times
Feb  7 03:19:45 yz147 last message repeated 194 times
Feb  7 03:19:45 yz147 mfsmaster[20934]: (10.39.2.111:9422) chunk: 00000000220860AD deletion status: 13
Feb  7 03:19:45 yz147 mfsmaster[20934]: (10.39.2.111:9422) chunk: 00000000220760AD deletion status: 13
Feb  7 03:19:45 yz147 mfsmaster[20934]: (10.39.2.111:9422) chunk: 00000000220786A2 deletion status: 13
Feb  7 03:19:45 yz147 mfsmaster[20934]: (10.39.2.111:9422) chunk: 000000002207903E deletion status: 13
Feb  7 03:19:45 yz147 mfsmaster[20934]: (10.39.2.111:9422) chunk: 00000000220890B9 deletion status: 13
Feb  7 03:19:45 yz147 mfsmaster[20934]: (10.39.2.111:9422) chunk: 000000002207B2D6 deletion status: 13
Feb  7 03:19:45 yz147 mfsmaster[20934]: (10.39.2.111:9422) chunk: 000000002207B89A deletion status: 13
Feb  7 03:19:45 yz147 mfsmaster[20934]: (10.39.2.111:9422) chunk: 000000002207C704 deletion status: 13
Feb  7 03:19:45 yz147 mfsmaster[20934]: (10.39.2.111:9422) chunk: 000000002207F2BD deletion status: 13
Feb  7 03:19:45 yz147 mfsmaster[20934]: (10.39.2.111:9422) chunk: 000000002207F9F2 deletion status: 13
Feb  7 03:19:45 yz147 mfsmaster[20934]: (10.39.2.111:9422) chunk: 000000002207FA6D deletion status: 13
Feb  7 03:19:45 yz147 mfsmaster[20934]: (10.39.2.111:9422) chunk: 000000002207FEC0 deletion status: 13
Feb  7 03:19:45 yz147 mfsmaster[20934]: (10.39.2.111:9422) chunk: 000000002209FF3B deletion status: 13
Feb  7 03:19:45 yz147 mfsmaster[20934]: (10.39.2.111:9422) chunk: 000000002207FFB6 deletion status: 13
Feb  7 03:19:45 yz147 mfsmaster[20934]: (10.39.2.111:9422) chunk: 0000000022080409 deletion status: 13
Feb  7 03:19:45 yz147 mfsmaster[20934]: (10.39.2.111:9422) chunk: 0000000022080484 deletion status: 13
Feb  7 03:19:45 yz147 mfsmaster[20934]: (10.39.2.111:9422) chunk: 000000002208057A deletion status: 13
Feb  7 03:19:45 yz147 mfsmaster[20934]: (10.39.2.111:9422) chunk: 00000000220806EB deletion status: 13
Feb  7 03:19:45 yz147 mfsmaster[20934]: (10.39.2.111:9422) chunk: 0000000022080766 deletion status: 13
Feb  7 03:19:45 yz147 mfsmaster[20934]: (10.39.2.111:9422) chunk: 0000000022071B19 deletion status: 13
Feb  7 03:19:45 yz147 mfsmaster[20934]: (10.39.2.111:9422) chunk: 0000000022091DFB deletion status: 13

In one second ,these message repeat  nearly 3000 times ,  that means a lot of deletion is working in chunkserver  10.39.2.111 .   I don't understand  why this happen .  my trash time is 86400  ,everyday I clean the space on 17:00:00  .why deletion happen in 03.

my moosefs version is 1.6.20 . work on Redhat 5.4 .

Any ideas ?  Thanks

**Comment by xandrus** [comment]
I would like to add that MooseFS 1.6 is no longer supported version.

Look how many fixes ware made since version 1.6.20.
https://moosefs.com/documentation/changes-in-moosefs-3-0.html

Please consider to update MooseFS to version 2.0.91 and than to MooseFS 3.0.86
https://moosefs.com/Content/Downloads/moosefs-upgrade.pdf

**Comment by xandrus** [comment]
And also please consider to update your operating system. 
Support for Red Hat 5.4 ended July 31, 2011.

So right now you have two unsupported systems.

**Comment by xiewei9527** [comment]
@xandrus    any way ,Thanks for your reply.

**Comment by xandrus** [comment]
By the way. You can do update in the fly.
So you don'y need to migrate data or move it some ware else.

Just update it in correct order:
1. Master Server
2. Chunkservers(in one by one scenario)
3. Mounts

**Comment by xandrus** [comment]
My mistake.
I mean:
.. you don'y need to migrate data or move it somewhere else.
