### ISSUE TITLE
[BUG] ZeroDivisionError on MFSCGI

### ISSUE THREAD

**Issue by struthio** [moosefs/moosefs#412]
## Have you read through available documentation, open Github issues and Github Q&A Discussions?

Yes

## System information

Running Ubuntu 20.04

#### Your moosefs version and its origin (moosefs.com, packaged by distro, built from source, ...).

CGI version: 3.0.115 ; python: 3.8
MASTER - 3.0.115

From Ubuntu ppa repository.

#### Operating system (distribution) and kernel version.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

Linux eden 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

#### How much data is tracked by moosefs master (order of magnitude)?

 - All fs objects:
 - Total space:
 - Free space:
 - RAM used:
 - last metadata save duration:

## Describe the problem you observed.

When using MFSCGI when there are some chunkservers everything is fine.
When I turn off all chunkservers Resources tab in MFSCGI gives following error:

Traceback (most recent call last):
  File "/usr/share/mfscgi/mfs.cgi", line 6050, in 
    msperc = (1.0 * mscount) / scount
ZeroDivisionError: float division by zero

#### Can you reproduce it? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

1. Start mfsmaster
2. Start mfscgi
3. Start chunkserver
4. Stop chunkserver

**Comment by chogata** [comment]
Thank you for the report, we'll fix it :)

**Comment by borkd** [comment]
I'm closing #459 as a duplicate, but it seems the problem persists with the latest HEAD

Culprit in https://github.com/moosefs/moosefs/blame/master/mfsscripts/mfscli.py.in#L6102
