### ISSUE TITLE
Mfsmount in /etc/fstab error

### ISSUE THREAD

**Issue by Hello-Linux** [moosefs/moosefs#42]
When I use mfsmount in /etc/fstab to mount mfs,but it show "mount: wrong fs type, bad option, bad superblock on mfsmount,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
mount: wrong fs type, bad option, bad superblock on mfsmount,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so"    and my linux version is centos7 kernel is 3.10.0-123.9.3.el7.x86_64,but at the same other one is success

**Comment by xandrus** [comment]
Hi,
Please check if you have installed fuse utilities, because without this package mfsmount will not work with fstab.

CentOS 7 packages should look like this:
`fuse.x86_64 : File System in Userspace (FUSE) utilities`
`fuse-libs.x86_64 : File System in Userspace (FUSE) libraries`

Would you be so kind and send us mfsmount line from fstab?

**Comment by richarson** [comment]
Would you guy reconsider adding fuse as a dependency for mfsmount?

I know fuse it's not really required to use mfsmount but I think this is already a recurring problem :)

Or at least put a note on the docs that you need to install fuse utilities, e.g (extracted from https://moosefs.com/download/centosfedorarhel.html):

After installing the MooseFS Client, you can add the following entry to your /etc/fstab to mount MooseFS automatically when system starts (**but note that you'll have to install fuse if you want to use this method**):
```
mfsmount /mnt/mfs fuse defaults 0 0
```

**Comment by oxide94** [comment]
Hi @richarson,

Thanks for reminding this matter - indeed I can remember, that it was mentioned somewhere on MooseFS-Users mailing list some time ago. Good point regarding the proposed place for info about fuse utilities on RPM-based systems - I'll take care of posting it on our website tomorrow, thanks!

Concerning packages - I can't promise we'll put fuse utils as a dependency, but we definitely will discuss it.

Best regards,
Peter / MooseFS Team

**Comment by richarson** [comment]
@oxide94 Thanks!

**Comment by oxide94** [comment]
@richarson:

I've just added better description on https://moosefs.com/download/centosfedorarhel.html. Please check it out - all comments and suggestions of course are welcome:

> If you want MooseFS to be mounted automatically when system starts, frist of all install `File System in Userspace (FUSE) utilities`:
> `# yum install fuse`
> and then add one of the following entries to your /etc/fstab:
> 
> "classic" entry (works with all MooseFS 3.0 and 2.0 verisons):
> `mfsmount /mnt/mfs fuse defaults 0 0`
> 
> or "NFS-like" entry (works with MooseFS 3.0.75+):
> `mfsmaster.host.name:	/mnt/mfs	moosefs	defaults	0	0`

**Comment by richarson** [comment]
@oxide94 Perfect, thanks!

**Comment by oxide94** [comment]
Guys, do you think this issue can be closed? I can't see anything more to be done on it for now.

Peter / MooseFS Team
