### ISSUE TITLE
[FEATURE] High available metaserver support

### ISSUE THREAD

**Issue by zhanglistar** [moosefs/moosefs#440]
## Have you read through available documentation, open Github issues and Github Ideas Discussions?

Yes

## Describe your request:
Is there a roadmap of high availability of metaserver? We want to use moosefs to substitute hdfs.

**Comment by chogata** [comment]
Hi,

This is a feature requested by enterprise clients and as such is available in the pro version. Please, contact contact@moosefs.pro for more details about the pro version. You can also visit https://moosefs.com/
