### ISSUE TITLE
[BUG] unanticipated nonprinting in file header

### ISSUE THREAD

**Issue by tmatejuk** [moosefs/moosefs#471]
## Have you read through available documentation, open Github issues and Github Q&A Discussions?

Yes ( as far as I can )

#### Your moosefs version and its origin (moosefs.com, packaged by distro, built from source, ...).
moosefs.com, 3.0.116

#### Operating system (distribution) and kernel version.
centos7, 
and centos7 and ubuntu18, debian11 on clients

#### Hardware / network configuration, and underlying filesystems on master, chunkservers, and clients.
multiprocesors master, logger, chunks, 2x 10Gb eth network, 
clients: multiprocessor, single processor, 10 / 1 Gb eth network; moosefs mounted with mfsmount .

#### How much data is tracked by moosefs master (order of magnitude)?
 - All fs objects: 101709122
 - Total space: 800 TiB
 - Free space: 248 TiB
 - RAM used: 31 GiB
 - last metadata save duration: ~35.3s

## Describe the problem you observed.
In the morning user reported corrupted .gz files. 

Other user created test. When run in bash :
```
   for i in 1 2 3; do echo $i >> test.txt; done

   cat -v test.txt 
```
showed that file has a lot of repeated non-printing '^@' at beginning of a file.

```
cat -v test.txt
^@^@^@^@^@^@^@^@^@ ...
...
...
^@^@^@^@^1
2
3
```

Mentioned corrupted .gz files also had additional ^@^@^@ at begging.

When displayed with command 'xxd', all additional ^@ hex representation was 0000.

#### Can you reproduce it? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Problem was reproducible with 
```
   for i in 1 2 3; do echo $i >> test.txt; done
```
on all tested clients ( centos7, ubuntu18, ubuntu20 ).

Problem was reproducible for at least ~4 hours.

After working hours I noticed that problem does not occur anymore.

It is unknown if affected files were corrected by file system, because affected files were deleted by users.
Some users created copies of affected files, those files still have '^@' at begging.

#### Include any warning/errors/backtraces from the system logs.
Chunk servers logs contains  errors
```
mfschunkserver[38137]: connect to 192.168.NNN.MMM:9422 failed, error: ETIMEDOUT (Operation timed out)
```
they occur regularly before, during, and after issue I report, with simillar frequency so I believe they are not good indicator.

Did not find other warnings/backtraces. 

Is there any particular test / log entry that may confirm issue.
What should I do to prevent such problems.

**Comment by tmatejuk** [comment]
I believe I tested the same file ("test.txt") from different client, but I am not really sure.
When problem was occurring I put more work to find workaround ( using local storage instead of shared MooseFS storage ).
I planed to do more test in evening, but then I was not able to reproduce it.

**Comment by chogata** [comment]
The reason I'm asking is there is a known problem with append mode and kernel cache on Linux. The result would be kind of what you showed: zero bytes present on writing client in the file, but the same file read from another client would be 100% correct. I need to know if your problem is the same cache problem we know about or something else. Please, try to repeat the problem and when you do, read the file from another client.

**Comment by tmatejuk** [comment]
Problem did not repeated. 
I will remember to check file from different client.
