### ISSUE TITLE
Drive's SMART data at Disks tab

### ISSUE THREAD

**Issue by oszafraniec** [moosefs/moosefs#48]
It would be really nice to see SMART data of a drive via Disks tab. [smartmontools](https://www.smartmontools.org) can be used by chunkserver for this if you don't want to make internal own code for this feature. It should be avaible per drive per request, some small popup with SMART table in it.

**Comment by marcin-github** [comment]
I think that monitoring smart parameters should be done using smartd (with mail notification), collectd (smart plugin), nagios/zabix/etc.

**Comment by oszafraniec** [comment]
@marcin-github I didn't asked for a smart monitoring tool built into MFS. I just asked for a quick preview of SMART data of a drive from a Disks tab, that's all :) Sometimes it's much easier and quicker to click a few times on a web that log into 5-10 servers just to check how of some the drives are doing. MFS is here, master-chunksrv communication is here, web-cgi is here... why not to add this small addon?

**Comment by marcin-github** [comment]
It needs mfs-chunkserver to have write access to block device. People oriented on security won't be happy:)
I'm not power user of moosefs and I'm using it in one small system since a short time so I'm not familiar with moosefs philosophy well. But I personally prefer rather old way, one task - one tool than installing bloatware.

**Comment by zcalusic** [comment]
@oszafraniec, while it is generally a fine idea, you do understand that SMART is **choke full** of various parameters, and there just wouldn't be enough space on the web page to present all the relevant ones. And who'd decide which ones are relevant? And who would trust it, if only small part of the info is presented?

You'd need temperature_celsius to catch overheating in the DC, I'd want percent_lifetime_used to know when my SSD's start dying, other people would like to monitor write errors, cable CRC errors, offline_uncorrectable, read error rates, power_on_hours etc, etc... The SMART is overwhelming.

I agree with @marcin-github, use right tool for specific job. MFS is not a monitoring tool, but a DFS.

**Comment by oszafraniec** [comment]
@marcin-github just from curiosity, why you need write access to retrieve SMART data? why not to use smartctl to get job done?

@zcalusic I'm aware of SMART and the way every vendor uses it's own ways to collect and present data differently even between drive models of the same vendor (Kingston SSDs f.ex.). It's a pain and I know it :) 
I don't want to present SMART info on the Disks tab directly. I was thinking only about some icon/link next to IP path which opens modal window with simple table of SMART data with values, typical what you can see in HD Tune or smartmontools output. Just a shortcut to get smartmontools output with 1 click rather then via cli on chunkserver.

I don't want to exaggerate the problem, it's a feature, a cosmetic one... but it's nice to see some discussion about it that can motivate MFS team to develop something and community to throw new ideas for them ;)
