### ISSUE TITLE
[BUG] Fuse driver timeout on fdatasync

### ISSUE THREAD

**Issue by piotr-machura** [moosefs/moosefs#485]
## Have you read through available documentation, open Github issues and Github Q&A Discussions?

Yes

#### How much data is tracked by moosefs master (order of magnitude)?

 - All fs objects: 0B
 - Total space: 20GB
 - Free space: 19GB
 - RAM used: 0.5GB
 - last metadata save duration: 0s

## Describe the problem you observed.

I have created an example cluster step by step, as described in  [user manual](https://moosefs.com/Content/Downloads/moosefs-3-0-users-manual.pdf), only modifying the files in the way described in the guide. I am able to mount root MooseFS directory, with all created servers and the mountpoint visible in CGI interface
![image](https://user-images.githubusercontent.com/59394665/185707849-ee41b244-f418-4337-b745-191c801f5a69.png)

I am also able to create directories and set the goal: 
![image](https://user-images.githubusercontent.com/59394665/185708040-eea07936-0fd2-4bb6-8dab-4a3b0aae0f0b.png)
and create empty files:
![image](https://user-images.githubusercontent.com/59394665/185708131-b46fa2e9-8fe3-4035-9bf3-e9f03f22224c.png)
The problem is, no data can be written to the mounted directories. Not by `cp`, `dd` or any other means. The program tasked with writing data hangs for ~5 minutes and exits with an input-output error. I have devised a simple C program to test the exact failure point:
```c
/* writetest.c */

#include <stdio.h>
#include <fcntl.h>
#include <unistd.h>

#define FILEPATH "/mnt/mfs/my-dir/test10.txt"
#define MSG "Hello, world!\n"

int main(void) {
	// Open syscall
	int fd = open(FILEPATH, O_WRONLY | O_CREAT | O_TRUNC, (mode_t) 0644);
	if (fd < 0) {
		perror("open() failed");
		return 1;
	}
	printf("Opened %s with descriptor %d\n", FILEPATH, fd);

	// Write syscall
	int nchars = write(fd, MSG, sizeof(MSG) - 1);
	if (nchars < 0) {
		perror("write() failed");
		return 2;
	}
	printf("Written %d bytes to %s\n", nchars, FILEPATH);

	// Flush syscall - no metadata
	int flushed = fdatasync(fd);
	if (flushed < 0) {
		perror("fdatasync() failed");
		return 3;
	}
	printf("Flushed kernel buffer\n");

	// Close syscall
	int closed = close(fd);
	if (closed < 0) {
		perror("close() failed");
                return 4;
	}
	printf("Closed %s\n", FILEPATH);
	return 0;
}
```
Running this program fails at the `fdatasync()` step after hanging at `Written 14 bytes to /mnt/mfs/my-dir/test10.txt`:
![image](https://user-images.githubusercontent.com/59394665/185708805-f7f70646-172c-477d-9b6f-973222433494.png)
The resulting file is empty. The long wait time makes me think the fuse driver hits a timeout, but that's just a guess 

No errors can be seen in client's `dmsg` or on the server side - the attempted writes are even visible in the CGI interface:
![image](https://user-images.githubusercontent.com/59394665/185709216-963aa448-6783-4f33-9a35-d64bec1ac974.png)
and `systemctl status` reports no errors on master, metalogger or the chunkservers.

I have re-installed the servers twice to ensure I didn't miss any steps, also tried VirtualBox instead of KVM to see if the issue is related to virtualization, but no dice.

Am I missing some obvious configuration step here?

**Comment by chogata** [comment]
It's a network problem: your client(mount) can't reach your chunkserver. It can be either because your mappings are not done correctly (post your module configs here if you want so I can check them) or your firewall is bloking those connections after all. And there have to be some messages from the client(mount) about that in your client's system logs. The writes will be in operations statistics, yes - the statistics show all attempts, successful and unsuccessful.

**Comment by piotr-machura** [comment]
Thanks, this turned out to be a combination of both things you mentioned: client and chunkservers were not on the same network (chunkservers on 192.168.10.0/24, client on 192.168.122.0/24) and missing firewall rules, defaulted to deny. Connecting the client to 192.168.10.0/24 and `ufw default allow` on chunkservers fixed the issue (I'll figure out more appropriate rules later).

Closing the issue, thanks again for the help.
