### ISSUE TITLE
Server select menu for Disks tab

### ISSUE THREAD

**Issue by oszafraniec** [moosefs/moosefs#49]
It would be very nice to by able to narrow the Disks tab to 1 chunkserver via the select dropdown, same as on Servers Charts to display all charts for a particular chkserver. As the cluster grows (f.ex. we have 10 CHKSRV with 200 drives total), Disks tab starts to be difficult to read if you want to focus on a particular chunkserver.

**Comment by chogata** [comment]
Feature implemented in MooseFS 4 - please, upgrade and test. If comments are needed, please open a new issue or discussion (whichever is appropriate for the info you want to post).
