### ISSUE TITLE
[BUG] Can't mount mfsmeta

### ISSUE THREAD

**Issue by Nexus2k** [moosefs/moosefs#517]
## Have you read through available documentation, open Github issues and Github Q&A Discussions?

Yes

#### Your moosefs version and its origin (moosefs.com, packaged by distro, built from source, ...).
apt install moosefs-* 3.0.116
#### Operating system (distribution) and kernel version.
Ubuntu 22.04 LTS
#### Hardware / network configuration, and underlying filesystems on master, chunkservers, and clients.
Mostly 1GBe connections between 22 servers, 
20 chunkservers 2x512GB SSD with ext4 (non-dedicated disks)
#### How much data is tracked by moosefs master (order of magnitude)?
4.1 TB in ~160k files

 - All fs objects: 159180
 - Total space: 8.7 TiB
 - Free space: 4.6 TiB
 - RAM used: 503 MiB
 - last metadata save duration: ~0.2s

## Describe the problem you observed.
I can't get the mfsmeta directory mounted to delete the trashfiles. I want to delete them as I've noticed a significant slow-down of writes after I wrote about 1.3TB of data.
```
# mfsmount -o mfsmeta /mnt/mfsmeta
mfsmaster register error: Permission denied
# mfsmount -o mfsmeta /mnt/mfsmeta -H mfsmaster
mfsmaster register error: Permission denied
```

#### Can you reproduce it? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Yes never works.

#### Include any warning/errors/backtraces from the system logs.
Tried to adjust mfsexports.cfg file with alldirs,maxtrashtime=0 but the trash files don't get cleaned up neither.
```
# cat /etc/mfs/mfsexports.cfg
10.8.0.0/16     /       rw,maproot=0,alldirs,maxtrashtime=0
```
I'm not sure if I need any other mfsexports entry to be able to mount mfsmeta or some mfsmaster.cfg line.

Any help appreciated.

**Comment by pkonopelko** [comment]
Most probably it is not a bug, but a configuration issue. In order to access the `mfsmeta` virtual directory, you need to explicitly allow access to it in `mfsexports.cfg` file on Master Server.

As per `man mfsexports.cfg`:

> Syntax is:
> `ADDRESS DIRECTORY [OPTIONS]`
> (...)
> `DIRECTORY` can be `/` or path relative to MooseFS root; special value `.` means MFSMETA companion filesystem.

Please try adding the following line to your `mfsexports.cfg` and **reloading** the Master Server (`mfsmaster reload`).

```
# Allow "meta"
10.8.0.0/16     .       rw
```

Please confirm if this resolved your issue.

**Comment by Nexus2k** [comment]
Thanks that indeed worked. Must have indeed missed that `special value . means MFSMETA companion filesystem.` line.
