### ISSUE TITLE
Maintenance mode questions

### ISSUE THREAD

**Issue by Damien9527** [moosefs/moosefs#53]
Recently,    our mfs cluster   network will have an update, and that time ,all our servers  will lost connect with other servers  in the cluster . 

Should  I  make all the chunkservers in maintenance mode  ?   and stop my  mfsmasters  process ?    

Any other advise ?

**Comment by xandrus** [comment]
In this particular case you should stop mfsmaster process only.
All chunkservers will be disconnected from master server so no other operations will be performed.

Maintenance mode was designed to prevent cluster from chunks replications during server power off, updates or other works.
If you enable maintenance mode on all chunkservers, master will ignore this state.
