### ISSUE TITLE
mfsmaster -a restore hangs with 100% CPU usage

### ISSUE THREAD

**Issue by baby-gnu** [moosefs/moosefs#536]
## Have you read through available documentation, open Github issues and Github Q&A Discussions?

Yes:

- [documentation](https://moosefs.com/support/#documentation)
- [best practice](https://moosefs.com/support/#best-practices)
- [FAQ](https://moosefs.com/faq/)
- [`restore` in bug tracker](https://github.com/moosefs/moosefs/issues?q=is%3Aissue+restore)
- [`metalogger` in bug tracker](https://github.com/moosefs/moosefs/issues?q=is%3Aissue+metalogger+)
- [a discussion about desaster recovery](https://github.com/moosefs/moosefs/discussions/533)

## System information

- 1 moosefs-master (4 disabled to permit restart after a failure)
- 5 moosefs-metalogger
- 5 moosefs-chunserver

#### Your moosefs version and its origin (moosefs.com, packaged by distro, built from source, ...).

All packages version `3.0.115-1` from Debian Bullseye repository

#### Operating system (distribution) and kernel version.

<details><summary><code>lsb_release -a</code></summary>

```
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```
</details>

<details><summary><code>uname -a</code></summary>

```
Linux moosefs-1 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64 GNU/Linux
```
</details>

#### Hardware / network configuration, and underlying filesystems on master, chunkservers, and clients.

Virtual KVM Machine on Intel(R) Xeon(R) Gold 5220 CPU with 10Gbs network interfaces

- master and metalogger using ext4
- chunkserver using xfs

#### How much data is tracked by moosefs master (order of magnitude)?

 - All fs objects: 243081
 - Total space: 938 GiB
 - Free space: 879 GiB
 - RAM used: 554 MiB
 - last metadata save duration: 

## Describe the problem you observed.

I test the restoration from `mfsmetalogger` but `mfsmaster -axx restore` use 100% CPU and hangs on a changelog entry.

#### Can you reproduce it? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes:

1. on a client with `/mnt/` a moosefs mount point
   1. execute `rsync -avP /usr/ /mnt/usr/`
   2. execute `sync`
   3. `rm -vrf /mnt/usr/`
2. during the `rm -rf`, stop the `mfsmaster` process, the `rm -rf` hangs as expected
3. on a server with `mfsmetalogger` running, execute `mfsmaster -axx restore`

#### Include any warning/errors/backtraces from the system logs.

<details><summary><code>mfsmaster -axx restore</code></summary>

```
[…]
filename: changelog_ml.0.mfs ; current meta version: 3217451 ; previous changeid: 3217450 ; current changeid: 3217451 ; change data1682350594|UNLINK(325773,_kernel-install):326154

changelog_ml.0.mfs: change1682350594|UNLINK(325773,_kernel-install):326154

filename: changelog_ml.0.mfs ; current meta version: 3217452 ; previous changeid: 3217451 ; current changeid: 3217452 ; change data1682350594|UNLINK(325773,_journalctl):326153

changelog_ml.0.mfs: change1682350594|UNLINK(325773,_journalctl):326153

filename: changelog_ml.0.mfs ; current meta version: 3217453 ; previous changeid: 3217452 ; current changeid: 3217453 ; change data1682350594|UNLINK(325773,_hostnamectl):326152

changelog_ml.0.mfs: change1682350594|UNLINK(325773,_hostnamectl):326152

filename: changelog_ml.0.mfs ; current meta version: 3217454 ; previous changeid: 3217453 ; current changeid: 3217454 ; change data1682350594|UNLINK(325773,_curl):326151

changelog_ml.0.mfs: change1682350594|UNLINK(325773,_curl):326151

filename: changelog_ml.0.mfs ; current meta version: 3217455 ; previous changeid: 3217454 ; current changeid: 3217455 ; change data1682350594|UNLINK(325773,_busctl):326150

changelog_ml.0.mfs: change1682350594|UNLINK(325773,_busctl):326150

filename: changelog_ml.0.mfs ; current meta version: 3217456 ; previous changeid: 3217455 ; current changeid: 3217456 ; change data1682350594|UNLINK(325773,_bootctl):326149

changelog_ml.0.mfs: change1682350594|UNLINK(325773,_bootctl):326149

filename: changelog_ml.0.mfs ; current meta version: 3217457 ; previous changeid: 3217456 ; current changeid: 3217457 ; change data1682350594|UNLINK(313473,vendor-completions):325773

changelog_ml.0.mfs: change1682350594|UNLINK(313473,vendor-completions):325773
```
</details>

#### Note

I do not have such issue when I stop the `mfsmaster` during the `rsync`.

It looks like removing files is much more sensitive.

**Comment by baby-gnu** [comment]
> Did you try WITHOUT -xx? Are there any error messages, or is the process just working and taking a lot of CPU? If it's the latter, how long did you wait for it to complete?

No error, it's a test bed so I only have my `/usr`.

The start of the logs is:

```
loading metadata ...
found valid metadata file: metadata.mfs.empty (version: 1)
found valid metadata file: metadata_ml.mfs.back.1 (version: 3230313 ; id: 64414D6881386D89)
found invalid metadata file (wrong header): metadata.crc
found valid metadata file: metadata.mfs.back.1 (version: 3259697 ; id: 64414D6881386D89)
found valid metadata file: metadata_ml.mfs.back.2 (version: 2920563 ; id: 64414D6881386D89)
found valid metadata file: metadata_ml.mfs.back.3 (version: 2920563 ; id: 64414D6881386D89)
found valid metadata file: metadata_ml.mfs.back (version: 3259697 ; id: 64414D6881386D89)
found valid metadata file: metadata.mfs (version: 3259697 ; id: 64414D6881386D89)
chosen most recent metadata file: metadata.mfs.back.1 (version: 3259697 ; id: 64414D6881386D89)
loading sessions data ... ok (0.0000)
loading storage classes data ... ok (0.0000)
loading objects (files,directories,etc.) ... ok (0.1522)
loading names ... ok (0.2530)
loading deletion timestamps ... ok (0.0015)
loading quota definitions ... ok (0.0000)
loading xattr data ... ok (0.0000)
loading posix_acl data ... ok (0.0000)
loading open files data ... ok (0.0000)
loading flock_locks data ... ok (0.0000)
loading posix_locks data ... ok (0.0000)
loading chunkservers data ... ok (0.0000)
loading chunks data ... ok (0.1170)
checking filesystem consistency ... ok
connecting files and chunks ... ok
all inodes: 270896
directory inodes: 2
file inodes: 270894
chunks: 270568
skipping changelog file: changelog_ml_back.1.mfs (changes: ??? - ???)
using changelog file: changelog_ml.0.mfs (changes: 3259697 - 3564466)
skipping changelog file: changelog_ml.1.mfs (changes: 3244768 - 3259696)
skipping changelog file: changelog.4.mfs (changes: 2593709 - 2631558)
skipping changelog file: changelog_ml_back.0.mfs (changes: ??? - ???)
filename: changelog_ml.0.mfs ; current meta version: 3259697 ; previous changeid: 3259696 ; current changeid: 3259697 ; change data1682353320|CREATE(2,usr,2,511,18,0,0,0):326173

changelog_ml.0.mfs: change1682353320|CREATE(2,usr,2,511,18,0,0,0):326173
[...]
```

in my last test, the logs stop at a lines:

```
filename: changelog_ml.0.mfs ; current meta version: 3549085 ; previous changeid: 3549084 ; current changeid: 3549085 ; change data1682353481|UNLINK(346981,vendor-completions):359282

changelog_ml.0.mfs: change1682353481|UNLINK(346981,vendor-completions):359282
```

and the process eat 100% CPU without any new logs.

I started the process in a screen and I'll see tomorrow how things are going.

Thanks.

**Comment by baby-gnu** [comment]
> I started the process in a screen and I'll see tomorrow how things are going.

Still the same, eating 100% CPU and no progress in the logs.

**Comment by chogata** [comment]
Since 3.0.115 we fixed one bug related to the restore process. It was a rare occurrence when it activated, nevertheless it's possible it is affecting you. Please, upgrade to the latest version (3.0.117) and try again.

**Comment by baby-gnu** [comment]
Ok, I tried the same configuration on Debian Bookworm using [moosefs 3.0.117](https://tracker.debian.org/pkg/moosefs) and it's working fine.

Thanks.
