### ISSUE TITLE
docker volume plugin

### ISSUE THREAD

**Issue by tivvit** [moosefs/moosefs#54]
Hi, do you have any plans for docker volume plugin?
It would be awesome.

**Comment by oszafraniec** [comment]
Witam,

W dniach 4-17 maja przebywam na urlopie. W sprawach pilnych proszę o kontakt z Mikołajem Benesz (mikolaj.benesz@webdev.pl, tel. 505123893).

Pozdrawiam
Oskar Szafraniec
WEBdev

**Comment by oxide94** [comment]
@tivvit, @muhh - please check [this](https://github.com/moosefs/moosefs-docker-cluster) out!

**Comment by tivvit** [comment]
@oxide94 that is really nice, but I was talking about something else.

I was talking about Docker volume plugin, which means you can mount MooseFs in Docker image (like this https://infinit.sh/documentation/docker/volume-plugin)

I am willing to help

**Comment by oxide94** [comment]
@karolmajek FYI

**Comment by oxide94** [comment]
@tivvit, oh of course you're right, I've just somehow omitted "volume" while reading your post :)

**Comment by oxide94** [comment]
Hi @tivvit,
please see this: https://github.com/moosefs/docker-volume-moosefs.
Tests and comments are appreciated!

Thanks,
Best regards,
Peter / MooseFS Team

**Comment by tivvit** [comment]
Wow! Great job, I will try that and let you know

**Comment by antoinetran** [comment]
Thank you for the job! I will try to test it in a few days. But after reading the README, there are some behaviors I do not understand yet, in the scenario:

1. that /mnt/moosefs exist but is not mounted and we create the container
2. that /mnt/moosefs does not exist and we create the container
3. that /mnt/moosefs is mounted, we have a container mapped to this, but we then have a MooseFs client crash
4. that /mnt/moosefs is mounted, we create a container mapped to /mnt/moosefs/subdir1 that does not exist?
5. that we have a MooseFs client in a container in our project, and no Mfs rpm installed in host, and we create the container

In anycase I will also try to answer this in my future tests.

**Comment by oxide94** [comment]
@karolmajek, can you please answer @antoinetran questions?
@antoinetran please share with us your tests results and if you would have further questions, we will be happy to help!

Thanks,
Peter / MooseFS Team

**Comment by karolmajek** [comment]
Finally I was able to answer your questions @antoinetran about scenarios

<h2>Scenarios</h2>
<p>In following scenarios we are using directory&nbsp;<code>/mnt/moosefs</code> for sake of simplicity. You can mount your MooseFS storage in any directory you want to.</p>
<p>In all scenarios MooseFS Docker Cluster is used:&nbsp;<a href="https://github.com/moosefs/moosefs-docker-cluster">https://github.com/moosefs/moosefs-docker-cluster</a></p>
<h3>MooseFS should be mounted to create a volume</h3>
<p>Directory <code>/mnt/moosefs</code>&nbsp;exist but is not mounted and we create the container</p>
<h4>Preconditions</h4>
<ul>
<li>Empty directory exists:&nbsp;<code>/mnt/moosefs</code></li>
<li>MooseFS is not mounted on host</li></ul>
<h5>Empty directory exists:&nbsp;/mnt/moosefs</h5>
<p>Command:</p><pre>ls -l /mnt/moosefs</pre>
<p>outputs:</p><pre>total 0</pre>
<p>The result of</p><pre>tree /mnt/</pre>
<p>is</p><pre>/mnt/
└── moosefs

1 directory, 0 files</pre>
<h5>MooseFS is not mounted on host</h5>
<p>Command&nbsp;&nbsp;<code>mount | grep moosefs</code>&nbsp;&nbsp;gives no results, so there are no mounts available</p>
<h4>Expected result</h4>
<p>Error, volume should not be created</p>
<h4>Actual result</h4>
<p>If we will try to create a volume we will get following error:</p><pre>docker volume create -d moosefs --name mymoosefs -o mountpoint=/mnt/moosefs
Error response from daemon: create mymoosefs: VolumeDriver.Create: Cannot create volume /mnt/moosefs as it's not a valid MooseFS mount</pre>
<p><br /></p>
<hr />
<h3>Can't create volume when mount directory doesn't exist</h3>
<p>Directory <code>/mnt/moosefs</code>&nbsp;does not exist and we create the container</p>
<h4>Preconditions</h4>
<ul>
<li>Directory <code>/mnt/moosefs</code>&nbsp;doesn't exist</li></ul>
<h5>Directory doesn't exist:&nbsp;/mnt/moosefs</h5>
<p>Command:</p><pre>ls -l /mnt</pre>
<p>outputs:</p><pre>total 0</pre>
<p>The result of</p><pre>tree /mnt</pre>
<p>is</p><pre>0 directory, 0 files</pre>
<h4>Expected result</h4>
<p>Error, volume should not be created</p>
<h4>Actual result</h4>
<p>If we will try to create a volume we will get following error:</p><pre>docker volume create -d moosefs --name mymoosefs -o mountpoint=/mnt/moosefs
Error response from daemon: create mymoosefs: VolumeDriver.Create: Cannot create volume /mnt/moosefs as it's not a valid MooseFS mount</pre>
<hr />
<h4>MooseFS Client killed when volume is mounted</h4>
<p>MooseFS is mounted in /mnt/moosefs, we have a volume mapped, but we then have a MooseFs client crash</p>
<h4>Preconditions</h4>
<ul>
<li>Directory <code>/mnt/moosefs</code>&nbsp;exist</li>
<li>MooseFS is mounted in /mnt/moosefs</li>
<li>Docker Volume is attached to /mnt/moosefs</li>
<li>Run container using volume</li>
<li>MooseFS Client is killed</li></ul>
<h5>Directory exists:&nbsp;/mnt/moosefs</h5>
<p>Command:</p><pre>ls -l /mnt/moosefs</pre>
<p>outputs:</p><pre>total 0</pre>
<p><span style="color: rgb(112,112,112);font-weight: bold;"><br />MooseFS is mounted in /mnt/moosefs</span></p>
<p>Command&nbsp;</p><pre>mount | grep moosefs</pre>
<p>gives following result:</p><pre>mfsmaster:9421 on /mnt/moosefs type fuse.mfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)</pre>
<p>The result of</p><pre>tree /mnt/</pre>
<p>is</p><pre>/mnt/
└── moosefs
    └── welcome_to_moosefs.txt

1 directory, 1 file</pre>
<h5>Docker Volume is attached to /mnt/moosefs</h5>
<p>Volume is mounted using following command:</p><pre>docker volume create -d moosefs --name mymoosefs -o mountpoint=/mnt/moosefs</pre>
<p>Response:</p><pre>mymoosefs</pre>
<p>List volumes:</p><pre>docker volume ls
DRIVER              VOLUME NAME
moosefs             mymoosefs</pre>
<h5>Run container using volume</h5>
<p>Run example nginx container which will mount&nbsp;</p><pre>docker run -ti -v mymoosefs:/usr/share/nginx/html -p 10080:80 nginx:latest bash -c "service nginx start;bash"</pre>
<h5>MooseFS Client is killed</h5><pre>sudo killall -9  mfsmount</pre>
<h4>Expected result</h4>
<p><br /></p>
<h4>Actual result</h4>
<p>If we will try to list files in the container: (volume is mounted in&nbsp;/usr/share/nginx/html)</p><pre>ls -l /usr/share/nginx/html
ls: cannot access '/usr/share/nginx/html': Transport endpoint is not connected</pre>
<p><br /></p>
<hr />
<h4>Attempt to use subdirectory as volume</h4>
<p>MooseFS is mounted in /mnt/moosefs, we create a container mapped to /mnt/moosefs/subdir1 that does not exist</p>
<h4>Preconditions</h4>
<ul>
<li>Directory <code>/mnt/moosefs</code>&nbsp;exists</li>
<li>MooseFS is mounted in /mnt/moosefs</li>
<li>/mnt/moosefs/subdir1 doesn't exist</li></ul>
<h5>Directory exists:&nbsp;/mnt/moosefs</h5>
<p>Command:</p><pre>ls -l /mnt/moosefs</pre>
<p>outputs:</p><pre>total 0</pre>
<h5><span style="color: rgb(112,112,112);">MooseFS is mounted in /mnt/moosefs</span></h5>
<p>Command&nbsp;</p><pre>mount | grep moosefs</pre>
<p>gives following result:</p><pre>mfsmaster:9421 on /mnt/moosefs type fuse.mfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)</pre>
<p>The result of</p><pre>tree /mnt/</pre>
<p>is</p><pre>/mnt/
└── moosefs
    └── welcome_to_moosefs.txt

1 directory, 1 file</pre>
<h5>/mnt/moosefs/subdir1 doesn't exist</h5>
<p>List files of&nbsp;/mnt/moosefs/subdir1 to check if it exist:</p><pre>ls -l /mnt/moosefs/subdir1
ls: cannot access '/mnt/moosefs/subdir1': No such file or directory</pre>
<h4>Expected result</h4>
<p>Error, volume should not be created</p>
<h4>Actual result</h4>
<p>If we will try to create a volume we will get following error:</p><pre>docker volume create -d moosefs --name mymoosefs -o mountpoint=/mnt/moosefs/subdir1
Error response from daemon: create mymoosefs: VolumeDriver.Create: Cannot create volume /mnt/moosefs/subdir1 as it's not a valid MooseFS mount
</pre>
<p><br /></p>
<hr />
<h4>No MooseFS Client on host machine</h4>
<p>MooseFS Client is installed and mounted in a container, and no MooseFS package is installed in host, and we create the container</p>
<p>MooseFS Client is required on host machine for now, we plan to provide Docker Volume Plugin which will not need installing additional packages on host machine. The plugin will be a client for MooseFS</p>
