### ISSUE TITLE
[BUG] fuse: bad mount point `/matrix/synapse/storage/media-store/': Input/output error

### ISSUE THREAD

**Issue by PC-Admin** [moosefs/moosefs#545]
## Have you read through available documentation, open Github issues and Github Q&A Discussions?

Yes

## System information

Debian 12 Bookworm
Virtual machine on Proxmox 8

#### Your moosefs version and its origin (moosefs.com, packaged by distro, built from source, ...).
```
root@matrix:~# sudo apt search moosefs-client
Sorting... Done
Full Text Search... Done
moosefs-client/stable,now 3.0.117-1 amd64 [installed]
  MooseFS - client tools and mount utility

root@matrix:~# sudo apt search fuse3
Sorting... Done
Full Text Search... Done
fuse3/stable,now 3.14.0-4 amd64 [installed]
  Filesystem in Userspace (3.x version)

libfuse3-3/stable,now 3.14.0-4 amd64 [installed,automatic]
  Filesystem in Userspace (library) (3.x version)
```

#### Operating system (distribution) and kernel version.

Debian 12 Bookworm
Kernel: 6.1.0-10-amd64

#### Hardware / network configuration, and underlying filesystems on master, chunkservers, and clients.

10.1.1.1/16 network
Chunkservers have XFS bricks.

#### How much data is tracked by moosefs master (order of magnitude)?

 - All fs objects: 8304019
 - Total space: 147TiB
 - Free space: 82TiB
 - RAM used: 2.3GB
 - last metadata save duration: 2.3s

## Describe the problem you observed.

Attempting to mount with the following fstab configuration:
```
# media-store MooseFS Mount
mfsmount /matrix/synapse/storage/media-store/ fuse mfsmaster=mfsmaster.perthchat.org,mfsdelayedinit,_netdev,noexec,rw,mfspassword=REDACTED
```
But I get this error when attempting to access it:
```
root@matrix:~# ls /matrix/synapse/storage/media-store/
ls: cannot access '/matrix/synapse/storage/media-store/': Input/output error
```
Strangely unmounting and re-mounting manually generated no errors:
```
root@matrix:~# mfsmount -H mfsmaster.perthchat.org -P REDACTED -o noexec,rw,mfsdelayedinit,_netdev /matrix/synapse/storage/media-store/
```
But then any attempt to access that mountpoint generates this error:
```
root@matrix:~# ls -la /matrix/synapse/storage/
ls: cannot access '/matrix/synapse/storage/media-store': Input/output error
total 8
drwxr-x--- 3 matrix matrix 4096 Jul 22 00:26 .
drwxr-x--- 7 matrix matrix 4096 Jul 22 00:26 ..
d????????? ? ?      ?         ?            ? media-store
root@matrix:~# sudo umount -l /matrix/synapse/storage/media-store/
root@matrix:~# ls -la /matrix/synapse/storage/media-store/
total 8
drwxr-x--- 2 matrix matrix 4096 Jul 22 00:26 .
drwxr-x--- 3 matrix matrix 4096 Jul 22 00:26 ..
```

#### Can you reproduce it? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

I'm not sure how to reproduce this, but it's not the first time I've seen it on my network...

#### Include any warning/errors/backtraces from the system logs.

The mfs-master isn't returning any log messages at all when attempting to mount this.

Could use some help, been wrestling with this all day and I'm still clueless about why it's failing. I do have other systems that are mounting this MooseFS here, but today I'm quite unlucky it seems. :S

**Comment by jkiebzak** [comment]
Is the export correct in mfsexport.cfg?

**Comment by PC-Admin** [comment]
Ahhh... I love it when it's something easy, I had just forgotten the `,mfssubfolder=/media-store` parameter in the fstab line.

Thank you! :)
