### ISSUE TITLE
hdd_delayed_ops: file:/foo/bar.mfs - fsync (direct call) error: EBADF (Bad file descriptor)

### ISSUE THREAD

**Issue by marcin-github** [moosefs/moosefs#55]
Hi!
I've added chunkserver to MooseFs cluster, Moosefs started rebalance. After a couple of minutes I changed option:
from HDD_FSYNC_BEFORE_CLOSE = 0 to 1
and I did reload chunkserver. Then I got in log this:

May 12 14:09:46 chunk1 systemd[1]: Reloading LSB: Start moosefs-chunkserver at boot time.
May 12 14:09:46 chunk1 moosefs-chunkserver[25644]: Reloading moosefs-chunkserver:
May 12 14:09:46 chunk1 mfschunkserver[25650]: set gid to 118
May 12 14:09:46 chunk1 moosefs-chunkserver[25644]: reload signal has been sent
May 12 14:09:46 chunk1 mfschunkserver[25650]: set uid to 112
May 12 14:09:46 chunk1 mfschunkserver[25352]: reloading config files
May 12 14:09:46 chunk1 mfschunkserver[25352]: main server module: socket address hasn't changed (*:9422)
May 12 14:09:46 chunk1 systemd[1]: Reloaded LSB: Start moosefs-chunkserver at boot time.
May 12 14:09:46 chunk1 mfschunkserver[25352]: reloading hdd data ...
May 12 14:09:46 chunk1 mfschunkserver[25352]: hdd space manager: folder /var/lib/mfs/sdd4/ didn't change
May 12 14:09:46 chunk1 mfschunkserver[25352]: hdd space manager: folder /var/lib/mfs/sdc4/ didn't change
May 12 14:09:46 chunk1 mfschunkserver[25352]: hdd space manager: folder /var/lib/mfs/sdb4/ didn't change
May 12 14:09:46 chunk1 mfschunkserver[25352]: hdd space manager: folder /var/lib/mfs/sda4/ didn't change
May 12 14:09:46 chunk1 mfschunkserver[25352]: hdd_delayed_ops: file:/var/lib/mfs/sdb4//00/chunk_0000000000001C40_00000001.mfs - fsync (direct call) error: EBADF (Bad file descriptor)
May 12 14:09:46 chunk1 mfschunkserver[25352]: hdd_delayed_ops: file:/var/lib/mfs/sdd4//00/chunk_0000000000003AC0_00000001.mfs - fsync (direct call) error: EBADF (Bad file descriptor)
May 12 14:09:46 chunk1 mfschunkserver[25352]: hdd_delayed_ops: file:/var/lib/mfs/sdb4//00/chunk_0000000000004E00_00000001.mfs - fsync (direct call) error: EBADF (Bad file descriptor)
[...]
May 12 14:09:47 chunk1 mfschunkserver[25352]: hdd_delayed_ops: file:/var/lib/mfs/sdd4//00/chunk_000000000000717F_00000001.mfs - fsync (direct call) error: EBADF (Bad file descriptor)
May 12 14:09:50 chunk1 mfschunkserver[25352]: connecting ...
May 12 14:09:50 chunk1 mfschunkserver[25352]: connected to Master

**Comment by marcin-github** [comment]
Moosefs version 3.0.92

**Comment by xandrus** [comment]
Hi.
Thank you for this information we have to check it.

**Comment by xandrus** [comment]
Hi,
I would like to inform you that problem was solved in MooseFS version 3.0.94.
For more information please look at feb265c0e8f1d55c81502c46188e749facfbe731 commit.
