### ISSUE TITLE
Metalogger restart bug: metadata files miss

### ISSUE THREAD

**Issue by OraCheung** [moosefs/moosefs#56]
Hi:
    I used HostA for mfsmaster, HostB for mfsmetalogger. Sometimes when I stop the mfsmetalogger, clean the /var/lib/mfs(remove change log files and metadata files), restart the metalogger, I found that metadata files miss: 
    ls -lh    
    total 4.0K    
    -rw-r----- 1 mfs mfs 2.4K 5May  15 17:25 changelog_ml.0.mfs

But sometimes it work well:
    ls -lh
    total 36M
    -rw-r----- 1 mfs mfs 1.7K 5May  15 17:49 changelog_ml.0.mfs
    -rw-r----- 1 mfs mfs 1.4K 5May   15 17:47 changelog_ml_back.0.mfs
    -rw-r----- 1 mfs mfs  16K 5May  15 17:47 changelog_ml_back.1.mfs
    -rw-r----- 1 mfs mfs  36M 5May   15 17:47 metadata_ml.mfs.back

How can I fix this bug?
As follows:
mfsmetalogger version: 3.0.92-1
mfsmetalogger.cfg:  default config

Thanks for your help !

**Comment by xandrus** [comment]
Hi.

First of all.
All metalogger metdetadata files are rotating and number of change log files can be set in metalogger configuration file.

`# number of metadata change log files (default is 50)`
`# BACK_LOGS = 50`

Secondly.
Metalloger by default downloads metadata file from MooseFS master once every 24 hours. 

Check /etc/mfs/metalogger.cfg file:
`# metadata download frequency in hours (default is 24, should be at least BACK_LOGS/2)`
`# META_DOWNLOAD_FREQ = 24`

You can also change number of previous metadata files.
`# number of previous metadata files to be kept (default is 3)`
`# BACK_META_KEEP_PREVIOUS = 3`

**Comment by OraCheung** [comment]
META_DOWNLOAD_FREQ "at least" or "at most" ?
When I:  man mfsmetalogger.cfg 
META_DOWNLOAD_FREQ
              metadata download frequency in hours (default is 24, at most BACK_LOGS/2)
When I: vim mfsmetalogger
             # metadata download frequency in hours (default is 24, should be at least BACK_LOGS/2)
             # META_DOWNLOAD_FREQ = 24

**Comment by OraCheung** [comment]
And the first question is: 
    When I restart metalogger, most will download all the files, but rarely will not download. When meet the situation not downloading the metadata files, it will never be able to download, unless  restart the mfsmaster. I  think that the 'META_DOWNLOAD_FREQ'  will not affect at the time restart the metalogger.
