### ISSUE TITLE
ext4 on loop device on file placed on mooosefs has some troubles

### ISSUE THREAD

**Issue by marcin-github** [moosefs/moosefs#57]
Hi!
kernel-4.10.1, mfsmount-3.0.92.
Steps to reproduce:
\# dd if=/dev/zero of=/mnt/mfsfs/file
\# losetup -f /mnt/mfsfs/file

\# losetup -l 
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE              DIO
/dev/loop0         0      0         0  0 /mnt/mfsfs/file   0

next steps:
\# mkfs.ext4 /dev/loop0
\# mount /dev/loop0 /mnt/something
(now kernel do lazy inode initializations)
and I'm getting:
May 17 18:28:25 server kernel: [464213.298379] EXT4-fs (loop0): mounted filesystem with ordered data mode. Opts: (null)
May 17 18:28:28 server kernel: [464216.057319] blk_update_request: I/O error, dev loop0, sector 5272
May 17 18:28:28 server kernel: [464216.325325] blk_update_request: I/O error, dev loop0, sector 9264
May 17 18:28:29 server kernel: [464216.589312] blk_update_request: I/O error, dev loop0, sector 13264
May 17 18:28:29 server kernel: [464216.853267] blk_update_request: I/O error, dev loop0, sector 17264
May 17 18:28:29 server kernel: [464217.117344] blk_update_request: I/O error, dev loop0, sector 21264
May 17 18:28:30 server kernel: [464217.381262] blk_update_request: I/O error, dev loop0, sector 25264
May 17 18:28:30 server kernel: [464217.641227] blk_update_request: I/O error, dev loop0, sector 29264
May 17 18:28:30 server kernel: [464217.901286] blk_update_request: I/O error, dev loop0, sector 33264
May 17 18:28:30 server kernel: [464218.161457] blk_update_request: I/O error, dev loop0, sector 37264
[...]

**Comment by xandrus** [comment]
Thank you for this information.
We will check what is going on and return to this topic as fast as it is possible.

**Comment by zcalusic** [comment]
FWIW, I see the same behaviour, kernel 4.11.0, moosefs 3.0.92

I believe this worked properly a few versions before (maybe 3.0.86).

**Comment by xandrus** [comment]
Thank you for this information.

**Comment by xandrus** [comment]
I would like to update you according to blk_update_request: I/O error.

It looks like this information is some kind of kernel only problem.

Inside MooseFS all operations are executed correctly. 
We are able to read and write to loop device stored on MooseFS without any problems.

You can try to check loop device with fsck to confirm that all is ok.
`fsck -pvcf /dev/loop0`

We are still trying to find the real source of this problem.

**Comment by alexcrow** [comment]
Confirmed on 3.0.92 on kernel 4.4.59-1.el7.elrepo.x86_64:
[582361.093080] blk_update_request: 20 callbacks suppressed
[582361.093083] blk_update_request: I/O error, dev loop0, sector 12632320
[582361.270983] blk_update_request: I/O error, dev loop0, sector 12636416
[582361.449061] blk_update_request: I/O error, dev loop0, sector 12640512
[582361.624969] blk_update_request: I/O error, dev loop0, sector 12644608
[582361.800963] blk_update_request: I/O error, dev loop0, sector 16777472
[582361.977045] blk_update_request: I/O error, dev loop0, sector 16781568
[582362.152980] blk_update_request: I/O error, dev loop0, sector 16785664

**Comment by oxide94** [comment]
@alexcrow,
Does this issue still occur on MooseFS 3.0.97 or newer?

Best regards,
Peter / MooseFS Team

**Comment by zcalusic** [comment]
MooseFS 3.0.100, Linux kernel 4.14.17, I still see the errors. But, they're slightly different and there's only 2 of them (small 2GB test file used, might make a difference).
```
Feb 08 14:03:00 kernel: print_req_error: I/O error, dev loop0, sector 0
Feb 08 14:03:29 kernel: print_req_error: I/O error, dev loop0, sector 2320
```

**Comment by borkd** [comment]
Any updates on this?

**Comment by acid-maker** [comment]
This problem is not connected with moosefs. I was able to reproduce this using sshfs. Problem lies in the kernel/fuse.

```
# mount
(...)
XXXXXX on /mnt/sshfs type fuse.sshfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0)

# truncate -s 5242880000 /mnt/sshfs/loopfile_trunc
# losetup --find --show /mnt/sshfs/loopfile_trunc
/dev/loop0
# mkfs.ext4 /dev/loop0
(...)
# mount /dev/loop0 /mnt/loop_trunc
# cd /mnt/loop_trunc/
# sysbench --test=fileio prepare
(...)
# sysbench --test=fileio --file-test-mode=rndrw run
(...)

```
And I have this in my logs:
```
Mar 28 07:26:08 ts03 kernel: [186430.387229] blk_update_request: I/O error, dev loop0, sector 0
Mar 28 07:26:09 ts03 kernel: [186431.684983] EXT4-fs (loop0): mounted filesystem with ordered data mode. Opts: (null)
Mar 28 07:26:11 ts03 kernel: [186433.103268] blk_update_request: I/O error, dev loop0, sector 2784
Mar 28 07:26:11 ts03 kernel: [186433.885659] blk_update_request: I/O error, dev loop0, sector 6768
Mar 28 07:26:12 ts03 kernel: [186434.665941] blk_update_request: I/O error, dev loop0, sector 10768
Mar 28 07:26:13 ts03 kernel: [186435.448914] blk_update_request: I/O error, dev loop0, sector 14768
Mar 28 07:26:14 ts03 kernel: [186436.235378] blk_update_request: I/O error, dev loop0, sector 18768
Mar 28 07:26:14 ts03 kernel: [186437.015842] blk_update_request: I/O error, dev loop0, sector 22768
Mar 28 07:26:15 ts03 kernel: [186437.796657] blk_update_request: I/O error, dev loop0, sector 26768
Mar 28 07:26:16 ts03 kernel: [186438.593180] blk_update_request: I/O error, dev loop0, sector 30768
Mar 28 07:26:17 ts03 kernel: [186439.374980] blk_update_request: I/O error, dev loop0, sector 34768
Mar 28 07:26:18 ts03 kernel: [186440.156070] blk_update_request: I/O error, dev loop0, sector 38768
(...)

```
BTW. Even though kernel reports all those I/O errors it looks that it works correctly - sysbench finished tests without any errors on both sshfs and moosefs.
