### ISSUE TITLE
chunkservers disconnected  

### ISSUE THREAD

**Issue by Damien9527** [moosefs/moosefs#58]
May 19 05:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 19 05:50:47 mfsmaster1 mfsmaster[7027]: structure check loop
May 19 06:00:10 mfsmaster1 mfsmaster[7027]: chunkserver disconnected - ip: 10.39.3.31 / port: 9432, usedspace: 8577627512832 (7988.54 GiB), totalspace: 21471015026688 (19996.44 GiB)
May 19 06:00:10 mfsmaster1 mfsmaster[7027]: chunkserver disconnected - ip: 10.39.54.216 / port: 9432, usedspace: 13889893072896 (12935.97 GiB), totalspace: 35651799744512 (33203.33 GiB)
May 19 06:00:10 mfsmaster1 mfsmaster[7027]: chunkserver disconnected - ip: 10.39.3.32 / port: 9432, usedspace: 8400027738112 (7823.14 GiB), totalspace: 21190198624256 (19734.91 GiB)
May 19 06:00:10 mfsmaster1 mfsmaster[7027]: chunkserver disconnected - ip: 10.39.54.217 / port: 9432, usedspace: 13890211258368 (12936.27 GiB), totalspace: 35651799744512 (33203.33 GiB)
May 19 02:12:04 mfsmaster1 mfsmaster[7027]: structure check loop
May 19 03:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 19 03:00:06 mfsmaster1 mfsmaster[7027]: child finished
May 19 03:52:48 mfsmaster1 mfsmaster[7027]: (10.39.54.215:9432 -> 10.39.54.219:9432) chunk: 00000000020A43EA replication status: Wrong chunk version
May 19 04:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 19 04:00:09 mfsmaster1 mfsmaster[7027]: child finished
May 19 04:00:09 mfsmaster1 mfsmaster[7027]: store process has finished - store time: 7.428
May 19 04:01:29 mfsmaster1 mfsmaster[7027]: structure check loop
May 19 04:56:06 mfsmaster1 mfsmaster[7027]: structure check loop
May 19 05:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 19 05:50:47 mfsmaster1 mfsmaster[7027]: structure check loop
May 19 06:00:10 mfsmaster1 mfsmaster[7027]: chunkserver disconnected - ip: 10.39.3.31 / port: 9432, usedspace: 8577627512832 (7988.54 GiB), totalspace: 21471015026688 (19996.44 GiB)
May 19 06:00:10 mfsmaster1 mfsmaster[7027]: chunkserver disconnected - ip: 10.39.54.216 / port: 9432, usedspace: 13889893072896 (12935.97 GiB), totalspace: 35651799744512 (33203.33 GiB)
May 19 05:50:47 mfsmaster1 mfsmaster[7027]: structure check loop
May 19 06:00:10 mfsmaster1 mfsmaster[7027]: chunkserver disconnected - ip: 10.39.3.31 / port: 9432, usedspace: 8577627512832 (7988.54 GiB), totalspace: 21471015026688 (19996.44 GiB)
May 19 06:00:10 mfsmaster1 mfsmaster[7027]: chunkserver disconnected - ip: 10.39.54.216 / port: 9432, usedspace: 13889893072896 (12935.97 GiB), totalspace: 35651799744512 (33203.33 GiB)
May 19 06:00:10 mfsmaster1 mfsmaster[7027]: chunkserver disconnected - ip: 10.39.3.32 / port: 9432, usedspace: 8400027738112 (7823.14 GiB), totalspace: 21190198624256 (19734.91 GiB)
May 19 06:00:10 mfsmaster1 mfsmaster[7027]: chunkserver disconnected - ip: 10.39.54.217 / port: 9432, usedspace: 13890211258368 (12936.27 GiB), totalspace: 35651799744512 (33203.33 GiB)
May 19 06:00:10 mfsmaster1 mfsmaster[7027]: store process has finished - store time: 9.289
May 19 06:00:10 mfsmaster1 mfsmaster[7027]: csdb: found cs using ip:port and csid (10.39.54.219:9432,5)
May 19 06:00:10 mfsmaster1 mfsmaster[7027]: csdb: found cs using ip:port and csid (10.39.3.32:9432,9)
May 19 06:00:10 mfsmaster1 mfsmaster[7027]: csdb: found cs using ip:port and csid (10.39.54.215:9432,2)
May 19 06:00:10 mfsmaster1 mfsmaster[7027]: connection with client(ip:10.39.0.107) has been closed by peer
May 19 06:00:10 mfsmaster1 mfsmaster[7027]: csdb: found cs using ip:port and csid (10.39.54.218:9432,8)
May 19 06:00:11 mfsmaster1 mfsmaster[7027]: chunkserver register end (packet version: 6) - ip: 10.39.54.215 / port: 9432
May 19 06:00:11 mfsmaster1 mfsmaster[7027]: connection with client(ip:10.39.5.131) has been closed by peer
May 19 06:00:11 mfsmaster1 mfsmaster[7027]: connection with client(ip:10.39.4.104) has been closed by peer
May 19 06:00:11 mfsmaster1 mfsmaster[7027]: connection with client(ip:10.39.3.85) has been closed by peer
May 19 06:00:11 mfsmaster1 mfsmaster[7027]: connection with client(ip:10.39.5.221) has been closed by peer
May 19 06:00:12 mfsmaster1 mfsmaster[7027]: connection with client(ip:10.39.3.117) has been closed by peer
May 19 06:00:12 mfsmaster1 mfsmaster[7027]: csdb: found cs using ip:port and csid (10.39.3.31:9432,3)
May 19 06:00:12 mfsmaster1 mfsmaster[7027]: chunkserver register begin (packet version: 6) - ip: 10.39.3.31 / port: 9432, usedspace: 8577627512832 (7988.54 GiB), totalspace: 21471015026688 (19996.44 GiB)
May 19 06:00:13 mfsmaster1 mfsmaster[7027]: csdb: found cs using ip:port and csid (10.39.3.30:9432,1)
May 19 06:00:13 mfsmaster1 mfsmaster[7027]: chunkserver register begin (packet version: 6) - ip: 10.39.3.30 / port: 9432, usedspace: 8221502128128 (7656.87 GiB), totalspace: 20718595727360 (19295.70 GiB)
May 19 06:00:14 mfsmaster1 mfsmaster[7027]: csdb: found cs using ip:port and csid (10.39.54.217:9432,4)
May 19 06:00:14 mfsmaster1 mfsmaster[7027]: chunkserver register begin (packet version: 6) - ip: 10.39.54.217 / port: 9432, usedspace: 13890211258368 (12936.27 GiB), totalspace: 35651799744512 (33203.33 GiB)
May 19 06:00:14 mfsmaster1 mfsmaster[7027]: csdb: found cs using ip:port and csid (10.39.54.216:9432,7)
May 19 06:00:14 mfsmaster1 mfsmaster[7027]: chunkserver register begin (packet version: 6) - ip: 10.39.54.216 / port: 9432, usedspace: 13889893072896 (12935.97 GiB), totalspace: 35651799744512 (33203.33 GiB)
May 19 06:00:15 mfsmaster1 mfsmaster[7027]: server ip: 10.39.54.217 / port: 9432 has been fully removed from data structures
May 19 06:00:15 mfsmaster1 mfsmaster[7027]: server ip: 10.39.3.32 / port: 9432 has been fully removed from data structures
May 19 06:00:15 mfsmaster1 mfsmaster[7027]: server ip: 10.39.54.218 / port: 9432 has been fully removed from data structures
May 19 06:00:15 mfsmaster1 mfsmaster[7027]: server ip: 10.39.3.30 / port: 9432 has been fully removed from data structures
May 19 06:00:15 mfsmaster1 mfsmaster[7027]: server ip: 10.39.54.216 / port: 9432 has been fully removed from data structures
May 19 06:00:15 mfsmaster1 mfsmaster[7027]: server ip: 10.39.54.219 / port: 9432 has been fully removed from data structures
May 19 06:00:15 mfsmaster1 mfsmaster[7027]: server ip: 10.39.54.215 / port: 9432 has been fully removed from data structures
May 19 06:00:15 mfsmaster1 mfsmaster[7027]: server ip: 10.39.3.31 / port: 9432 has been fully removed from data structures
May 19 06:00:17 mfsmaster1 mfsmaster[7027]: chunkserver register end (packet version: 6) - ip: 10.39.3.32 / port: 9432
May 19 06:00:17 mfsmaster1 mfsmaster[7027]: chunkserver register end (packet version: 6) - ip: 10.39.3.31 / port: 9432
May 19 06:00:17 mfsmaster1 mfsmaster[7027]: chunkserver register end (packet version: 6) - ip: 10.39.3.30 / port: 9432
May 19 06:00:19 mfsmaster1 mfsmaster[7027]: chunkserver register end (packet version: 6) - ip: 10.39.54.218 / port: 9432
May 19 06:00:19 mfsmaster1 mfsmaster[7027]: chunkserver register end (packet version: 6) - ip: 10.39.54.219 / port: 9432
May 19 06:00:20 mfsmaster1 mfsmaster[7027]: chunkserver register end (packet version: 6) - ip: 10.39.54.217 / port: 9432
May 19 06:00:20 mfsmaster1 mfsmaster[7027]: chunkserver register end (packet version: 6) - ip: 10.39.54.216 / port: 9432
May 19 06:00:37 mfsmaster1 mfsmaster[7027]: (10.39.54.215:9432 -> 10.39.54.219:9432) chunk: 00000000020C6E82 replication status: Wrong chunk version

rencently  in am  06    ,  this error appeared .  I have test the network , that goes well ,  I don't know what should I do the take care of this  .

also in the chunkserver like this :

May 19 06:00:09 localhost mfsmount[3669]: master: tcp recv error: ETIMEDOUT (Operation timed out) (header)
May 19 06:00:10 localhost mfschunkserver[26420]: masterconn: connection timed out
May 19 06:00:10 localhost mfsmount[3669]: master: register error (read header: ETIMEDOUT (Operation timed out))
May 19 06:00:11 localhost mfsmount[3669]: master: register error (read header: ETIMEDOUT (Operation timed out))
May 19 06:00:14 localhost mfsmount[3669]: master: register error (read header: ETIMEDOUT (Operation timed out))
May 19 06:00:15 localhost mfschunkserver[26420]: connecting ...
May 19 06:00:15 localhost mfschunkserver[26420]: connected to Master
May 19 06:00:15 localhost mfsmount[3669]: master: register error (read header: ETIMEDOUT (Operation timed out))
May 19 06:00:17 localhost mfsmount[3669]: registered to master
May 19 06:10:27 localhost mfschunkserver[26420]: connect to 10.39.54.215:9432 failed, error: ETIMEDOUT (Operation timed out)
May 19 06:14:48 localhost mfschunkserver[26420]: connect to 10.39.54.215:9432 failed, error: ETIMEDOUT (Operation timed out)
May 19 06:14:54 localhost mfschunkserver[26420]: connect to 10.39.54.215:9432 failed, error: ETIMEDOUT (Operation timed out)
May 19 06:16:27 localhost mfschunkserver[26420]: connect to 10.39.54.215:9432 failed, error: ETIMEDOUT (Operation timed out)
May 19 06:20:11 localhost mfschunkserver[26420]: connect to 10.39.3.30:9432 failed, error: ETIMEDOUT (Operation timed out)
May 19 06:24:32 localhost mfschunkserver[26420]: connect to 10.39.3.30:9432 failed, error: ETIMEDOUT (Operation timed out)

**Comment by xandrus** [comment]
Hi,
please check if you have enough RAM for fork process.
Each hour MooseFS master dumps metadata file on hard disk.

This happens each hour so please check if you have enabled over commit memory in your system:

`# echo 1 > / proc /sys/vm/ overcommit_memory`

Please read about this case in our documentation - page 47:
https://moosefs.com/Content/Downloads/moosefs-3-0-users-manual.pdf

**Comment by xandrus** [comment]
How thing are going?
Can you update us according to this topic?

**Comment by Damien9527** [comment]
HI  @xandrus 

     I have change the overcommit  options ,but it seems not work .

cat /proc/sys/vm/overcommit_memory
1

free -g
             total       used       free     shared    buffers     cached
Mem:            62         62          0          0          4         48
-/+ buffers/cache:         10         52
Swap:            7          0          7
