### ISSUE TITLE
data sync problems

### ISSUE THREAD

**Issue by perlbox** [moosefs/moosefs#60]
I have two question about moosefs data sync.
1). Suppose I have two chunkserver Machine A and B, and A shutdown. while A halted, There are some operation to MFS filesystem,such as add some files, modify some files.  When A start again, I found  it spent some minutes(5-10min) to get the changed data  on Machine A.  Is there and parameter or option to make the data sync quickly ?

2). Suppose I have two mooseFS Cluster: C and D, I want to sync data from  C to D close to  real-time,     I try scp and rsync, I found when the data becomes too large, it doesn't work. Is there some way to make the data sync quickly?

**Comment by Sveeeeeen** [comment]
1). Take a look into mfsmaster.cfg. You can adjust "REPLICATIONS_DELAY_INIT". 

2). What do you mean with "doesnt work"? rsync should be a good choice.

**Comment by xandrus** [comment]
@perlbox
Would you be so kind and tell us something more about your configuration, operating systems, network configuration, latency between MooseFS components.

Which MooseFS version we are talking about?
If you are talking about two clusters it means that:
A) you have two phisically separate MooseFS instances?
B) you have two MooseFS clients mouted to the one MooseFS master?


And one more thing - what do you mean under statement "to make the data sync quickly"

**Comment by oxide94** [comment]
@perlbox,
Regarding your second question and rsync, you can use the tool I attached to [this message](https://sourceforge.net/p/moosefs/mailman/message/36263443/) called `mfsrecentfiles.py` (or use [this permalink](https://sourceforge.net/p/moosefs/mailman/attachment/77228BFD-204F-4E77-8B22-4E0CA34FFC91%40moosefs.com/1/) to the attachment).

It should be helpful in listing recently modified files.

Thanks,
Best regards,
Peter / MooseFS Team

**Comment by 4Dolio** [comment]
Sorry for many otherwise pointless replies, but it is because I can almost do these things, want to remember, hope to read my comments and intentionally try these things... the mentioned .py script and it's gust specifically..
