### ISSUE TITLE
Not able to reshare  MooseFS/OSXFUSE mounts through AppleFileServer (AFP)

### ISSUE THREAD

**Issue by rajava2010** [moosefs/moosefs#61]
We are trying to build distributed file server cluster using MooseFS / OSXFUSE  and reshare the moosefs mount through AFP to clients. Through Server app we were able to share the mounts but when we are connecting from the client, the mount or the shared folder is not visible, for some reason AppleFileServer is not able to server the files. We checked the permissions, ACL’s , etc which seems ok we were able to even switch to root and access through terminal but only through AFP we couldn’t access. Is there any other way we can re-share the mooseFS mount point through SMB/AFP ?
 
We are trying this is on Mac OX Sierra 10.12.4 / Server (5.3.1).

**Comment by xandrus** [comment]
Hi.
We have one question.
Why you want to use AFP gate if you can use native MooseFS client on all OSX computers?

According to SAMBA. You can easy set MooseFS - SAMBA gate on MooseFS chunk server with MooseFS client. Samba re-share is used only for Windows Clients. But right now we have native Windows Client for Windows operating systems too.

**Comment by rajava2010** [comment]
Hi,


Why you want to use AFP gate if you can use native MooseFS client on all
OSX computers?

     -- We don't have MooseFS Client on all OS X Computers, we wanted to
have few AFP FileServers mounted through moosefs client and then serve
through them as we have about 2000 iMacs and growing and we didn't want to
install MooseFS Client and OSXFUSE on all, Also setting the permissions at
the group level through openDirectory seemed easier through Mac Server
application. We are still struggling to set OpenDirectory level group/users
permissions on the export and mount through mooseFS (Any doc in that aspect
will be helpful as well).


According to SAMBA. You can easy set MooseFS - SAMBA gate on MooseFS chunk
server with MooseFS client. Samba re-share is used only for Windows
Clients. But right now we have native Windows Client for Windows operating
systems too.

   -- Can you send more information on this ? Unfortunately we are 99% Mac
OS X Shop, if the only way is  to go through Windows, we can definitely
give it a try through SMB.

Thanks
-Raja

**Comment by xandrus** [comment]
Hi.
Would you be so kind and try to mount MooseFS client without xattr support and do some tests.

`mfsmount -o mfsnoxattrs -H mfsmaster.your.domain /mfs/mount/point`

Right now we are trying to trace the source of the problem.
When we find something interesting we will inform you.

**Comment by rajava2010** [comment]
No luck , even though -o mfsnoxattrs is set, AFP is still not able to
serve, although it removed the xattr (com.apple.system.Security) from the
folder (IT)

*With -o mfsnoxattrs:*

xattr newmfs/IT


*Without -o mfsnoxattrs :*

xattr newmfs/IT

com.apple.system.Security


Please advise , I hope you can re-create the problem so that it's easier to
debug. Let me know if you wanted us to try anything else.

**Comment by rajava2010** [comment]
Any luck on finding the issue ? we are still struggling , if we don't get
it fixed in a day or 2 we might have to go different DFS ? Please help.

**Comment by xandrus** [comment]
I would like to inform you that we ware able to reshared MooseFS with AFP.
Our test was looking like that:

On Mac1 with OSX 10.12 we have mounted MooseFS with -o mfsnoxattrs inside home folder ~/mfs.
Than we have reshared home folder with enabling "File sharing" from Sharing pane.
On Mac2 we have connectd to Mac1 and we ware able to explore MooseFS files.

Can you send us system logs and MooseFS ophistory:
`cat /mnt/mfs/.ophistory`

**Comment by rajava2010** [comment]
Hi Aleksander,
                It's surprising that you are able to get it work, but still
we are not able to . attaching the ophistory, Also the folder under the MFS
mount doesn't have "Share" option , this is how it looks for us as show
below, please advise.

[image: Inline image 1]

**Comment by acid-maker** [comment]
Ups. You are right. I'm Macintosh user since the year 1991 and AFP always was the default protocol in Mac OS and then OS X, so I assumed that still is. I was surprised today when I've found out that now the default protocol in Mac OS X is SMB !!!.

With Alex we checked sharing using default settings, so we have checked SMB not AFP.

I will check it again now using AFP, but it is possible that the problem lies in incompatibilities between OSXFUSE and AFP, not MFS itself. I'll let you know.

**Comment by rajava2010** [comment]
ok, We are even ok serving files with SMB as long as we can share the
files, let us now how you how Alex did it (Some STEP by STEP instructios
with screenshots will really help)

**Comment by xandrus** [comment]
It should be easy to set SMB access only:

- Open server app
- Go to Services > File Sharing
- Select folder
- Click the pencil
- Remove selection from AFP check box

![image](https://user-images.githubusercontent.com/13887484/28163384-341b9630-67cb-11e7-93f0-96f9f753057f.png)

**Comment by rajava2010** [comment]
ok , We did it and it seems to work to explore, but when ACL's applied from
OpenDirectory at group level or user level, it doesn't allow people to
login. but we can see the ACL's on the file, we also added new attribute
 -o extended_security to the mfsmount (without it we were not able to apply
ACL's )

mfsmount  mfssecure/ -p -o mfsnoxattrs -o extended_security -H
server.domain.com


we tried enabling the below, but no luck , We are almost close to solving
but this had become a blocker, thanks for your help so far.

 sudo defaults write
/Library/Preferences/SystemConfiguration/com.apple.smb.server AclsEnabled
-bool YES

sudo serveradmin stop smb

sudo serveradmin start smb

**Comment by SIN3R6Y** [comment]
Can you remove "-o mfsnoxattrs" now that you are using smb? Pretty sure OpenDirectory needs xattrs.

**Comment by rajava2010** [comment]
We tried but no luck, we can't share the folders, for some reason SMB
doesn't like the mounted mooseFS or the OSXFUSE. Here are some debug logs,
please help :(.

**Comment by rajava2010** [comment]
I meant it was allowing to login provided client machine is also configured with the same OD but the permissions of users and groups applied on the moosefs folders is not taking effect but works
Fine in the regular OS X file system

**Comment by borkd** [comment]
Is this still an issue?

**Comment by borkd** [comment]
@rajava2010 - could you attach a link to gist with an automated/scripted way to replicate this problem? Thanks!
