### ISSUE TITLE
[BUG] MooseFS Master on Debian Trixie doesn't start

### ISSUE THREAD

**Issue by doloopuntil** [moosefs/moosefs#618]
## Have you read through available documentation, open Github issues and Github Q&A Discussions?

Yes – I followed the [step-by-step guide](https://moosefs.com/Content/Downloads/moosefs-installation.pdf) and searched for the specific error message without luck.

#### Your moosefs version and its origin (moosefs.com, packaged by distro, built from source, ...).
version: 4.56.6-1 ; build: 1850, packaged by distro

#### Operating system (distribution) and kernel version.
Debian Trixie (testing), kernel `6.11.10-amd64`

#### Hardware / network configuration, and underlying filesystems on master, chunkservers, and clients.
Mini PC, Intel N100, 16GB RAM. Master installed on ext4 partition, metadata stored on ext4 filesystem managed separately by mdadm (RAID1). Ownership of metadata directory set to `mfs:mfs` 

#### How much data is tracked by moosefs master (order of magnitude)?
Fresh install, no data.

## Describe the problem you observed.
I cannot start `mfsmaster`. 

`> sudo mfsmaster`

```
open files limit has been set to: 16384
working directory: /mnt/mfs/meta
lockfile created and locked
initializing mfsmaster modules ...
mfscsipmap configuration file (/etc/mfs/mfsipmap.cfg) not found - no chunkserver ip mappings
exports file has been loaded
mfstopology configuration file (/etc/mfs/mfstopology.cfg) not found - network topology not defined
loading metadata ...
can't find metadata.mfs - try using option '-a'
init: metadata manager failed !!!
error occurred during initialization - exiting
doloopuntil@footprints:~$
```

So I ran:

`> sudo mfsmaster -a`
```
open files limit has been set to: 16384
working directory: /mnt/mfs/meta
lockfile created and locked
initializing mfsmaster modules ...
mfscsipmap configuration file (/etc/mfs/mfsipmap.cfg) not found - no chunkserver ip mappings
exports file has been loaded
mfstopology configuration file (/etc/mfs/mfstopology.cfg) not found - network topology not defined
loading metadata ...
can't find valid metadata file
init: metadata manager failed !!!
error occurred during initialization - exiting
```
#### Can you reproduce it? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Yes, I can reproduce the same behavior using a metadata directory created in the root filesystem (`/tmp/mfs/meta`, no mdadm RAID). 

#### Include any warning/errors/backtraces from the system logs.
No relevant system logs.

**Comment by xandrus** [comment]
Hi,

It doesn't look like a bug! I suspect you have a different metadata path defined in the mfsmaster.cfg file.
It looks as follows: /mnt/mfs/meta. By default all metadata related files are installed in the `/var/lib/mfs` folder.

Try copying `metadata.mfs.empty` into the metadata folder. So:
```
cp /var/lib/mfs/metadata.mfs.empty /mnt/mfs/meta/metadata.mfs
```
Or run this command:
```
echo -n "MFSM NEW" > /mnt/mfs/meta/metadata.mfs
```
And than start MooseFS master process: `mfsmaster start`

**Remember that this command will remove all information from the metadata!
You mentioned that this is a fresh installation, so in your case everything should be fine.
