### ISSUE TITLE
mfs erro log 

### ISSUE THREAD

**Issue by Damien9527** [moosefs/moosefs#62]
Hi ,
    I got some erro message from the logs:
1、mfsmount[7481]: high packet travel time between client and master (2.078529s) - ignoring in time sync
2、
mfsmount[6256]: file: 9436409, index: 0, chunk: 48783629, version: 1, cs: 0A27031E:9432 - readblock error (try counter: 0)
mfsmount[6256]: readblock; unknown message
mfsmount[6256]: file: 9436409, index: 0, chunk: 48783629, version: 1, cs: 0A2736D8:9432 - readblock error (try counter: 0)
mfsmount[6256]: readblock; unknown message
mfsmount[6256]: file: 9436409, index: 0, chunk: 48783629, version: 1, cs: 0A27031E:9432 - readblock error (try counter: 0)
mfsmount[6256]: readblock; unknown message
mfsmount[6256]: file: 8197545, index: 0, chunk: 44560660, version: 1, cs: 0A2736DA:9432 - readblock error (try counter: 0)
mfsmount[6256]: readblock; unknown message
mfsmount[6256]: file: 8197545, index: 0, chunk: 44560660, version: 1, cs: 0A27031D:9432 - readblock error (try counter: 0)
mfsmount[6256]: readblock; unknown message
mfsmount[6256]: file: 8197545, index: 0, chunk: 44560660, version: 1, cs: 0A27031D:9432 - readblock error (try counter: 0)
mfsmount[6256]: file: 9403132, index: 0, chunk: 49320757, version: 1 - writeworker: connection with (0A270320:9432) was reset by peer (unfinished writes: 2; try counter: 3)
mfsmount[6256]: file: 8000634, index: 0, chunk: 49095224, version: 1 - writeworker: connection with (0A2736DA:9432) was reset by peer (unfinished writes: 2; try counter: 1)
mfsmount[6256]: file: 9783448, index: 0, chunk: 49289621, version: 1 - writeworker: connection with (0A27031F:9432) was reset by peer (unfinished writes: 2; try counter: 2)
mfsmount[6256]: file: 9803892, index: 0, chunk: 49324335, version: 1 - writeworker: connection with (0A270320:9432) was reset by peer (unfinished writes: 2; try counter: 1)
mfsmount[6256]: file: 9056565, index: 0, chunk: 49315798, version: 1 - writeworker: connection with (0A27031D:9432) was reset by peer (unfinished writes: 2; try counter: 1)
mfsmount[6256]: file: 9783448, index: 0, chunk: 49289621, version: 1 - writeworker: connection with (0A2736DA:9432) was reset by peer (unfinished writes: 2; try counter: 3)
 

3、
 mfscli   -H 10.39.2.243     -SMC -b cpu -b scpu -b ucpu -b setattr -b write
+-----------------------------------------------------------------------------------------------------------------------------------------------+
|                                                               Master chart data                                                               |
+------------------+----------------------------+------------------+----------------+------------------------------+----------------------------+
|   host/port ->   |           leader           |      leader      |     leader     |            leader            |           leader           |
+------------------+----------------------------+------------------+----------------+------------------------------+----------------------------+
|       Time       | Cpu usage (total sys+user) | System cpu usage | User cpu usage | Number of setattr operations | Number of write operations |
+------------------+----------------------------+------------------+----------------+------------------------------+----------------------------+
| 2017-07-07 14:49 |                    115.34% |           86.51% |         28.83% |                   1755.817/s |                  223.750/s |
| 2017-07-07 14:48 |                    113.69% |           84.95% |         28.74% |                   2150.433/s |                  220.600/s |
| 2017-07-07 14:47 |                    118.47% |           88.51% |         29.96% |                   3165.117/s |                  192.283/s |
| 2017-07-07 14:46 |                    115.91% |           86.99% |         28.92% |                   2447.717/s |                  221.983/s |
| 2017-07-07 14:45 |                    116.79% |           86.81% |         29.98% |                   2498.300/s |                  184.850/s |
| 2017-07-07 14:44 |                    116.70% |           87.21% |         29.49% |                   2461.617/s |                  209.967/s |
| 2017-07-07 14:43 |                    117.96% |           88.20% |         29.76% |                   2532.950/s |                  265.433/s |
| 2017-07-07 14:42 |                    115.59% |           86.35% |         29.25% |                   3461.567/s |                  307.917/s |
| 2017-07-07 14:41 |                    126.32% |           92.55% |         33.77% |                   6863.933/s |                  376.750/s |
| 2017-07-07 14:40 |                    123.53% |           91.39% |         32.15% |                   4533.267/s |                  433.133/s |
| 2017-07-07 14:39 |                    117.79% |           88.18% |         29.61% |                   2564.850/s |                  383.383/s |

questions:
what dose setattr operations  means ?   chown  、chmod  operation ?
the cpu high load is caused by the heavy setattr operations ? 

Thanks.

**Comment by xandrus** [comment]
Hi.
First question.
Which version you are using right now? Is it 3.0.94?

**Comment by Damien9527** [comment]
Hi, @xandrus    
    verion : 3.0.85

**Comment by xandrus** [comment]
Are you sure that mfsmount is running in 3.0.85 version?
Syslog looks like mfsmount 2.0.41 or older.

Please execute this command and send us result:

`df -i`

**Comment by Damien9527** [comment]
Hi，@xandrus 
      some  mfsclients  version are   1.6.25   ,others are  3.0.92 ， master and chunkserver is 3.0.85 .
      
 df -i
Filesystem            Inodes   IUsed   IFree IUse% Mounted on
/dev/sda1            1048576   41123 1007453    4% /
/dev/sdb1            720240640  692227 719548413    1% /data0
/dev/sda6            2098720  211220 1887500   11% /var
/dev/sda5            2097152   19831 2077321    1% /tmp
/dev/sda3            3670016  244405 3425611    7% /usr
tmpfs                12373632       1 12373631    1% /dev/shm
mfs#10.39.0.252:9421 1001157583  151558 1001006025    1% /mnt/mfs3
mfs#10.39.0.248:9431/online  1010711796 7703295 1003008501    1% /mnt/mfs2
 

  Also  sometimes  , some clients  appear  
' ll /mnt/mfs2/xxx/svnbase/netdev/recommend/crelr/target
 ls： /mnt/mfs2/xxx/svnbase/netdev/recommend/crelr/target: No such file or directory'

but in other clients .   it work well .

**Comment by xandrus** [comment]
Hi.
First of all please update all old clients like 1.6.25. I would like to add that MooseFS 1.6 support has ended long time ago.
Good idea is to update MooseFS to latest stable version - 3.0.94

**Comment by xandrus** [comment]
Hi.
How things are going?
Do you have some updates?
