### ISSUE TITLE
mfsscadmin /mountpoint throws Segmentation fault

### ISSUE THREAD

**Issue by marcin-github** [moosefs/moosefs#63]
Hi!
On debian (proxmox 5) I have segfault when I run `mfsscadmin /mountpoint` without additional arguments throws segfault:
`# mfsscadmin /mnt/mfs-x/`
`Segmentation fault`

in dmesg:
`[5449515.984491] mfsscadmin[26762]: segfault at 0 ip 00007f6bdecf7782 sp 00007ffc74d24e38 error 4 in libc-2.24.so[7f6bdec68000+195000]`

**Comment by xandrus** [comment]
Hi.
I will check it, but I'm sure that we have fixed this bug long time ago.

**Comment by xandrus** [comment]
OK.
Now I see. We have fixed this problem in upcoming MooseFS 4.0 that's why I thought that problem was also solved in 3.0 branch.

Fixed by 0df2c1b87febd7c6ba17f8b29c0c8de6ac2d9e8c

**Comment by marcin-github** [comment]
Thank you!
