### ISSUE TITLE
mfschunkserver system log

### ISSUE THREAD

**Issue by wudigailun** [moosefs/moosefs#65]
Hi.
     I have a question
`mfschunkserver  -v
version: 3.0.95-1`

`cat /etc/redhat-release 
CentOS release 6.8`

`uname -r
2.6.32-642.el6.x86_64`

`df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda3       112G  1.1G  106G   2% /
tmpfs            16G     0   16G   0% /dev/shm
/dev/sda1       190M   35M  146M  20% /boot
/dev/sdb        3.7T  810G  2.7T  23% /data

 df -i
Filesystem        Inodes    IUsed     IFree IUse% Mounted on
/dev/sda3        7462912    30564   7432348    1% /
tmpfs            4095223        1   4095222    1% /dev/shm
/dev/sda1          51200       39     51161    1% /boot
/dev/sdb       248119632 23232067 224887565   10% /data`

`cat /var/log/message
Aug  2 19:40:36 localhost mfschunkserver[3368]: hdd_io_begin: file:/data/chunkserver_data//6F/chunk_0000000002C1D4C2_00000001.mfs - open error: ENOSPC (No space left on device)
Aug  2 19:40:36 localhost kernel: EXT4-fs warning (device sdb): ext4_dx_add_entry: Directory index full!
Aug  2 19:41:20 localhost kernel: EXT4-fs warning (device sdb): ext4_dx_add_entry: Directory index full!
Aug  2 19:41:20 localhost mfschunkserver[3368]: hdd_io_begin: file:/data/chunkserver_data//6F/chunk_0000000002C1FCEE_00000001.mfs - open error: ENOSPC (No space left on device)
Aug  2 19:41:20 localhost kernel: EXT4-fs warning (device sdb): ext4_dx_add_entry: Directory index full!
Aug  2 19:41:20 localhost kernel: EXT4-fs warning (device sdb): ext4_dx_add_entry: Directory index full!
Aug  2 19:41:20 localhost kernel: EXT4-fs warning (device sdb): ext4_dx_add_entry: Directory index full!
Aug  2 19:41:20 localhost kernel: EXT4-fs warning (device sdb): ext4_dx_add_entry: Directory index full!
Aug  2 19:41:27 localhost kernel: EXT4-fs warning (device sdb): ext4_dx_add_entry: Directory index full!
Aug  2 19:41:27 localhost kernel: EXT4-fs warning (device sdb): ext4_dx_add_entry: Directory index full!
Aug  2 19:41:27 localhost mfschunkserver[3368]: hdd_io_begin: file:/data/chunkserver_data//6F/chunk_0000000002C2026D_00000001.mfs - open error: ENOSPC (No space left on device)
Aug  2 19:41:27 localhost kernel: EXT4-fs warning (device sdb): ext4_dx_add_entry: Directory index full!
Aug  2 19:41:27 localhost kernel: EXT4-fs warning (device sdb): ext4_dx_add_entry: Directory index full!
Aug  2 19:41:27 localhost kernel: EXT4-fs warning (device sdb): ext4_dx_add_entry: Directory index full!
Aug  2 19:41:50 localhost kernel: EXT4-fs warning (device sdb): ext4_dx_add_entry: Directory index full!
Aug  2 19:41:50 localhost kernel: EXT4-fs warning (device sdb): ext4_dx_add_entry: Directory index full!
Aug  2 19:41:50 localhost kernel: EXT4-fs warning (device sdb): ext4_dx_add_entry: Directory index full!
Aug  2 19:41:50 localhost kernel: EXT4-fs warning (device sdb): ext4_dx_add_entry: Directory index full!
Aug  2 19:41:50 localhost mfschunkserver[3368]: hdd_io_begin: file:/data/chunkserver_data//6F/chunk_0000000002C2190A_00000001.mfs - open error: ENOSPC (No space left on device)
Aug  2 19:41:50 localhost kernel: EXT4-fs warning (device sdb): ext4_dx_add_entry: Directory index full!
Aug  2 19:42:03 localhost kernel: EXT4-fs warning (device sdb): ext4_dx_add_entry: Directory index full!
Aug  2 19:42:03 localhost kernel: EXT4-fs warning (device sdb): ext4_dx_add_entry: Directory index full!
Aug  2 19:42:03 localhost mfschunkserver[3368]: hdd_io_begin: file:/data/chunkserver_data//6F/chunk_0000000002C22341_00000001.mfs - open error: ENOSPC (No space left on device)
Aug  2 19:42:03 localhost kernel: EXT4-fs warning (device sdb): ext4_dx_add_entry: Directory index full!
Aug  2 19:42:03 localhost kernel: EXT4-fs warning (device sdb): ext4_dx_add_entry: Directory index full!
Aug  2 19:42:03 localhost kernel: EXT4-fs warning (device sdb): ext4_dx_add_entry: Directory index full!
Aug  2 19:42:48 localhost kernel: EXT4-fs warning (device sdb): ext4_dx_add_entry: Directory index full!
Aug  2 19:42:48 localhost kernel: EXT4-fs warning (device sdb): ext4_dx_add_entry: Directory index full!
Aug  2 19:42:48 localhost kernel: EXT4-fs warning (device sdb): ext4_dx_add_entry: Directory index full!
Aug  2 19:42:48 localhost mfschunkserver[3368]: hdd_io_begin: file:/data/chunkserver_data//6F/chunk_0000000002C24A29_00000001.mfs - open error: ENOSPC (No space left on device)
Aug  2 19:42:48 localhost kernel: EXT4-fs warning (device sdb): ext4_dx_add_entry: Directory index full!
Aug  2 19:42:48 localhost kernel: EXT4-fs warning (device sdb): ext4_dx_add_entry: Directory index full!
Aug  2 19:43:29 localhost kernel: EXT4-fs warning (device sdb): ext4_dx_add_entry: Directory index full!
Aug  2 19:43:29 localhost kernel: EXT4-fs warning (device sdb): ext4_dx_add_entry: Directory index full!
Aug  2 19:43:29 localhost kernel: EXT4-fs warning (device sdb): ext4_dx_add_entry: Directory index full!
Aug  2 19:43:29 localhost kernel: EXT4-fs warning (device sdb): ext4_dx_add_entry: Directory index full!
Aug  2 19:43:29 localhost mfschunkserver[3368]: hdd_io_begin: file:/data/chunkserver_data//6F/chunk_0000000002C26F13_00000001.mfs - open error: ENOSPC (No space left on device)`

I was in the client,Execute the command 'du -sh /  directory',chunkserver ---->That's the problem
What causes this?

**Comment by xandrus** [comment]
This problem is connected with your file system not with MooseFS.
Please check EXT4 filesystem consistency. 
Please consider to do format block device with 4k block size or change filesystem.
