### ISSUE TITLE
How can I determine if the metalogger is up to speed or if it's lagging behind?

### ISSUE THREAD

**Issue by weirdbricks** [moosefs/moosefs#67]
Hi folks,

I'm wondering if there is a way to determine if a metalogger is up to speed with the master or not? 

I'm looking for something similar to MySQL's "Seconds_Behind_Master: 0" (link with example: https://dev.mysql.com/doc/refman/5.7/en/replication-administration-status.html). 

How can I determine if a metalogger is "current" or not? 

Thanks!

**Comment by xandrus** [comment]
Hi,

We don't have such a tool or place where we can check it like that. It's rather feature request.

If you really wan to check if all is synchronized, you can always compare changelogs on master and metalogger.
