### ISSUE TITLE
mfsmount point lose 

### ISSUE THREAD

**Issue by zhs077** [moosefs/moosefs#73]
recently I found same machine mfsmout point lose, I search /var/log/messages, found the mfs info are "read workers: 0-"
how can i do?

**Comment by xandrus** [comment]
Hi.

Would you be so kind and tell us something more about this issue? MooseFS version, OS version, Fuse version.
Read workers :0 means that at this specific point of time worker usage dropped to 0. Nothing unusual.

Please check is you have enough RAM. It is possible that OOM killed mfsmount process.

**Comment by xandrus** [comment]
Any updates?
