### ISSUE TITLE
mfschunk cannot connect 

### ISSUE THREAD

**Issue by zhs077** [moosefs/moosefs#74]
master log:

Sep 29 16:57:28 mfsmaster[14326]: chunkserver disconnected - ip: 127.0.0.1.129 / port: 9422, usedspace: 3273105408 (3.05 GiB), totalspace: 35080790593536 (32671.53 GiB)
Sep 29 16:57:28 mfsmaster[14326]: server ip: 127.0.0.1.129 / port: 9422 has been fully removed from data structures
Sep 29 16:57:33 mfsmaster[14326]: chunkserver register begin (packet version: 6) - ip: 127.0.0.1.129 / port: 9422, usedspace: 3273105408 (3.05 GiB), totalspace: 35080790593536 (32671.53 GiB)
Sep 29 16:57:33 mfsmaster[14326]: connection with CS(127.0.0.1.129) has been closed by peer
Sep 29 16:57:33 mfsmaster[14326]: chunkserver disconnected - ip: 127.0.0.1.129 / port: 9422, usedspace: 3273105408 (3.05 GiB), totalspace: 35080790593536 (32671.53 GiB)
Sep 29 16:57:33 mfsmaster[14326]: server ip: 127.0.0.1.129 / port: 9422 has been fully removed from data structures
Sep 29 16:57:38 mfsmaster[14326]: chunkserver register begin (packet version: 6) - ip: 127.0.0.1.129 / port: 9422, usedspace: 3273105408 (3.05 GiB), totalspace: 35080790593536 (32671.53 GiB)
Sep 29 16:57:38 mfsmaster[14326]: connection with CS(127.0.0.1.129) has been closed by peer
Sep 29 16:57:38 mfsmaster[14326]: chunkserver disconnected - ip: 127.0.0.1.129 / port: 9422, usedspace: 3273105408 (3.05 GiB), totalspace: 35080790593536 (32671.53 GiB)
Sep 29 16:57:38 mfsmaster[14326]: server ip: 127.0.0.1.129 / port: 9422 has been fully removed from data structures

chunkservice log
Sep 29 16:34:33 mfschunkserver[10803]: connecting ...
Sep 29 16:34:33 mfschunkserver[10803]: connected to Master
Sep 29 16:34:33 mfschunkserver[10803]: MATOCS_MASTER_ACK - wrong meta data id. Can't connect to master
Sep 29 16:34:38 mfschunkserver[10803]: connecting ...
Sep 29 16:34:38 mfschunkserver[10803]: connected to Master
Sep 29 16:34:38 mfschunkserver[10803]: MATOCS_MASTER_ACK - wrong meta data id. Can't connect to master

**Comment by xandrus** [comment]
Hi,
Are you sure that you are connecting to correct master server?
This is protection to avoid connecting wrong chunkserevr to different MooseFS instance.

If you are 100% sure that this chunkserver was connected to this specific master server you can remove this files:
`/var/lib/mfs/chunkserverid.mfs`
 and 
`/mnt/[hdd mount point]/.metaid` file.
I mean .metaid file from all hard disks defined in /mnt/mfs/mfshdd.cfg file

**Please remember that if chunkserver was connected to different master all chunks will be treated as "unknown" and deleted.**

**Comment by zhs077** [comment]
I not found /var/lib/mfs this dir ,
/mnt/mfs/  dir not found  .metaid and  mfshdd.cfg file

**Comment by zhs077** [comment]
old master server is down, and I use a new master server

**Comment by xandrus** [comment]
Hi,
I mean hard disk defined in /etc/mfs/mfshdd.cfg file.

chunkserverid.mfs file should be in MooseFS chunkserver metadata path (DATA_PATH parameter in mfschunkserer.cfg file)

**Comment by zhs077** [comment]
thank you, I've solved it

**Comment by suntabu** [comment]
Hi,
I wanna deploy two masters with one instance for HA got the same error.

only one master running at the same time, once it's down, another backup master would handle the master work.

What should I do to keep two masters running properly?

**Comment by xandrus** [comment]
Hi,
Basically, if you want to use two or more master servers( MooseFS HA) you have to install all the components in the pro version.
Then you should add two A entries to your DNS server which should resolve mfsmaster name to two different IP addresses. Something like this:

`mfsmaster IN A 192.168.1.1`
`mfsmaster IN A 192.168.1.2`

And this is it.

Please remember that PRO version is not for free.

**Comment by suntabu** [comment]
OK, thanks for your info.
