### ISSUE TITLE
Can moosefs support k8s Persistent Volume

### ISSUE THREAD

**Issue by duffqiu** [moosefs/moosefs#75]
we know we can mount the path in container.

But can we use Persistent Volume provided by moosefs?

**Comment by xandrus** [comment]
Hi.
Would you be so kind and tell us little bit more about this case?

Are we talking about Docker containers?

**Comment by xandrus** [comment]
OK
I see :) Kubernetes
I'm blind :)

**Comment by xandrus** [comment]
Hi.
If you like to use Persistent Volume with MooseFS, you have to use HostPath in PV and PVC specification. Than you have to ensure that each node/worker has mounted MooseFS client in path specified in hostPath section.

If you like you can write us at support@moosefs.com and than we will start private thread.

**Comment by duffqiu** [comment]
I will try your suggestion, if any question, I will comment again
