### ISSUE TITLE
negative packet travel time between client and master

### ISSUE THREAD

**Issue by ivanabc** [moosefs/moosefs#76]
I find error log:

>  mfsmount[57396]: monotonic clock function: clock_gettime
 mfsmount[57396]: monotonic clock speed: 63576 ops / 10 mili seconds
...
>mfsmount[57396]: negative packet travel time between client and master - ignoring in time sync;
 current monotonic time: 1980896.021134 ; last monotonic time: 1980896.021134

send and receive sync monotic time are equal, why?

**Comment by xandrus** [comment]
Hi,

I have few questions according this weird behavior?
Is it a latest MooseFS version I mean - 3.0.97?
Do yo have some kind of NTP synchronization in you cluster?

**Comment by ivanabc** [comment]
[root@10-6-58-22-snsgz ~]# mfsmount -V
MFS version 3.0.97-1
FUSE library version: 2.9.2
fusermount version: 2.9.2

yes, the kind of ntp server is chrony

**Comment by xandrus** [comment]
Do you use mfsmount inside virtualized operating system?
I Would like to add that monotonic clock is not working with some Hipervisors.

According to "negative packet travel" entry in syslog. In this specific case caption is incorrect.
We will correct this information.

**Comment by ivanabc** [comment]
I think so. 
I don't find "negative packet travel" message  in physical machine.

**Comment by xandrus** [comment]
Would you be so kind and tell us what kind of hypervisor you are using.
We would like to repeat this issue in our development environment, so would you be so kind and tell us more information about your current configuration. Host OS - version, Hypervisor version?

**Comment by oxide94** [comment]
Fixed in 6fc3bb6

**Comment by ivanabc** [comment]
@xandrus os is "ubuntu 1404", kvm version is "QEMU emulator version 2.0.0"
