### ISSUE TITLE
Packages for Debian-9 "stretch" on ppa.moosefs.com?

### ISSUE THREAD

**Issue by kbarmen** [moosefs/moosefs#78]
Our current MooseFS clusters are running on Debian, and in a few month we want to upgrade our servers to Debian-9, aka "stretch". However, the package repository at ppa.moosefs.com has no packages for this distribution yet. I hope this will change soon? :)

**Comment by zcalusic** [comment]
I fully agree that Stretch labeled packages would be a welcome addition, Debian Stretch has been released months ago and is a current stable Debian. Jessie is now oldstable, in maintenance mode.

Having said that, @kbarmen you can use Jessie MooseFS packages on Stretch, no problem. At least I had no issues doing exactly that, for the last several months. MooseFS doesn't have many dependencies, so packages from the older distro work without any problems.

**Comment by oxide94** [comment]
Hi @kbarmen and @zcalusic,

yes, it is going to be fixed soon (i.e. in MooseFS 3.0.98). Packages with Debian Stretch support are almost ready, there are only small fixes to be made with `unit` / `@` files.

I hope next week we will finish it and after extensive testing (because there are also other issues fixed) I hope packages should be available by the end of this month, maybe sooner.

Thanks,
Peter / MooseFS Team

**Comment by kbarmen** [comment]
Excellent! Thanks for replying :)

**Comment by oxide94** [comment]
Hi @kbarmen and @zcalusic,

Debian 9 / Ubuntu 16.04 LTS support has been added in 993c813. MooseFS 3.0.99 will be released next week.

Best regards
Peter / MooseFS Team

**Comment by zcalusic** [comment]
Thank you for the heads up @oxide94, looking forward to test the new release. 👍

**Comment by oxide94** [comment]
Hi @kbarmen and @zcalusic,

Just wanted to inform, that MooseFS 3.0.99 has been released! :)

Best regards
Peter / MooseFS Team

**Comment by zcalusic** [comment]
@oxide94 just wanted to inform :) that 3.0.99 is already happily running on my (Debian stretch based) MooseFS cluster.

The new repo is allright, migration to systemd went flawless, there was no problem at all, very smooth ride.

Thank you for all good work and for keeping this great FS top notch! :+1:

**Comment by oxide94** [comment]
@zcalusic just wanted to inform :D your information is received :)

> The new repo is allright, migration to systemd went flawless, there was no problem at all, very smooth ride.
That's perfect, it should exactly be like this!

> Thank you for all good work and for keeping this great FS top notch! 👍
Thanks for good words about MooseFS, it's nice to hear our work is appreciated!

Best regards,
Peter / MooseFS Team
