### ISSUE TITLE
Is mkdir atomic over moosefs?

### ISSUE THREAD

**Issue by ivanabc** [moosefs/moosefs#79]

**Comment by xandrus** [comment]
Would you be so kind and tell us what do you mean "atomic mkdir".
How can mkdir operation be made not in atomic way?

**Comment by ivanabc** [comment]
Two mkdir operations are executed, which one will be successful?
Or which one operation first arrive mfsmaster, which one will be successful?

**Comment by xandrus** [comment]
One of them will be successful, second will return error - "File exists".
Successful will be one, which arrives first.

**Comment by ivanabc** [comment]
Thank you!
