### ISSUE TITLE
Clients loose access to data after introducing storage classes and modifying mfsexports 

### ISSUE THREAD

**Issue by marcinvp** [moosefs/moosefs#81]
After introducing storage classes to our cluster all our clients lost access to data. Remount fixes problem

Steps to reproduce it on fresh install:

chunkservers configured with label A
mfsscadmin create 1A sclass1
mfssetsclass -r  sclass1 /mnt/mfsroot
add new export  "192.168.1.9		/test	rw,alldirs,admin,maproot=0:0"
systemctl reload moosefs-master.service

tested on:
CentOS   7.4.1708
moosefs-cli-3.0.97-1.rhsystemd.x86_64
moosefs-client-3.0.97-1.rhsystemd.x86_64
moosefs-master-3.0.97-1.rhsystemd.x86_64
moosefs-chunkserver-3.0.97-1.rhsystemd.x86_64

**Comment by xandrus** [comment]
Hi.
I would like to inform you that we have fixed this problem few days ago.
New update will be available soon in source code and in packages.

**Comment by xandrus** [comment]
I would like to inform you that fix was made in 42530556bd7f99cdd2eb9ac3cf160fbc2bbb6fe5 commit
