### ISSUE TITLE
Is there a efficient way to do mfssetsclass recursively?

### ISSUE THREAD

**Issue by tclh123** [moosefs/moosefs#83]
When I do `mfssetsclass -r` on a large mfs cluster(37M files and 5M directories), the mfsmaster will hang, and it's not acceptable.
I can first `find` all files and directories on the cluster, and do `mfssetsclass` in batches. I wonder how many items each time, and what frequency is appropriate? Any better suggestions?

**Comment by xandrus** [comment]
MooseFS master makes this kind of operations in atomic way. So in such a case MooseFS master will be unresponsive. Right now there is no something like one good solution.
Good one is as you said, to use find command, but we have to keep about 100 operations/second to have MooseFS master responsive.

**Comment by tclh123** [comment]
Hello @xandrus , thanks for your response.

I wrote a script, and it works well. Basically, it consumes the `find` output, and when it find a directory which owns less than 1M inodes, do `mfssetclass -r` on it, otherwise don't do `-r`.
It can complete the whole sc ensuring process on my cluster in 6 minutes.

But now, I got another problem. After I finish the process,  which change goal 3 to my custom sc - 3c. There will be some chunk won't change immediately, but it will finally be 3c in the future.

- the resources dashboard just after I change the sc

![image](https://user-images.githubusercontent.com/1311043/34030538-7522f874-e1a8-11e7-91c1-50c383837ca9.png)

- one more day after, you can see 3 goal is decreased

![image](https://user-images.githubusercontent.com/1311043/34030631-c69fc0f6-e1a8-11e7-8378-795826fbdbb2.png)

@xandrus Do you know why? Are there some *lazy* sc change?

**Comment by oxide94** [comment]
Hi @tclh123,

remember, that you could have some of these files in trash (which had goal / SC "3") and they have been removed after default trash time (i.e. 24h).

You can mount trash and check what files are ther using:
`mfsmount -H mfsmaster.domain.name -m /mnt/mfsmeta`
If you are sure you don't have much files in trash, you can use this command:
`mfsmount -H mfsmaster.domain.name -o mfsflattrash -m /mnt/mfsmeta`

Best regards,
Peter / MooseFS Team

**Comment by tclh123** [comment]
Hello @oxide94 , thanks. It did looks like there're old sc files in the trash.
