### ISSUE TITLE
Moosefs mfsmaster   tcp recv error: ETIMEDOUT

### ISSUE THREAD

**Issue by linux-ops** [moosefs/moosefs#84]
details as the following:

Every day there will be be all the client connection timeout problem, I try to view the log and found that at about the hour, there will be a lot of time-out in the mfsmster log, I have been suspect that the network problem, but you can see from the log 127.0 .0.1 local connection failed, is not because my metadata is too large, in the dump memory to the hard disk, is not an I / O bottleneck led to the mfsmaster parent process communication? I observed the parent process problems when the process becomes D;

Metadata size: 14GB
mfsmaster version: version: 3.0.81
Server: physical machine
Memory: 200GB
enable overcommit_memory = 1

mfsmaster log

Dec 16 01:04:30 mfsmaster01 mfsmount [109153]: master: tcp recv error: ETIMEDOUT (Operation timed out) (header)
Dec 16 01:04:31 mfsmaster01 mfsmount [109153]: master: register error (read header: ETIMEDOUT (Operation timed out))
Dec 16 01:04:33 mfsmaster01 mfsmount [109153]: can not connect to master ("127.0.0.1": "9421")
Dec 16 01:04:37 mfsmaster01 mfsmount [109153]: can not connect to master ("127.0.0.1": "9421")
Dec 16 01:04:39 mfsmaster01 mfsmount [109153]: can not connect to master ("127.0.0.1": "9421")
Dec 16 01:04:43 mfsmaster01 mfsmount [109153]: can not connect to master ("127.0.0.1": "9421")
Dec 16 01:04:45 mfsmaster01 mfsmount [109153]: can not connect to master ("127.0.0.1": "9421")
Dec 16 01:04:49 mfsmaster01 mfsmount [109153]: can not connect to master ("127.0.0.1": "9421")
Dec 16 01:04:51 mfsmaster01 mfsmount [109153]: can not connect to master ("127.0.0.1": "9421")
Dec 16 01:04:55 mfsmaster01 mfsmount [109153]: can not connect to master ("127.0.0.1": "9421")
Dec 16 01:04:57 mfsmaster01 mfsmount [109153]: can not connect to master ("127.0.0.1": "9421")
Dec 16 01:05:01 mfsmaster01 mfsmount [109153]: can not connect to master ("127.0.0.1": "9421")
Dec 16 01:05:01 mfsmaster01 mfsmaster [3914]: main master server module: (ip: 10.212.0.233) write error: EPIPE (Broken pipe)

Dec 16 01:05:01 mfsmaster01 mfsmaster [3914]: connection with client (ip: 10.204.31.5) has been closed by peer
Dec 16 01:05:01 mfsmaster01 mfsmaster [3914]: connection with client (ip: 10.212.5.242) has been closed by peer
Dec 16 01:05:01 mfsmaster01 mfsmaster [3914]: connection with client (ip: 10.204.93.250) has been closed by peer
Dec 16 01:05:01 mfsmaster01 mfsmaster [3914]: connection with client (ip: 10.212.0.57) has been closed by peer
Dec 16 01:05:01 mfsmaster01 mfsmaster [3914]: connection with client (ip: 10.212.0.253) has been closed by peer
Dec 16 01:05:01 mfsmaster01 mfsmaster [3914]: connection with

client:

Dec 16 01:04:29 yum03 mfsmount [18628]: master: tcp recv error: ETIMEDOUT (Operation timed out) (header)
Dec 16 01:04:30 yum03 mfsmount [18628]: master: register error (read header: ETIMEDOUT (Operation timed out))
Dec 16 01:04:31 yum03 mfsmount [18628]: master: register error (read header: ETIMEDOUT (Operation timed out))
Dec 16 01:04:35 yum03 mfsmount [18628]: can not connect to master ("10.204.250.2": "9421")
Dec 16 01:04:37 yum03 mfsmount [18628]: can not connect to master ("10.204.250.2": "9421")
Dec 16 01:04:41 yum03 mfsmount [18628]: can not connect to master ("10.204.250.2": "9421")
Dec 16 01:04:43 yum03 mfsmount [18628]: can not connect to master ("10.204.250.2": "9421")
Dec 16 01:04:47 yum03 mfsmount [18628]: can not connect to master ("10.204.250.2": "9421")
Dec 16 01:05:01 yum03 mfsmount [18628]: can not connect to master ("10.204.250.2": "9421")
Dec 16 01:05:03 yum03 mfsmount [18628]: registered to maste

**Comment by linux-ops** [comment]
so update new  mfsmaster version?

**Comment by oxide94** [comment]
Hi @linux-ops,

Yes, first of all we definitely recommend to update Master Server (then also Chunkservers and Clients) to the newest version, i.e. 3.0.99. If your issue will persist, please let us know and we will try to help you further.

Thanks,

Best regards,
Peter / MooseFS Team

**Comment by linux-ops** [comment]
Okay, do you have any issues needing attention during the upgrade? Need to stop service first?

**Comment by linux-ops** [comment]
@oxide94  Okay, do you have any issues needing attention during the upgrade? Need to stop service first?

**Comment by Damien9527** [comment]
Maybe you should check the cpu usage of the master process. You can see it on the mfscgi ,or use mfscli

**Comment by oxide94** [comment]
@linux-ops,

Please check what I wrote in this comment: https://github.com/moosefs/moosefs/issues/99#issuecomment-373941160. I think it may be helpful also in your case.

Thanks,
Best regards,
Peter / MooseFS Team
