### ISSUE TITLE
mfsexports  problem

### ISSUE THREAD

**Issue by Damien9527** [moosefs/moosefs#86]
Version：mfs3.0.92 ，Centos6.5    

I want to cancle the premission in the mfsexports.cfg ,  when I  change  "10.39.3.109"  as a comment, the reload the mfsmaster process .   

10.39.3.1-10.39.3.107 	/	rw,alldirs,maproot=0,mintrashtime=1h30m,maxtrashtime=2w
**#10.39.3.109-10.39.3.250 /	rw,alldirs,maproot=0,mintrashtime=1h30m,maxtrashtime=2w**

the  mount point  on 10.39.3.85  also miss , I can find it .
  $ ps axu|grep mfsmount
root      8389  0.6  0.1 691984 148588 ?       S<sl Dec05 149:25 /usr/local/moosefs-3.0.92/bin/mfsmount -H 10.39.1.254 /mnt/mfs3

$ df -h|grep mfs

$ mount
/dev/sda1 on / type ext3 (rw)
 ...
**mfs#10.39.1.254:9421 on /mnt/mfs3 type fuse (rw,nosuid,nodev,allow_other)**

$ cat /etc/redhat-release
CentOS Linux release 7.1.1503 (Core)
 
the jobs run on mount point work  fine .   So ,how can I recovery it ?   It this a bug ?

**Comment by oxide94** [comment]
Hi @Damien9527,
I just wanted to let you know, that it was fixed in commit 4253055. The newest MooseFS 3.0.100 version doesn't have this issue. Thank you for your report.

Best regards,
Peter / MooseFS Team
