### ISSUE TITLE
Automatic maintenace mode

### ISSUE THREAD

**Issue by acid-maker** [moosefs/moosefs#9]
This is continuation of topic started in <#8>:

> This is my idea:
> 
> Chunkserver during graceful stop just before disconnection from master will send command that will turn on "temporary maintenance mode".
> 
> When chunkserver with "temporary maintenance mode" will connect again then master will turns off "temporary maintenance mode".
> 
> With such approach you will be able to restart chunkservers, or do some quick maintenance without changing anything in the master server. In such case replication will not start, but during real server failure chunkserver will not disconnect gracefully and in such case replication will start immediately.
>

**Comment by acid-maker** [comment]
I like the idea of maintenance mode timeouts. I will add two timers. One for classic maintenance mode (default to 0 - which will mean "no timeout") and second for this new "quick" or "temporary" maintenance mode (default to 1800).

@kiatoa I'll think about it. Removal of overgoal chunks and also system rebalance might be suspended for short (configurable) period of time after connecting of new chunkserver (or after adding HDD with chunks). The question is: How long should it be suspended? Hour?

**Comment by nrm21** [comment]
I just upgraded to 3.0.78 from 3.0.74.  So far this maintenance mode is working very nicely, thanks.  :)
