### ISSUE TITLE
 master: register error (read header: ETIMEDOUT (Operation timed out))

### ISSUE THREAD

**Issue by zhs077** [moosefs/moosefs#92]
Feb 11 23:00:09 mfschunkserver[16565]: masterconn: connection timed out
Feb 11 23:00:10 mfschunkserver[16565]: connecting ...
Feb 11 23:00:10 mfschunkserver[16565]: connected to Master
Feb 11 23:00:10 mfsmount[20729]: master: tcp recv error: ETIMEDOUT (Operation timed out) (header)
Feb 11 23:00:11 mfsmount[20729]: master: register error (read header: ETIMEDOUT (Operation timed out))
Feb 11 23:00:12 mfsmount[20729]: master: register error (read header: ETIMEDOUT (Operation timed out))
Feb 11 23:00:15 mfsmount[20729]: master: register error (read header: ETIMEDOUT (Operation timed out))
Feb 11 23:00:16 mfsmount[20729]: master: register error (read header: ETIMEDOUT (Operation timed out))
Feb 11 23:00:19 mfsmount[20729]: master: register error (read header: ETIMEDOUT (Operation timed out))
Feb 11 23:00:20 mfschunkserver[16565]: masterconn: connection timed out
Feb 11 23:00:20 mfschunkserver[16565]: connecting ...
Feb 11 23:00:20 mfschunkserver[16565]: connected to Master

version is 2.0.71

**Comment by xandrus** [comment]
Hi,
It looks like you don't have enabled overcommit memory. Please read this article:
https://sourceforge.net/p/moosefs/mailman/moosefs-users/thread/53189C6A.2020503@purdue.edu/

**Comment by oxide94** [comment]
Hi @zhs077,

We also strongly recommend to upgrade your MooseFS Cluster to the latest stable version, 3.0.100 as MooseFS 2.x branch is not supported anymore (see: https://moosefs.com/support/#moosefs-support-status). We are not going to release any new fixes for MooseFS 2.x. We fixed a lot of issues in MooseFS 3.x.

Actually upgrading MooseFS between major versions (e.g. from 2.x to 3.x) is as simple, as upgrading between minor versions (e.g. from 2.0.89 to 2.0.91). This process is shortly described in "MooseFS 2.0 Upgrade Guide", Chapter 2: "MooseFS 2.0 (CE and Pro) upgrade to newer version" (p. 5). You can obtain it from [here](https://moosefs.com/support/#documentation).

What I would like to mention is, that after stopping Master Server, we strongly recommend to make a backup of dumped `metadata.mfs` file. That's it. So in terms of Master upgrade, Please follow this scenario:

1. Upgrade `moosefs-master` package
2. Run `mfsmaster stop` (this will stop old version and dump `metadata.mfs`)
3. Run `cp /var/lib/mfs/metadata.mfs ~/metadata_YYYYMMDD_BACKUP.mfs` (in this example - to homedir, but any other safe place is of course good)
4. Run `sync`
5. Run `mfsmaster start` (this will start new version)

Then, upgrade MooseFS Chunkservers in a rolling fashion (i.e. "one-by-one").
At the very end, upgrade MooseFS Clients when it is convenient for you.

Thank you,
Best regards,
Peter / MooseFS Team
