### ISSUE TITLE
HDD list not showing in cgi server web interface - 3.0.100

### ISSUE THREAD

**Issue by kiranranjane** [moosefs/moosefs#93]
I am using version: 3.0.100 with 5 chunkservers with 10 ssd disk each, When I go to the web cgi interface under disk tab section I get this below error, How can I fix the below error:

Traceback (most recent call last):
  File "/usr/share/mfscgi/mfs.cgi", line 4514, in 
    data,length = conn.command(CLTOCS_HDD_LIST,CSTOCL_HDD_LIST)
  File "/usr/share/mfscgi/mfs.cgi", line 1423, in command
    raise RuntimeError("MFS communication error")
RuntimeError: MFS communication error

**Comment by oxide94** [comment]
Hi @kiranranjane,

is MooseFS CGI package (`moosefs-cgi`) in the the same version as other MooseFS components are? Could you please check it in top right corner on CGI website or running (depending on the OS):

* `rpm -qa | grep moose` (CentOS / RHEL / other RPM-based distros)
* `dpkg -l | grep moose` (Ubuntu / Debian / other DEB-based distros)

Thanks,
Peter / MooseFS Team

**Comment by kiranranjane** [comment]
Its a new installation of 3.0.100 on all ubuntu servers.

**Comment by kiranranjane** [comment]
dpkg -l | grep moose
ii  moosefs-cgi                         3.0.100-1                                  amd64        MooseFS CGI Monitor
ii  moosefs-cgiserv                     3.0.100-1                                  amd64        Simple CGI-capable HTTP server to run MooseFS CGI Monitor
ii  moosefs-cli                         3.0.100-1                                  amd64        MooseFS CLI Utility
ii  moosefs-master                      3.0.100-1                                  amd64        MooseFS master (metadata) server
oneadmin@NY-Controller-A-01:~$

**Comment by oxide94** [comment]
Thanks. We'll check it.

**Comment by oxide94** [comment]
Hi @kiranranjane,

Could you please first of all check MTU size on all MooseFS components and the machine where MFS CGI and MFS CGISERV is installed?

Thanks,
Peter / MooseFS Team

**Comment by kiranranjane** [comment]
Hi Peter,

Indeed it was a MTU issue at switch level due to different MTU set on it. Made changes and now it is fixed

**Comment by oxide94** [comment]
Perfect,

Thanks for the information. I am happy I could help you! :)

Best,
Peter / MooseFS Team
