### ISSUE TITLE
move chunk 

### ISSUE THREAD

**Issue by zhs077** [moosefs/moosefs#96]
I am restart chunkserver ,the system message print 
Mar 13 14:38:02 mfschunkserver[11002]: move chunk /cache9/ -> /cache3/ (chunk: 000000003004EC0C_00000001)
Mar 13 14:38:02 mfschunkserver[11002]: move chunk /cache8/ -> /cache3/ (chunk: 000000002F32A4A5_00000001)

mache space:
/dev/sdb1       3.6T  480G  3.1T  14% /cache1
/dev/sdc1       3.6T  481G  3.1T  14% /cache2
/dev/sdd1       3.6T  484G  3.1T  14% /cache3
/dev/sde1       3.6T  2.0T  1.7T  55% /cache4
/dev/sdg1       3.6T  3.6T  247M 100% /cache6
/dev/sdh1       3.6T  3.6T  236M 100% /cache7
/dev/sdi1       3.6T  3.6T  225M 100% /cache8
/dev/sdj1       3.6T  3.6T  201M 100% /cache9

what to do about it.

**Comment by acid-maker** [comment]
> On 13 Mar, 2018, at 7:40, zhenghuashan <notifications@github.com> wrote:
> 
> I am restart chunkserver ,the system message print
> Mar 13 14:38:02 mfschunkserver[11002]: move chunk /cache9/ -> /cache3/ (chunk: 000000003004EC0C_00000001)
> Mar 13 14:38:02 mfschunkserver[11002]: move chunk /cache8/ -> /cache3/ (chunk: 000000002F32A4A5_00000001)
> 
> mache space:
> /dev/sdb1 3.6T 480G 3.1T 14% /cache1
> /dev/sdc1 3.6T 481G 3.1T 14% /cache2
> /dev/sdd1 3.6T 484G 3.1T 14% /cache3
> /dev/sde1 3.6T 2.0T 1.7T 55% /cache4
> /dev/sdg1 3.6T 3.6T 247M 100% /cache6
> /dev/sdh1 3.6T 3.6T 236M 100% /cache7
> /dev/sdi1 3.6T 3.6T 225M 100% /cache8
> /dev/sdj1 3.6T 3.6T 201M 100% /cache9
> 
> what to do about it.
> 
> 

Why do you want to do something with that? This is correct behaviour. Disks cache8 and cache9 are almost full when disk cache3 is almost empty. Chunkserver automatically balance usage of each disk - to do that it moves chunks between disks.

If you really want to turn it off (I can't find a reason for that, but still ...) then in mfschunkserver.cfg set option HDD_REBALANCE_UTILIZATION to 0 and reload your chunkserver.

-- 
Regards,
Jakub Kruszona-Zawadzki
- - - - - - - - - - - - - - - -
Segmentation fault (core dumped)
Phone: +48 602 212 039
