### ISSUE TITLE
mfs used space issue

### ISSUE THREAD

**Issue by zhs077** [moosefs/moosefs#97]
i am use  /usr/local/mfs/bin/mfsdirinfo -g /mnt/mfs/ 
result use space are 361914G ，353T
/mnt/mfs/:
 inodes:                 0
  directories:           0
  files:                 0
 chunks:                 0
 length:            175826
 size:              180957
 realsize:          361914
but I df -h used 435T
[root@PSjsntdx3tx55 ~]# df -h
Filesystem          Size  Used Avail Use% Mounted on
/dev/sda3           1.8T  541G  1.3T  30% /
tmpfs                32G     0   32G   0% /dev/shm
/dev/sda1           477M   56M  396M  13% /boot
/dev/sdb1           3.6T  3.6T  263M 100% /cache1
/dev/sdc1           3.6T  3.6T  190M 100% /cache2
/dev/sdd1           3.6T  3.6T  222M 100% /cache3
/dev/sde1           3.6T  3.6T  256M 100% /cache4
/dev/sdf1           3.6T  3.6T  213M 100% /cache5
/dev/sdg1           3.6T  3.6T  242M 100% /cache6
/dev/sdh1           3.6T  3.6T  183M 100% /cache7
/dev/sdi1           3.6T  3.6T  188M 100% /cache8
/dev/sdj1           3.6T  3.6T   52M 100% /cache9
/dev/sdk1           137G   60M  136G   1% /cache10
/dev/sdl1           137G   60M  136G   1% /cache11
xxxxxxx:9421  475T  435T   41T  92% /mnt/mfs

 I don't understand where the extra space is.

**Comment by tclh123** [comment]
`df -h` shows the sum of all disks volume, but not exactly what used by moosefs.

For example,
/data1 is the mountpoint,
/data1/mfsdata is a moosefs data folder,
/data1/other_blob is other directory which isn't a moosefs stuff.
`df -h` will show the size like `df -h /data1` which includes /data1/other_blob.
