### ISSUE TITLE
chunkserver disconnect 

### ISSUE THREAD

**Issue by zhs077** [moosefs/moosefs#99]
master log: 
Feb 24 14:01:05 chunkserver disconnected - ip: XXXXXX / port: 9422, usedspace: 5360153464832 (4992.03 GiB), totalspace: 35174947516416 (32759.22 GiB)

chunkserver log:
Feb 24 14:01:04 uadianxin124 mfschunkserver[29772]: masterconn: connection timed out
Feb 24 14:01:05 uadianxin124 mfschunkserver[29772]: connecting ...
Feb 24 14:01:05 uadianxin124 mfschunkserver[29772]: connected to Master

How to explain the appearance？

**Comment by oxide94** [comment]
Hi @zhs077,

It can indicate some network issues, but as I can see, Chunkserver was immediately connected again. These messages are rather info messages, but just in case please check your network (e.g. number of packets dropped on the network interface on this Chunkserver and on Master Server, number of errors on this interface and on a switch, etc.).

Thanks,
Peter / MooseFS Team

**Comment by borkd** [comment]
Any chance master was caught busy writing out dirty memory to storage, i.e. recently rotated metadata dump in addition to other things that happen on the hour?

**Comment by oxide94** [comment]
@zhs077,
Regarding to what @borkd said - please let us know whether in MFSCGI, in "INFO" tab you can see "last metadata save status" as "Saved in background" (in green) or "saved in foreground" (in yellow).

If you can see "Saved in foreground" it may explain everything. If so, please check out our Best Practice number 7. "`overcommit_memory` on Master Servers (Linux only)" [here](https://moosefs.com/support/#best-practices). Everything is quite well-described there. It should help in this case.

Thanks,
Best regards,
Peter / MooseFS Team

**Comment by 4Dolio** [comment]
Nice feature MooseFS team!  Oh I miss you guys, i need to get back to using MFS... sigh, need a TARDIS..
